### ISSUE TITLE
Leo doesn't start with: leo --gui=console

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1007]
Running commit 9953939 here is console log:
Empty setting name in False
set parent @settings
loading npyscreen
Leo 5.8.1 devel, build 20181013173725, Sat Oct 13 17:37:25 PDT 2018
rss.py: can not import feedparser
Traceback (most recent call last):
  File "N:\git\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "N:\git\leo-editor\leo\core\runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2261, in load
    ok = lm.doPostPluginsInit()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2319, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2362, in openEmptyWorkBook
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3080, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3117, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3291, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)
  File "N:\git\leo-editor\leo\core\leoFileCommands.py", line 652, in openLeoFile
    silent=silent,
  File "N:\git\leo-editor\leo\core\leoFileCommands.py", line 527, in getLeoFile
    recoveryNode = fc.readExternalFiles(fileName)
  File "N:\git\leo-editor\leo\core\leoFileCommands.py", line 612, in readExternalFiles
    c.atFileCommands.readAll(c.rootVnode(), force=False)
  File "N:\git\leo-editor\leo\core\leoAtFile.py", line 539, in readAll
    c.raise_error_dialogs()
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 2478, in raise_error_dialogs
    c.rootPosition().b = saved_body
  File "N:\git\leo-editor\leo\core\leoNodes.py", line 1613, in __set_b
    c.setBodyString(p, val)
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 1164, in setBodyString
    c.frame.body.setSelectionAreas(s, None, None)
  File "N:\git\leo-editor\leo\core\leoFrame.py", line 668, in setSelectionAreas
    pos = w.getYScrollPosition()
AttributeError: 'NoneType' object has no attribute 'getYScrollPosition'
[end]

**Comment by maphew** [comment]
Do the `leo-console` or `leo-c` convenience wrapper scripts work?

**Comment by edreamleo** [comment]
Fixed at 1f434d0ad.

**Comment by edreamleo** [comment]
On Mon, Oct 29, 2018 at 7:28 PM matt wilkie <notifications@github.com>
wrote:

> Do the leo-console or leo-c convenience wrapper scripts work?
>
No. It isn't your problem ;-) Fixed at 1f434d0
<https://github.com/leo-editor/leo-editor/commit/1f434d0ad7945e94c09c852a5a0d6eec974bb535>.


Edward

**Comment by LewisNeal** [comment]
All fixed, Thanks.
