### ISSUE TITLE
Leo can't read form feeds in .leo files

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1036]
Inserting a form feed, as in [pymacs.el.in](https://raw.githubusercontent.com/pinard/Pymacs/master/pymacs.el.in) generates the message:
```
bad .leo file: pymacs.leo
ParseError('not well-formed (invalid token): line 85, column 29',)
```
Here is the traceback from earlier version of Leo, with an earlier version of pymacs.leo in leo-editor-contrib.
```
Traceback (most recent call last):
  File "c:\leo.repo\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "c:\leo.repo\leo-editor\leo\core\runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 2262, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 2432, in doPrePluginsInit
    lm.readGlobalSettingsFiles()
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 2202, in readGlobalSettingsFiles
    theme_path = lm.computeThemeFilePath()
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 1845, in computeThemeFilePath
    theme_c = lm.openSettingsFile(path)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 2171, in openSettingsFile
    readAtFileNodesFlag=False, silent=True)
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 653, in openLeoFile
    silent=silent,
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 516, in getLeoFile
    v = FastRead(c, self.gnxDict).readFile(fileName)
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 68, in readFile
    return self.readWithElementTree(path, s)
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 91, in readWithElementTree
    hidden_v = self.scanVnodes(gnx2body, self.gnx2vnode, gnx2ua, v_elements)
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 312, in scanVnodes
    v_element_visitor(v_elements, hidden_v)
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 302, in v_element_visitor
    v_element_visitor(e, v)
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 302, in v_element_visitor
    v_element_visitor(e, v)
  File "c:\leo.repo\leo-editor\leo\core\leoFileCommands.py", line 246, in v_element_visitor
    gnx = e.attrib['t']
KeyError: 't'
```

**Comment by edreamleo** [comment]
Fixed at b400f4 in devel.
