### ISSUE TITLE
Pip install fails with "No module named 'leo'"

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1079]
```
> pip install -e .
Obtaining file:///C:/Users/mattw/code/leo-editor
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command c:\apps\miniconda3\envs\leo-dev\python.exe c:\apps\miniconda3\envs\leo-dev\lib\site-packages\pip\_vendor\pep517\_in_process.py get_requires_for_build_wheel C:\Users\mattw\AppData\Local\Temp\tmp4a0kjug_:
  Traceback (most recent call last):
    File "c:\apps\miniconda3\envs\leo-dev\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "c:\apps\miniconda3\envs\leo-dev\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\apps\miniconda3\envs\leo-dev\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-z1_1z9io\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-z1_1z9io\overlay\Lib\site-packages\setuptools\build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "C:\Users\mattw\AppData\Local\Temp\pip-build-env-z1_1z9io\overlay\Lib\site-packages\setuptools\build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 17, in <module>
      import leo.core.leoGlobals as g
  ModuleNotFoundError: No module named 'leo'

  ----------------------------------------
Command "c:\apps\miniconda3\envs\leo-dev\python.exe c:\apps\miniconda3\envs\leo-dev\lib\site-packages\pip\_vendor\pep517\_in_process.py get_requires_for_build_wheel C:\Users\mattw\AppData\Local\Temp\tmp4a0kjug_" failed with error code 1 in C:\Users\mattw\code\leo-editor
```

First reported by Neal Becker on the mailing list, https://groups.google.com/d/msg/leo-editor/yPleZaz5T2E/UpnQpe8bFAAJ. 

Later in same thread @vitalije gave the vital _(heheh)_ clue that sys.path didn't contain the leo-editor folder. That turned out not to be quite the case, but it's the right answer nonetheless. More in a minute.

**Comment by maphew** [comment]
With pip >v10 _and_ the presence of `pyproject.toml` pip creates a virtual environment first, then puts an **sdist** (source distribution) into it, and then runs the rest of it's business from there. In that virtual environment Leo is not yet installed, so the import leo statement fails.

Rename `pyproject.toml` or otherwise move it out of the way, and pip install will work again, same as pip v9 and earlier.

At any rate, editing sys.path was the fix (commit d3a6494).

I believe it's related to:
`python path/to/setup.py {...}` will fail, while
`cd path/to`
`python setup.py {..}` succeeds.
