### ISSUE TITLE
Right-click handlers can crash Leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1084]
Right-clicking a headline caused this traceback:
```
Traceback (most recent call last):
  File "/home/jnicoll/leo-editor/leo/plugins/qt_tree.py", line 732, in onContextMenu
    h(c, p, menu)
  File "/home/jnicoll/leo-editor/leo/plugins/contextmenu.py", line 109, in configuredcommands_rclick
    for cmd, desc in cmds:
ValueError: need more than 1 value to unpack
Aborted (core dumped)
```

**Comment by edreamleo** [comment]
Fixed at rev a3e4998d4 by adding guards in two places.
