### ISSUE TITLE
Unbounded recursion in edit-headline command

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1086]
c.executeMinibufferCommand('edit-headline') or Alt-X edit-headline yield:
```
Traceback (most recent call last):

   File "C:\Users\IH\Leo-Git\leo-editor\leo\core\leoGlobals.py", line 7389, in getScript
    elif w and p == c.p and useSelectedText and w.hasSelection():

   File "C:\Users\IH\Leo-Git\leo-editor\leo\core\leoCommands.py", line 1170, in __get_p
    return c.currentPosition()

   File "C:\Users\IH\Leo-Git\leo-editor\leo\core\leoCommands.py", line 867, in currentPosition
    if hasattr(c, '_currentPosition') and getattr(c, '_currentPosition'):

RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by edreamleo** [comment]
I am going to close this.  Everything works as expected.  Perhaps a plugin is involved.
