### ISSUE TITLE
moving between nodes crashes Leo console gui

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1118]
Start leo running the console gui.

move cursor to Tree Pane
Use the arrow down key to move from node to node.
test_node_1
test_node_2

This causes leo to crash. Here is log:

Empty setting name in False
set parent @settings
extractExecutableString rest rest
extractExecutableString rest python
extractExecutableString rest rest
extractExecutableString rest python
loading npyscreen
Leo 5.9-final-devel, build 20190409061733, Tue Apr  9 06:17:32 UTC 2019
rss.py: can not import feedparser
Traceback (most recent call last):
  File "N:\git\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "N:\git\leo-editor\leo\core\runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2290, in load
    g.app.gui.runMainLoop()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1586, in runMainLoop
    self.curses_app.run()
  File "N:/git/leo-editor/leo/external\npyscreen\apNPSApplication.py", line 46, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "N:/git/leo-editor/leo/external\npyscreen\npyssafewrapper.py", line 47, in wrapper
    wrapper_no_fork(call_function)
  File "N:/git/leo-editor/leo/external\npyscreen\npyssafewrapper.py", line 106, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "N:/git/leo-editor/leo/external\npyscreen\apNPSApplication.py", line 37, in __remove_argument_call_main
    return self.main()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2781, in main
    g.app.gui.run()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1603, in run
    self.top_form.edit()
  File "N:/git/leo-editor/leo/external\npyscreen\fm_form_edit_loop.py", line 111, in edit
    self._widgets__[self.editw].edit()
  File "N:/git/leo-editor/leo/external\npyscreen\wgboxwidget.py", line 181, in edit
    self.entry_widget.edit()
  File "N:/git/leo-editor/leo/external\npyscreen\wgmultiline.py", line 623, in edit
    self.get_and_use_key_press()
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 579, in get_and_use_key_press
    self.handle_input(ch)
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 113, in handle_input
    f(i)
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 3604, in h_cursor_line_down
    c.frame.tree.select(p)
  File "N:\git\leo-editor\leo\core\leoFrame.py", line 1479, in select
    self.selectHelper(p)
  File "N:\git\leo-editor\leo\core\leoFrame.py", line 1515, in selectHelper
    self.select_new_node(old_p, p)
  File "N:\git\leo-editor\leo\core\leoFrame.py", line 1563, in select_new_node
    self.set_body_text_after_select(p, old_p)
TypeError: set_body_text_after_select() missing 1 required positional argument: 'traceTime'

**Comment by edreamleo** [comment]
The fix looks easy.  I'll fix it before the next 5.9 beta release.

**Comment by edreamleo** [comment]
Fixed in both devel and py3.

**Comment by LewisNeal** [comment]
Moving between nodes works now.
However after editing a file and then Tab to [Quit Leo], I pressed <enter>. Here is traceback:

[snip] loading npyscreen
Leo 5.9-final-devel, build 20190409061733, Tue Apr  9 06:17:32 UTC 2019
rss.py: can not import feedparser
Traceback (most recent call last):
  File "N:\git\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "N:\git\leo-editor\leo\core\runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2290, in load
    g.app.gui.runMainLoop()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1586, in runMainLoop
    self.curses_app.run()
  File "N:/git/leo-editor/leo/external\npyscreen\apNPSApplication.py", line 46, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "N:/git/leo-editor/leo/external\npyscreen\npyssafewrapper.py", line 47, in wrapper
    wrapper_no_fork(call_function)
  File "N:/git/leo-editor/leo/external\npyscreen\npyssafewrapper.py", line 106, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "N:/git/leo-editor/leo/external\npyscreen\apNPSApplication.py", line 37, in __remove_argument_call_main
    return self.main()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2781, in main
    g.app.gui.run()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1603, in run
    self.top_form.edit()
  File "N:/git/leo-editor/leo/external\npyscreen\fm_form_edit_loop.py", line 111, in edit
    self._widgets__[self.editw].edit()
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 526, in edit
    self._edit_loop()
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 346, in _edit_loop
    self.get_and_use_key_press()
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 579, in get_and_use_key_press
    self.handle_input(ch)
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 113, in handle_input
    f(i)
  File "N:/git/leo-editor/leo/external\npyscreen\wgbutton.py", line 116, in h_toggle
    self.whenPressed()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 719, in whenPressed
    g.app.onQuit()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 1413, in onQuit
    g.app.sessionManager.save_snapshot()
  File "N:\git\leo-editor\leo\core\leoSessions.py", line 112, in save_snapshot
    session = self.get_session()
  File "N:\git\leo-editor\leo\core\leoSessions.py", line 45, in get_session
    mf = getattr(g.app.gui.frameFactory, 'masterFrame', None)
AttributeError: 'LeoCursesGui' object has no attribute 'frameFactory'
[end]

**Comment by LewisNeal** [comment]
Identical traceback if you don't edit the file. Crash occurs when you Quit Leo.

**Comment by edreamleo** [comment]
Fixed the second crash in both devel and py3.  Please *reopen* this item if problems remain.
