### ISSUE TITLE
Crash when doing git-diff in leoDist.leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1136]
```
Traceback (most recent call last):

   File "c:\leo.repo\leo-editor\leo\core\leoGlobals.py", line 320, in new_cmd_wrapper
    func(self, event=event)

   File "c:\leo.repo\leo-editor\leo\commands\editFileCommands.py", line 342, in gitDiff
    GitDiffController(c=self.c).git_diff(rev1='HEAD')

   File "c:\leo.repo\leo-editor\leo\commands\editFileCommands.py", line 584, in git_diff
    ok = self.diff_revs(rev1, rev2)

   File "c:\leo.repo\leo-editor\leo\commands\editFileCommands.py", line 604, in diff_revs
    self.diff_file(fn=fn, rev1=rev1, rev2=rev2)

   File "c:\leo.repo\leo-editor\leo\commands\editFileCommands.py", line 634, in diff_file
    c1 = self.make_at_clean_outline(fn, root, s1, rev1)

   File "c:\leo.repo\leo-editor\leo\commands\editFileCommands.py", line 807, in make_at_clean_outline
    assert old_public_lines

AssertionError
```

**Comment by edreamleo** [comment]
Fixed at a4dcf5 in devel.
