### ISSUE TITLE
gui=console  'TopFrame' object has no attribute 'saveState'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1153]
Running commit ee315b1 with gui=console.
After editing, Quit and successfully saving a file, the console is locked and needs to be force closed. Here is console log:

loading npyscreen
Leo 6.0-devel, dock branch
rss.py: can not import feedparser
wrote C:/Users/lewis/.leo/leo.session
Traceback (most recent call last):
  File "N:\git\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "N:\git\leo-editor\leo\core\runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2363, in load
    g.app.gui.runMainLoop()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1584, in runMainLoop
    self.curses_app.run()
  File "N:/git/leo-editor/leo/external\npyscreen\apNPSApplication.py", line 46, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "N:/git/leo-editor/leo/external\npyscreen\npyssafewrapper.py", line 47, in wrapper
    wrapper_no_fork(call_function)
  File "N:/git/leo-editor/leo/external\npyscreen\npyssafewrapper.py", line 106, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "N:/git/leo-editor/leo/external\npyscreen\apNPSApplication.py", line 37, in __remove_argument_call_main
    return self.main()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2774, in main
    g.app.gui.run()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1601, in run
    self.top_form.edit()
  File "N:/git/leo-editor/leo/external\npyscreen\fm_form_edit_loop.py", line 111, in edit
    self._widgets__[self.editw].edit()
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 526, in edit
    self._edit_loop()
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 346, in _edit_loop
    self.get_and_use_key_press()
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 579, in get_and_use_key_press
    self.handle_input(ch)
  File "N:/git/leo-editor/leo/external\npyscreen\wgwidget.py", line 113, in handle_input
    f(i)
  File "N:/git/leo-editor/leo/external\npyscreen\wgbutton.py", line 116, in h_toggle
    self.whenPressed()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 718, in whenPressed
    g.app.onQuit()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 1409, in onQuit
    if not g.app.closeLeoWindow(w):
  File "N:\git\leo-editor\leo\core\leoApp.py", line 1313, in closeLeoWindow
    g.app.saveWindowState(c)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 1430, in saveWindowState
    ('windowState:', dw.saveState),
AttributeError: 'TopFrame' object has no attribute 'saveState'
[end]

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report. Fixed at 47865da.
