### ISSUE TITLE
fix[Doc] run Leo --gui=browser in conda miss meta

### ISSUE THREAD

**Issue by ZoomQuiet** [leo-editor/leo-editor#1203]
## base
same -> [fix\[Doc\] install Leo in conda miss PyQtWebEngine · Issue #1202 · leo-editor/leo-editor](https://github.com/leo-editor/leo-editor/issues/1202)

## erro.

༄  leo --gui=browser

    setting leoID from os.getenv('USER'): 'zoomq'
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Alt+) move-past-close
       all Alt+) move-past-close
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Alt+} forward-paragraph
       all Alt+} forward-paragraph-extend-selection
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Ctrl+( add-comments
       all Ctrl+( add-comments
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Ctrl+) delete-comments
       all Ctrl+) delete-comments
       all Ctrl+) delete-comments
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Ctrl+{ promote
       all Ctrl+{ promote
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Ctrl+} demote
       all Ctrl+} demote
    [I 16:13:49 flexx.app] Asset store collected 2 new modules.
    Leo 5.9-b2, build 20190409061733, Tue Apr  9 06:17:32 UTC 2019
    livecode.py: can not import meta
    pip install meta
    livecode.py: can not import meta
    pip install meta

    [I 16:13:50 flexx.app] Serving apps at http://localhost:49190/
    [I 16:13:50 flexx.app] Asset store collected 26 new modules.
    Traceback (most recent call last):
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/urllib/request.py", line 1317, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/http/client.py", line 1229, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/http/client.py", line 1275, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/http/client.py", line 1224, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/http/client.py", line 1016, in _send_output
        self.send(msg)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/http/client.py", line 956, in send
        self.connect()
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/http/client.py", line 1384, in connect
        super().connect()
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/http/client.py", line 928, in connect
        (self.host,self.port), self.timeout, self.source_address)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/socket.py", line 727, in create_connection
        raise err
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/socket.py", line 716, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 61] Connection refused

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/zoomq/miniconda3/envs/leo373/bin/leo", line 10, in <module>
        sys.exit(run())
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/leo/core/runLeo.py", line 72, in run
        g.app.loadManager.load(fileName, pymacs)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/leo/core/leoApp.py", line 2290, in load
        g.app.gui.runMainLoop()
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/leo/plugins/leoflexx.py", line 1225, in runMainLoop
        flx.launch(LeoBrowserApp, runtime)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_funcs.py", line 231, in launch
        return a.launch(runtime, **runtime_kwargs)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_app.py", line 157, in launch
        session = manager.create_session(self.name)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_app.py", line 580, in create_session
        app(flx_session=session, flx_is_app=True)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_app.py", line 77, in __call__
        return self.cls(*a, **kw)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/event/_component.py", line 209, in __init__
        self._comp_init_property_values(property_values)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_component2.py", line 361, in _comp_init_property_values
        self._comp_init_app_component(property_values)  # pops items
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_component2.py", line 340, in _comp_init_app_component
        self._session._register_component(self, custom_id)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_session.py", line 392, in _register_component
        self._register_component_class(cls)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_session.py", line 444, in _register_component_class
        self._register_module(cls.__jsmodule__)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_session.py", line 516, in _register_module
        self.send_command('DEFINE', suffix, asset.name, asset.to_string())
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_asset.py", line 195, in to_string
        self._source_str = self._get_from_url(self._source)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/site-packages/flexx/app/_asset.py", line 203, in _get_from_url
        return urlopen(req, timeout=5.0).read().decode()
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/urllib/request.py", line 525, in open
        response = self._open(req, data)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/urllib/request.py", line 543, in _open 
        '_open', req)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/urllib/request.py", line 1360, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/Users/zoomq/miniconda3/envs/leo373/lib/python3.7/urllib/request.py", line 1319, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 61] Connection refused>

## fixed

༄  conda run pip install meta

    Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
    Collecting meta
      Downloading https://mirrors.aliyun.com/pypi/packages/78/4e/bf6414dd628664eee7d03831f36fe9ffd43708c36c8bd43ae56ebe7cd69d/meta-1.0.2.tar.gz (49kB)
    Building wheels for collected packages: meta
      Building wheel for meta (setup.py): started
      Building wheel for meta (setup.py): finished with status 'done'
      Stored in directory: /Users/zoomq/Library/Caches/pip/wheels/54/61/ba/fd385140a07d8061d7e49848d0e79872cdcd12fe77fe5bce14
    Successfully built meta
    Installing collected packages: meta
    Successfully installed meta-1.0.2

༄  leo --gui=browser

    setting leoID from os.getenv('USER'): 'zoomq'
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Alt+) move-past-close
       all Alt+) move-past-close
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Alt+} forward-paragraph
       all Alt+} forward-paragraph-extend-selection
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Ctrl+( add-comments
       all Ctrl+( add-comments
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Ctrl+) delete-comments
       all Ctrl+) delete-comments
       all Ctrl+) delete-comments
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Ctrl+{ promote
       all Ctrl+{ promote
    duplicate, (not conflicting) key bindings in myLeoSettings.leo
       all Ctrl+} demote
       all Ctrl+} demote
    [I 16:15:15 flexx.app] Asset store collected 2 new modules.
    Leo 5.9-b2, build 20190409061733, Tue Apr  9 06:17:32 UTC 2019

    [I 16:15:16 flexx.app] Serving apps at http://localhost:49190/
    [I 16:15:16 flexx.app] Asset store collected 26 new modules.

## suggest:

append meta as Leo depend package ;-)

**Comment by maphew** [comment]
Meta depends was added in c45e2d97 (devel branch).

I wasn't getting a crash with meta not installed though, just a warning to the Log pane. So leaving this open in case there's something else going on.

**Comment by edreamleo** [comment]
Let's close this for now.
