### ISSUE TITLE
pip install --editable error on linux

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1290]
`Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/matt/code/leo-editor/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/matt/code/leo-editor/`

when running `pip install -e code/leo-editor` on a Linux Mint 18.02 laptop I've not used for many months. Code folder is up to date wih current repo.

**Comment by maphew** [comment]
Error message after `pip3 install --upgrade pip` and then using `sudo -H pip install -e code/leo-editor`.

Next problem is a python2/3 conflict. We already tell pip Leo is v3, though not 3.6 as the message below warns about. I'll change that shortly. I think there's something deeper messed up at the OS level though, because pip uninstall says there's nothing to do, yet also still shows leo stiil intsalled. 

```
$ leo --version

    Leo requires Python 3.6 or higher.
    You may download Python from
    http://python.org/download/
    
Traceback (most recent call last):

  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter

ImportError: No module named '_tkinter'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/matt/code/leo-editor/leo/core/leoApp.py", line 3125, in isValidPython
    message=message)

  File "/home/matt/code/leo-editor/leo/core/leoGlobals.py", line 448, in __init__
    self.createTopFrame()

  File "/home/matt/code/leo-editor/leo/core/leoGlobals.py", line 486, in createTopFrame
    import tkinter as Tk

  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')

ImportError: No module named '_tkinter', please install the python3-tk package
```

```
matt@dell-xps ~/code/leo-editor $ which leo
/usr/local/bin/leo
matt@dell-xps ~/code/leo-editor $ cat /usr/local/bin/leo
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'leo','gui_scripts','leo'
__requires__ = 'leo'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('leo', 'gui_scripts', 'leo')()
    )
matt@dell-xps ~/code/leo-editor $ pip show leo
Name: leo
Version: 6.1-dev-dev32
Summary: An IDE, PIM and Outliner
Home-page: http://leoeditor.com
Author: Edward K. Ream
Author-email: edreamleo@gmail.com
License: MIT License
Location: /home/matt/code/leo-editor
Requires: PyQtWebEngine, docutils, meta, nbformat, pylint, pyflakes, setupext-janitor, shortcutter, sphinx, future, six, flexx
Required-by: 
matt@dell-xps ~/code/leo-editor $ pip uninstall leo
Can't uninstall 'leo'. No files were found to uninstall.
matt@dell-xps ~/code/leo-editor $ sudo pip uninstall leo
The directory '/home/matt/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Can't uninstall 'leo'. No files were found to uninstall.
The directory '/home/matt/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
matt@dell-xps ~/code/leo-editor $ sudo -H pip uninstall leo
Can't uninstall 'leo'. No files were found to uninstall.
```

**Comment by maphew** [comment]
Leo works just fine on this computer from a Conda environment. So the problem lies somewhere in the depths of time and my repeated sallies back and forth between `sudo pip` and `pip install --user` over years. Closing as too-localized until/if I can determine exactly what's going on at the system level.
