### ISSUE TITLE
Crash when reloading after changing a file externally

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1362]
In devel, with the recent fix to #1361 

- Load leoPy.leo.
- Change leoApp.py in an external editor.
  Changed `#@+<< imports >>` to `#@+<< imports >> (changed)`
  Hmm.  This is a non-trivial change to a sentinel.
- A dialog appears warning of the change. Choose "yes" in the dialog.
- The following crash appears:
```
Traceback (most recent call last):

  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 60, in on_idle
    callback()

  File "c:\leo.repo\leo-editor\leo\core\leoExternalFiles.py", line 150, in on_idle
    self.idle_check_commander(c)

  File "c:\leo.repo\leo-editor\leo\core\leoExternalFiles.py", line 178, in idle_check_commander
    self.idle_check_at_file_node(c, p)

  File "c:\leo.repo\leo-editor\leo\core\leoExternalFiles.py", line 195, in idle_check_at_file_node
    c.refreshFromDisk(p)

  File "c:\leo.repo\leo-editor\leo\commands\commanderFileCommands.py", line 290, in refreshFromDisk
    at.read(p, force=True)

  File "c:\leo.repo\leo-editor\leo\core\leoAtFile.py", line 353, in read
    FastAtRead(c, gnx2vnode).read_into_root(contents, fileName, root)

  File "c:\leo.repo\leo-editor\leo\core\leoAtFile.py", line 3642, in read_into_root
    delims, first_lines, lines, path, start_i)

  File "c:\leo.repo\leo-editor\leo\core\leoAtFile.py", line 3342, in scan_lines
    gnx, indent, body = stack.pop()

IndexError: pop from empty list
```

**Comment by edreamleo** [comment]
The change I made had the effect of destroying the `#@+<<`.  So this was a serious user error :-)

The relevant regex is: `^(\s*){delim1}@(\+|-){ref}\s*{delim2}$`

where {ref} is: `g.angleBrackets(r'(.*)')`

By adding something after `{ref}` I destroyed the opening sentinel.  The crash happened when trying to handle the *unmatched* closing sentinel.

I am not going to attempt error recovery in `<< 4. handle section refs >>`.  Doing so could easily do more harm than good.  Ditto for changing the regex.

**Summary**

The change I made was a serious user error.  Error recovery could easily do more harm than good.

I am going to close this issue.
