### ISSUE TITLE
Show-settings-outline yields "AttributeError: 'LoadManager' object has no attribute 'theme_c'"

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1374]
Leo >> `Alt-X: show-settings-outline` yields:

~~~
Leo Log Window
Leo 6.1-devel, devel branch, build a6809b7721
2019-10-08 14:17:25 -0500
Python 3.7.1, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.18362) SP0
-active-settings
reading settings in D:/code-maphew/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/mhwilkie/.leo/myLeoSettings.leo
Traceback (most recent call last):

  File "d:\code-maphew\leo-editor\leo\core\leoGlobals.py", line 293, in new_cmd_wrapper
    func(self, event=event)

  File "d:\code-maphew\leo-editor\leo\commands\helpCommands.py", line 1164, in showSettingsOutline
    self.c.config.createActivesSettingsOutline()

  File "d:\code-maphew\leo-editor\leo\core\leoConfig.py", line 1756, in createActivesSettingsOutline
    ActiveSettingsOutline(self.c)

  File "d:\code-maphew\leo-editor\leo\core\leoConfig.py", line 916, in __init__
    self.start()

  File "d:\code-maphew\leo-editor\leo\core\leoConfig.py", line 936, in start
    self.create_commanders_list()

  File "d:\code-maphew\leo-editor\leo\core\leoConfig.py", line 952, in create_commanders_list
    if lm.theme_c:

AttributeError: 'LoadManager' object has no attribute 'theme_c'
~~~

**Comment by technatica** [comment]
This works on linux with a different python/pyqt version.

Leo 6.1-devel, devel branch, build 10171e16af

2019-10-08 13:50:40 -0700

Python 3.6.8, PyQt version 5.13.1

linux


Chris



n 5.13.1
nux
.

**Comment by edreamleo** [comment]
@maphew Thanks for this testing.

**Comment by edreamleo** [comment]
Should be fixed at rev 2a61f52 in devel.  Please reopen as needed.

**Comment by maphew** [comment]
2a61f52 doesn't yield LM error, but now I get a different one. Let me if this should be a new issue. This isn't the same machine I opened this issue with.

Render pane:
~~~
legend:
leoSettings.leo
System Message: WARNING/2 (<string>, line 4)
Block quote ends without a blank line; unexpected unindent.
@ @button, @command, @mode
System Message: WARNING/2 (<string>, line 5)
Block quote ends without a blank line; unexpected unindent.
[D] default settings [F] local file: myLeoSettings.leo [M] myLeoSettings.leo [T] theme file: ZephyrDarkTheme.leo 
~~~

Log:
~~~
Leo Log Window
Leo 6.1-devel, devel branch, build 2a61f52701
2019-10-08 17:58:06 -0500
Python 3.6.9, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.18362) SP0
D:/Matt/Dropbox/.leo/myLeoSettings.leo-active-settings
reading settings in D:/matt/code/leo-editor/leo/config/leoSettings.leo
reading settings in D:/Matt/Dropbox/.leo/myLeoSettings.leo
reading settings in D:/matt/code/leo-editor/leo/themes/ZephyrDarkTheme.leo
reading settings in D:/Matt/Dropbox/.leo/myLeoSettings.leo
~~~

Console:
~~~
Leo Log Window
Leo 6.1-devel, devel branch, build 2a61f52701
2019-10-08 17:58:06 -0500
Python 3.6.9, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.18362) SP0
D:/Matt/Dropbox/.leo/myLeoSettings.leo-active-settings
reading settings in D:/matt/code/leo-editor/leo/config/leoSettings.leo
reading settings in D:/Matt/Dropbox/.leo/myLeoSettings.leo
reading settings in D:/matt/code/leo-editor/leo/themes/ZephyrDarkTheme.leo
reading settings in D:/Matt/Dropbox/.leo/myLeoSettings.leo
~~~

**Comment by maphew** [comment]
Ahh, excuse the noise. This is the first time I've used the command and didn't know what to expect. I thought Render was supposed to show the outline. I didn't realize a new document is created and that settings are in the Outline pane.
