### ISSUE TITLE
can not import leo.plugins.importers.ipynb

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1382]
Run leo with viewrendered plugin disabled:

Leo Log Window
Leo 6.1-devel, devel branch, build c79238e4d2
2019-10-10 13:24:32 -0500
Python 3.7.4, PyQt version 5.13.1
Windows 10 AMD64 (build 10.0.18362) SP0
can not import leo.plugins.importers.ipynb
can not import leo.plugins.importers.ipynb
current dir: N:/git/leo-editor
load dir: N:/git/leo-editor/leo/core
global config dir: N:/git/leo-editor/leo/config
home dir: C:/Users/lewis
[snip]

(I think this has only occurred since PyQt5-sip was updated from v4.19.19 to v12.7.0)
Run leo with viewrendered plugin enabled:
Leo Log Window
Leo 6.1-devel, devel branch, build c79238e4d2
2019-10-10 13:24:32 -0500
Python 3.7.4, PyQt version 5.13.1
Windows 10 AMD64 (build 10.0.18362) SP0
can not import leo.plugins.importers.ipynb
can not import leo.plugins.importers.ipynb
current dir: N:/git/leo-editor
load dir: N:/git/leo-editor/leo/core
global config dir: N:/git/leo-editor/leo/config
home dir: C:/Users/lewis
reading settings in N:/git/leo-editor/leo/config/leoSettings.leo
reading settings in C:/Users/lewis/.leo/myLeoSettings.leo
Empty setting name in False
reading settings in C:/Users/lewis/.leo/LeoBlackGraySolarized.leo
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 515, in loadOnePluginHelper
__import__(moduleName)

  File "N:\git\leo-editor\leo\plugins\viewrendered.py", line 239, in <module>
import nbformat

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\nbformat\__init__.py", line 33, in <module>
from .validator import validate, ValidationError

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\nbformat\validator.py", line 12, in <module>
from jsonschema import ValidationError

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\jsonschema\__init__.py", line 31, in <module>
import importlib_metadata

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 547, in <module>
__version__ = version(__name__)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 509, in version
return distribution(distribution_name).version

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 482, in distribution
return Distribution.from_name(distribution_name)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 183, in from_name
dist = next(dists, None)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 425, in <genexpr>
for path in map(cls._switch_path, paths)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 449, in _search_path
if not root.is_dir():

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1358, in is_dir
return S_ISDIR(self.stat().st_mode)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1168, in stat
return self._accessor.stat(self)

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'N:\\git\\leo-editor\\ N:\\git\\leo-editor\\leo'

http serving enabled at 127.0.0.1:8130
pyzo_in_leo requires --global-docks
reading settings in N:/git/leo-editor/leo/doc/quickstart.leo
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 515, in loadOnePluginHelper
__import__(moduleName)

  File "N:\git\leo-editor\leo\plugins\viewrendered.py", line 239, in <module>
import nbformat

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\nbformat\__init__.py", line 33, in <module>
from .validator import validate, ValidationError

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\nbformat\validator.py", line 12, in <module>
from jsonschema import ValidationError

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\jsonschema\__init__.py", line 31, in <module>
import importlib_metadata

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 547, in <module>
__version__ = version(__name__)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 509, in version
return distribution(distribution_name).version

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 482, in distribution
return Distribution.from_name(distribution_name)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 183, in from_name
dist = next(dists, None)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 425, in <genexpr>
for path in map(cls._switch_path, paths)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 449, in _search_path
if not root.is_dir():

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1358, in is_dir
return S_ISDIR(self.stat().st_mode)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1168, in stat
return self._accessor.stat(self)

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'N:\\git\\leo-editor\\ N:\\git\\leo-editor\\leo'

read outline in 0.21 seconds
[end]

Posted for information only. I will reinstall PyQt5-sip v4.19.19

**Comment by LewisNeal** [comment]
I uninstalled PyQt5_sip

Went back to =4.19.18
ERROR: pyqt5 5.13.1 has requirement PyQt5_sip<13,>=4.19.19, but you'll have pyqt5-sip 4.19.18 which is incompatible.
Leo did not run with anything <4.19.19 installed.

I still get same errors running Leo with PyQt5_sip v4.19.19 and viewrendered plugin enabled.

**Comment by maphew** [comment]
I'm ok here with these versions:

PyQt5                    5.12.2
PyQt5-sip                4.19.17
PyQtWebEngine            5.12.1

I'm pretty sure I have pyqt 5.13 on another computer. I won't be at that one until next tuesday though.

**Comment by LewisNeal** [comment]
@maphew did you get to try PyQt5 5.13.1 on your other computer?
I only saw errors once PyQt5-sip was updated from v4.19.19 to v12.7.0

**Comment by maphew** [comment]
Thanks for the bump, I'd forgotten to follow up. Yes, okay on my other computer:

~~~
$ pip list |findstr /i "qt"
PyQt5                    5.13.1
PyQt5-sip                12.7.0
PyQtWebEngine            5.13.0

$ leo-m

--global-docks: False

Leo 6.1-devel, devel branch, build bf84bc2560
2019-10-23 14:22:55 -0500

pyzo_in_leo not loaded: requires --global-docks

wrote C:/Users/mhwilkie/.leo/leo.session
wrote recent file: C:/Users/mhwilkie/.leo/.leoRecentFiles.txt
~~~

Leo: plugins >> show-plugins-info:
~~~
leo.plugins.plugins_menu    myLeoSettings.leo
leo.plugins.free_layout     myLeoSettings.leo
leo.plugins.contextmenu     myLeoSettings.leo
leo.plugins.leo_to_html     myLeoSettings.leo
leo.plugins.livecode        myLeoSettings.leo
leo.plugins.mod_scripting   myLeoSettings.leo
leo.plugins.nav_qt          myLeoSettings.leo
leo.plugins.nodetags        myLeoSettings.leo
leo.plugins.quicksearch     myLeoSettings.leo
leo.plugins.screen_capture  myLeoSettings.leo
leo.plugins.settings_finder myLeoSettings.leo
leo.plugins.stickynotes     myLeoSettings.leo
leo.plugins.todo            myLeoSettings.leo
leo.plugins.viewrendered    myLeoSettings.leo
leo.plugins.active_path     myLeoSettings.leo
~~~

**Comment by LewisNeal** [comment]
No longer any issues after updating to
Python 3.8.0, PyQt version 5.13.2

**Comment by edreamleo** [comment]
@LewisNeal Thanks for these investigations.
