### ISSUE TITLE
Leo hard crash when loading session, non-existent .leo file is blamed

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1415]
For Viktor (@ranvik14) on Windows in a Python virtual environment (not conda) Leo crashes on startup with `unexpected exception loading session` and then `unexpected reading empty workbook` errors on startup. (I note an apparent missing word in 2nd message.) Both tracebacks complain that a .leo file doesn't exist. It doesn't, said file is in an old directory that doesn't exist anymore.

After removing `HOME\.leo` folder Leo starts okay. Putting the problem .leo folder back is a reliable way of reproducing the crash.

This issue is spawned from discussion thread https://groups.google.com/d/msg/leo-editor/JxE7zwStAhA/AZVdD2kVDgAJ and Issue #847.  _They're linked for completeness but reading them is unlikely to shed light here._ The other way around maybe.

I attempted to replicate the error on my machine by creating a new .leo file, closing all other workbooks, closing Leo and then removing the file. Leo restarted fine for me so I think there's more going on than just not being able to find the last open workbook.

@ranvik14, please be ready to post `Log-021` if asked. Also if you still have it keep the `HOME\.leo` folder which causes the crash somewhere as @edreamleo might want to inspect parts of it.

### Error snippets from Log-021
~~~
unexpected exception loading session
Traceback (most recent call last):

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 2601, in doPostPluginsInit
    g.app.sessionManager.load_session(c1, aList)

[...]

 File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 1478, in <listcomp>
    if [x for x in aList if os.path.samefile(x, fn)]:

  File "C:\EE\Python\lib\genericpath.py", line 96, in samefile
    s1 = os.stat(f1)

FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:/users/viktor/pyve/ve4ileo/lib/site-packages/leo/doc/quickstart.leo'
~~~
~~~
unexpected reading empty workbook
Traceback (most recent call last):

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 2614, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()

[...]

  File "C:\EE\Python\lib\genericpath.py", line 96, in samefile
    s1 = os.stat(f1)

FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:/users/viktor/pyve/ve4ileo/lib/site-packages/leo/doc/quickstart.leo'
~~~

**Comment by ranvik14** [comment]
@edreamleo : I assume you uploaded your changes to the leo-devel branch before closing the issue. - Correct?

The reason why I ask is that when I was informed via the GitHub, I tried to verify in my local PyVE environment. - Unfortunately w/o success ...

Here are my notes & logs from this attempt ( #9 ;-) :

::

    Perform another test after Edward closed #1451:

    Fixed #1415. Rewrote computeWorkbookFileName

    1) Re-activate the existing PyVE "leo-dev-opt-b" - OK. - See "Log-022"
    2) Try to start Leo in the existing PyVE "leo-dev-opt-b" w/o closing this running instance of Leo - Not OK. - See "Log-023"

**Comment by edreamleo** [comment]
On Mon, Oct 21, 2019 at 2:37 PM ranvik14 <notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo> : I assume you uploaded your
> changes to the leo-devel branch before closing the issue. - Correct?
>
Yes.  Leo now starts correctly when the ~/.leo folder does not exist.

> The reason why I ask is that when I was informed via the GitHub, I tried
> to verify in my local PyVE environment. - Unfortunately w/o success ...
>
> Here are my notes & logs from this attempt ( #9
> <https://github.com/leo-editor/leo-editor/issues/9> ;-) :
>
> ::
>
> Perform another test after Edward closed #1451:
>
> The issue is #1415, not #1451.

> Fixed #1415. Rewrote computeWorkbookFileName
>
> 1) Re-activate the existing PyVE "leo-dev-opt-b" - OK. - See "Log-022"
> 2) Try to start Leo in the existing PyVE "leo-dev-opt-b" w/o closing this running instance of Leo - Not OK. - See "Log-023"
>
> This means nothing to me.  What is your environment?  What are the results?

Edward

**Comment by ranvik14** [comment]
@edreamleo : Here are my notes & logs from a second attempt to verify your fix in my environment.

1) Re-activate the existing PyVE "leo-dev-opt-b" - OK. - See "Log-024"
2) Try to start Leo in the existing PyVE "leo-dev-opt-b" w/o closing this running instance of Leo - Not OK. - See "Log-025"

Please let me know if you need further information from my local environment.

**Content of Log-024:**

Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6

PS C:\Users\Viktor> cd pyve/github/leo-dev-*
PS C:\Users\Viktor\pyve\github\leo-dev-opt-b> ls

    Verzeichnis: C:\Users\Viktor\pyve\github\leo-dev-opt-b


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       15.10.2019     20:38                Include
d-----       15.10.2019     20:38                Lib
d-----       19.10.2019     09:15                Scripts
-a----       21.10.2019     21:17       11723032 devel.zip
-a----       15.10.2019     20:38             76 pyvenv.cfg


PS C:\Users\Viktor\pyve\github\leo-dev-opt-b> ./scripts/activate.ps1
(leo-dev-opt-b) PS C:\Users\Viktor\pyve\github\leo-dev-opt-b> pip list
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
appdirs                       1.4.3
astroid                       2.3.1
attrs                         19.3.0
Babel                         2.7.0
black                         19.3b0
certifi                       2019.9.11
chardet                       3.0.4
Click                         7.0
colorama                      0.4.1
decorator                     4.4.0
dialite                       0.5.2
docutils                      0.15.2
flexx                         0.8.0
future                        0.18.0
idna                          2.8
imagesize                     1.1.0
importlib-metadata            0.23
ipython-genutils              0.2.0
isort                         4.3.21                                                                                    Jinja2                        2.10.3                                                                                    jsonschema                    3.1.1                                                                                     jupyter-core                  4.6.0                                                                                     lazy-object-proxy             1.4.2                                                                                     MarkupSafe                    1.1.1
mccabe                        0.6.1
meta                          1.0.2
more-itertools                7.2.0
nbformat                      4.4.0
packaging                     19.2
pip                           19.3
pscript                       0.7.1
pyflakes                      2.1.1
Pygments                      2.4.2
pylint                        2.4.2
pyparsing                     2.4.2
PyQt5                         5.13.1
PyQt5-sip                     12.7.0
PyQtWebEngine                 5.13.1
pyrsistent                    0.15.4
pyshortcuts                   1.7
pytz                          2019.3
pywin32                       225
requests                      2.22.0
setupext-janitor              1.1.1
setuptools                    40.8.0
six                           1.12.0
snowballstemmer               2.0.0
Sphinx                        2.2.0
sphinxcontrib-applehelp       1.0.1
sphinxcontrib-devhelp         1.0.1
sphinxcontrib-htmlhelp        1.0.2
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.2
sphinxcontrib-serializinghtml 1.1.3
toml                          0.10.0
tornado                       6.0.3
traitlets                     4.3.3
typed-ast                     1.4.0
urllib3                       1.25.6
webruntime                    0.5.6
wrapt                         1.11.2
zipp                          0.6.0
WARNING: You are using pip version 19.3; however, version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
(leo-dev-opt-b) PS C:\Users\Viktor\pyve\github\leo-dev-opt-b> expand-archive ./devel.zip
(leo-dev-opt-b) PS C:\Users\Viktor\pyve\github\leo-dev-opt-b> pip install --editable ./devel/leo-editor-devel
Obtaining file:///C:/Users/Viktor/pyve/github/leo-dev-opt-b/devel/leo-editor-devel
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: six in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (1.12.0)
Requirement already satisfied: PyQt5>=5.12; python_version >= "3.6" in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (5.13.1)
Requirement already satisfied: setupext-janitor>=1.1 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (1.1.1)
Requirement already satisfied: future in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (0.18.0)
Requirement already satisfied: meta in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (1.0.2)
Requirement already satisfied: pyflakes in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (2.1.1)
Requirement already satisfied: pyshortcuts>=1.7 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (1.7)
Requirement already satisfied: nbformat in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (4.4.0)
Requirement already satisfied: docutils in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (0.15.2)
Requirement already satisfied: pylint in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (2.4.2)
Requirement already satisfied: flexx; python_version >= "3.5" in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (0.8.0)
Requirement already satisfied: sphinx in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (2.2.0)
Requirement already satisfied: black in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (19.3b0)
Requirement already satisfied: PyQtWebEngine in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from leo===6.1-devel) (5.13.1)
Requirement already satisfied: PyQt5_sip<13,>=4.19.19 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from PyQt5>=5.12; python_version >= "3.6"->leo===6.1-devel) (12.7.0)
Requirement already satisfied: pywin32 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from pyshortcuts>=1.7->leo===6.1-devel) (225)
Requirement already satisfied: traitlets>=4.1 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from nbformat->leo===6.1-devel) (4.3.3)
Requirement already satisfied: jupyter-core in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from nbformat->leo===6.1-devel) (4.6.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from nbformat->leo===6.1-devel) (3.1.1)
Requirement already satisfied: ipython-genutils in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from nbformat->leo===6.1-devel) (0.2.0)
Requirement already satisfied: astroid<2.4,>=2.3.0 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from pylint->leo===6.1-devel) (2.3.1)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from pylint->leo===6.1-devel) (0.4.1)
Requirement already satisfied: isort<5,>=4.2.5 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from pylint->leo===6.1-devel) (4.3.21)
Requirement already satisfied: mccabe<0.7,>=0.6 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from pylint->leo===6.1-devel) (0.6.1)
Requirement already satisfied: pscript>=0.7.1 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from flexx; python_version >= "3.5"->leo===6.1-devel) (0.7.1)
Requirement already satisfied: webruntime>=0.5.6 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from flexx; python_version >= "3.5"->leo===6.1-devel) (0.5.6)
Requirement already satisfied: dialite>=0.5.2 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from flexx; python_version >= "3.5"->leo===6.1-devel) (0.5.2)
Requirement already satisfied: tornado in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from flexx; python_version >= "3.5"->leo===6.1-devel) (6.0.3)
Requirement already satisfied: sphinxcontrib-htmlhelp in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (1.0.2)
Requirement already satisfied: sphinxcontrib-applehelp in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (1.0.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (0.7.12)
Requirement already satisfied: sphinxcontrib-jsmath in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (1.0.1)
Requirement already satisfied: setuptools in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (40.8.0)
Requirement already satisfied: Jinja2>=2.3 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (2.10.3)
Requirement already satisfied: snowballstemmer>=1.1 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (2.0.0)
Requirement already satisfied: babel!=2.0,>=1.3 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (2.7.0)
Requirement already satisfied: sphinxcontrib-serializinghtml in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (1.1.3)
Requirement already satisfied: requests>=2.5.0 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (2.22.0)
Requirement already satisfied: sphinxcontrib-devhelp in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (1.0.1)
Requirement already satisfied: imagesize in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (1.1.0)
Requirement already satisfied: sphinxcontrib-qthelp in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (1.0.2)
Requirement already satisfied: Pygments>=2.0 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (2.4.2)
Requirement already satisfied: packaging in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from sphinx->leo===6.1-devel) (19.2)
Requirement already satisfied: attrs>=18.1.0 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from black->leo===6.1-devel) (19.3.0)
Requirement already satisfied: appdirs in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from black->leo===6.1-devel) (1.4.3)
Requirement already satisfied: toml>=0.9.4 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from black->leo===6.1-devel) (0.10.0)
Requirement already satisfied: click>=6.5 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from black->leo===6.1-devel) (7.0)
Requirement already satisfied: decorator in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from traitlets>=4.1->nbformat->leo===6.1-devel) (4.4.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->leo===6.1-devel) (0.15.4)
Requirement already satisfied: importlib-metadata in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->leo===6.1-devel) (0.23)
Requirement already satisfied: wrapt==1.11.* in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from astroid<2.4,>=2.3.0->pylint->leo===6.1-devel) (1.11.2)
Requirement already satisfied: typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from astroid<2.4,>=2.3.0->pylint->leo===6.1-devel) (1.4.0)
Requirement already satisfied: lazy-object-proxy==1.4.* in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from astroid<2.4,>=2.3.0->pylint->leo===6.1-devel) (1.4.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from Jinja2>=2.3->sphinx->leo===6.1-devel) (1.1.1)
Requirement already satisfied: pytz>=2015.7 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from babel!=2.0,>=1.3->sphinx->leo===6.1-devel) (2019.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from requests>=2.5.0->sphinx->leo===6.1-devel) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from requests>=2.5.0->sphinx->leo===6.1-devel) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from requests>=2.5.0->sphinx->leo===6.1-devel) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from requests>=2.5.0->sphinx->leo===6.1-devel) (1.25.6)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from packaging->sphinx->leo===6.1-devel) (2.4.2)
Requirement already satisfied: zipp>=0.5 in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat->leo===6.1-devel) (0.6.0)
Requirement already satisfied: more-itertools in c:\users\viktor\pyve\github\leo-dev-opt-b\lib\site-packages (from zipp>=0.5->importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat->leo===6.1-devel) (7.2.0)
Installing collected packages: leo
  Found existing installation: leo 6.1-devel
    Uninstalling leo-6.1-devel:
      Successfully uninstalled leo-6.1-devel
  Running setup.py develop for leo
Successfully installed leo
WARNING: You are using pip version 19.3; however, version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
(leo-dev-opt-b) PS C:\Users\Viktor\pyve\github\leo-dev-opt-b>

**Content of Log-025:**

(leo-dev-opt-b) PS C:\Users\Viktor\pyve\github\leo-dev-opt-b> pip list                                                  
Package                       Version   Location
----------------------------- --------- ----------------------------------------------------------------
alabaster                     0.7.12
appdirs                       1.4.3
astroid                       2.3.1
attrs                         19.3.0
Babel                         2.7.0
black                         19.3b0
certifi                       2019.9.11
chardet                       3.0.4
Click                         7.0
colorama                      0.4.1
decorator                     4.4.0
dialite                       0.5.2
docutils                      0.15.2
flexx                         0.8.0
future                        0.18.0
idna                          2.8
imagesize                     1.1.0
importlib-metadata            0.23
ipython-genutils              0.2.0
isort                         4.3.21
Jinja2                        2.10.3
jsonschema                    3.1.1
jupyter-core                  4.6.0
lazy-object-proxy             1.4.2
leo                           6.1-devel c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel
MarkupSafe                    1.1.1
mccabe                        0.6.1
meta                          1.0.2
more-itertools                7.2.0
nbformat                      4.4.0
packaging                     19.2
pip                           19.3
pscript                       0.7.1
pyflakes                      2.1.1
Pygments                      2.4.2
pylint                        2.4.2
pyparsing                     2.4.2
PyQt5                         5.13.1
PyQt5-sip                     12.7.0
PyQtWebEngine                 5.13.1
pyrsistent                    0.15.4
pyshortcuts                   1.7
pytz                          2019.3
pywin32                       225
requests                      2.22.0
setupext-janitor              1.1.1
setuptools                    40.8.0
six                           1.12.0
snowballstemmer               2.0.0
Sphinx                        2.2.0
sphinxcontrib-applehelp       1.0.1
sphinxcontrib-devhelp         1.0.1
sphinxcontrib-htmlhelp        1.0.2
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.2
sphinxcontrib-serializinghtml 1.1.3
toml                          0.10.0
tornado                       6.0.3
traitlets                     4.3.3
typed-ast                     1.4.0
urllib3                       1.25.6
webruntime                    0.5.6
wrapt                         1.11.2
zipp                          0.6.0
WARNING: You are using pip version 19.3; however, version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
(leo-dev-opt-b) PS C:\Users\Viktor\pyve\github\leo-dev-opt-b> leo-m                                                     
--global-docks: False

Leo 6.1-devel
unexpected exception loading session
Traceback (most recent call last):

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 2589, in doPostPluginsInit
    g.app.sessionManager.load_session(c1, aList)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoSessions.py", line 82, in load_session
    g.app.loadManager.loadLocalFile(fn, gui=g.app.gui, old_c=c)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 3302, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 3340, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 3509, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoFileCommands.py", line 700, in openLeoFile
    silent=silent,

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoFileCommands.py", line 557, in getLeoFile
    g.app.checkForOpenFile(c, fileName)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 1478, in checkForOpenFile
    if [x for x in aList if os.path.samefile(x, fn)]:

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 1478, in <listcomp>
    if [x for x in aList if os.path.samefile(x, fn)]:

  File "C:\EE\Python\lib\genericpath.py", line 96, in samefile
    s1 = os.stat(f1)

FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:/users/viktor/pyve/ve4ileo/lib/site-packages/leo/doc/quickstart.leo'

unexpected exception reading empty workbook
Traceback (most recent call last):

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 2602, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 2648, in openEmptyWorkBook
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 3302, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 3340, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 3509, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoFileCommands.py", line 700, in openLeoFile
    silent=silent,

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoFileCommands.py", line 557, in getLeoFile
    g.app.checkForOpenFile(c, fileName)

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 1478, in checkForOpenFile
    if [x for x in aList if os.path.samefile(x, fn)]:

  File "c:\users\viktor\pyve\github\leo-dev-opt-b\devel\leo-editor-devel\leo\core\leoApp.py", line 1478, in <listcomp>
    if [x for x in aList if os.path.samefile(x, fn)]:

  File "C:\EE\Python\lib\genericpath.py", line 96, in samefile
    s1 = os.stat(f1)

FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:/users/viktor/pyve/ve4ileo/lib/site-packages/leo/doc/quickstart.leo'

(leo-dev-opt-b) PS C:\Users\Viktor\pyve\github\leo-dev-opt-b>

**Comment by edreamleo** [comment]
On Tue, Oct 22, 2019 at 3:31 PM ranvik14 <notifications@github.com> wrote:

> @edreamleo <https://github.com/edreamleo> : Here are my notes & logs from
> a second attempt to verify your fix in my environment.
> ...
>
> Please let me know if you need further information from my local
> environment.
>

Clearly, the cause of the crash is a missing file:
> FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad
nicht finden:
'C:/users/viktor/pyve/ve4ileo/lib/site-packages/leo/doc/quickstart.leo'

This is not the structure that Leo typically assumes.

Leo expects that the leo folder resides in a leo-editor folder.

Edward

**Comment by maphew** [comment]
>>'C:/users/viktor/pyve/ve4ileo/lib/site-packages/leo/doc/quickstart.leo'
>
>This is not the structure that Leo typically assumes.
>Leo expects that the leo folder resides in a leo-editor folder.

The only time Leo tries to find that structure is when Viktor's old `HOME/.leo` folder and contents are present. Remove that folder and Leo is happy to start, and create a new one. So there's something in there that's screwy. An obvious suspect is `leo.session`. 

Anyway, Viktor already has a solution: delete HOME/.leo folder (or iterate through removing it's contents until the bad file is found). The only percentage in pursuing this issue now is to build a guard against bad session data for other people. (Leo should still start if session info is missing or corrupt, right?) If that's not a good use of time relative to everything else then this can stay closed.

------
**Information:** `PYTHONHOME/lib/site-packages/leo` is the `leo-editor/leo` folder for a pip-installed Leo that didn't use the `--editable` flag. I've verified on many Windows and Linux machines that this arrangement works, modulo a few specific and clearly identified problems (not being able to locate anything that is expected to be parallel to `leo-editor/leo`). I'll link to them later if wanted.

**Comment by edreamleo** [comment]
On Wed, Oct 23, 2019 at 1:23 AM matt wilkie <notifications@github.com>
wrote:

The only time Leo tries to find that structure is when Viktor's old
> HOME/.leo folder and contents are present. Remove that folder and Leo is
> happy to start, and create a new one. So there's something in there that's
> screwy. An obvious suspect is leo.session.
>
I agree.

> Anyway, Viktor already has a solution: delete HOME/.leo folder (or iterate
> through removing it's contents until the bad file is found). The only
> percentage in pursuing this issue now is to build a guard against bad
> session data for other people. (Leo should still start if session info is
> missing or corrupt, right?)
>
No.  Leo must quit if no files at all are found.  The workbook file is the
fallback. Leo has no good options if the workbook doesn't exist and can't
be created.

All the relevant code is in LM.doPostPluginsInit.  Just now, looking at it
once again, I found a few strange (out of place) lines.  These lead to
further cleanups.

Rev a9b10bc in devel contains the new code. Let me know if they create
problems.

It's a bit late in the release cycle to be making these changes, but better
now than later.

Edward

**Comment by ranvik14** [comment]
Hello Edward, hello Matt,

Am Mi., 23. Okt. 2019 um 12:57 Uhr schrieb Edward K. Ream <
notifications@github.com>:

> On Wed, Oct 23, 2019 at 1:23 AM matt wilkie <notifications@github.com>
> wrote:
>
> > The only time Leo tries to find that structure is when Viktor's old
> > HOME/.leo folder and contents are present. Remove that folder and Leo is
> > happy to start, and create a new one. So there's something in there
> that's
> > screwy. An obvious suspect is leo.session.
>
> I agree.
>
> > Anyway, Viktor already has a solution: delete HOME/.leo folder (or
> iterate
> > through removing it's contents until the bad file is found). The only
> > percentage in pursuing this issue now is to build a guard against bad
> > session data for other people. (Leo should still start if session info is
> > missing or corrupt, right?)
>
> No. Leo must quit if no files at all are found. The workbook file is the
> fallback. Leo has no good options if the workbook doesn't exist and can't
> be created.
>

Based on the updated info I received from the two of you my plan is to
perform the following tests in time for Leo-6.1-b1:


   - Dimension #1: Test Leo-6.0-final vs. Leo-6.1-devel in dedicated PyVEs
   - Dimension #2: Start Leo instance w/ a mentioned **existing** outline
   vs. w/ a mentioned **new** outline vs. **w/o any** mentioned outline


WDYT?

With kind regards,

Viktor

**Comment by edreamleo** [comment]
On Wed, Oct 23, 2019 at 2:24 PM ranvik14 <notifications@github.com> wrote:

Based on the updated info I received from the two of you my plan is to
> perform the following tests in time for Leo-6.1-b1:
>
>
> - Dimension #1: Test Leo-6.0-final vs. Leo-6.1-devel in dedicated PyVEs
> - Dimension #2: Start Leo instance w/ a mentioned **existing** outline
> vs. w/ a mentioned **new** outline vs. **w/o any** mentioned outline
>
>
> WDYT?
>

Further testing in this area is always welcome :-)

Edward
