### ISSUE TITLE
Leo curses does not work out of the box in Windows

### ISSUE THREAD

**Issue by ranvik14** [leo-editor/leo-editor#1424]
Using "leo-c" I get the following traceback (See Log). - The package "windows-curses" should be added to the dependencies, that are automatically resolved, when installing Leo into a Windows environment.

### Log ###

(Leo-6.1-b1) PS C:\Users\Viktor\pyve\Leo-6.1-b1> leo-c                                                                 
--global-docks: False

Traceback (most recent call last):

  File "c:\users\viktor\pyve\leo-6.1-b1\lib\site-packages\leo\core\leoApp.py", line 1015, in createCursesGui
    import curses

  File "C:\Users\Viktor\EE\Python\Python37\lib\curses\__init__.py", line 13, in <module>
    from _curses import *

ModuleNotFoundError: No module named '_curses'

can not import _curses.
Windows: pip install windows-curses
(Leo-6.1-b1) PS C:\Users\Viktor\pyve\Leo-6.1-b1>

**Comment by ranvik14** [comment]
@edreamleo : Agreed - but - @mhw-at-yg asked me to open an issue for it, so that he would not forget fixing it.

**Comment by ranvik14** [comment]
@maphew : I can confirm that the script 'leo-c' is now working - and - properly starts Leo in/ with the Curses UI in Windows 10. - Thanks a lot!
