### ISSUE TITLE
Can not start Leo: AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1464]
update 97be7a3fd..016867f5a

Traceback (most recent call last):

  File "/Users/swot/app/leo-editor/leo/core/leoApp.py", line 2603, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()

  File "/Users/swot/app/leo-editor/leo/core/leoApp.py", line 2646, in openEmptyWorkBook
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)

  File "/Users/swot/app/leo-editor/leo/core/leoApp.py", line 3295, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)

  File "/Users/swot/app/leo-editor/leo/core/leoApp.py", line 3333, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)

  File "/Users/swot/app/leo-editor/leo/core/leoApp.py", line 3502, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)

  File "/Users/swot/app/leo-editor/leo/core/leoFileCommands.py", line 699, in openLeoFile
    silent=silent,

  File "/Users/swot/app/leo-editor/leo/core/leoFileCommands.py", line 575, in getLeoFile
    recoveryNode = fc.readExternalFiles(fileName)

  File "/Users/swot/app/leo-editor/leo/core/leoFileCommands.py", line 659, in readExternalFiles
    c.atFileCommands.readAll(c.rootPosition(), force=False)

  File "/Users/swot/app/leo-editor/leo/core/leoAtFile.py", line 476, in readAll
    at.readFileAtPosition(force, p)

  File "/Users/swot/app/leo-editor/leo/core/leoAtFile.py", line 530, in readFileAtPosition
    at.read(p, force=force)

  File "/Users/swot/app/leo-editor/leo/core/leoAtFile.py", line 360, in read
    FastAtRead(c, gnx2vnode).read_into_root(contents, fileName, root)

  File "/Users/swot/app/leo-editor/leo/core/leoAtFile.py", line 3668, in read_into_root
    contents = contents.replace('\r','')

AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by wangzhaohe** [comment]
git reset --hard 1667e84.   is ok

git reset --hard c9c766e.  AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by wangzhaohe** [comment]
I seems that there is a @file learn_mysql.md in workbook.leo, but now the file is deleted.

can not open /Users/swot/.leo/learn_mysql.md
read only: /Users/swot/.Leo/learn_mysql.md

Traceback (most recent call last):

  File "/Users/swot/app/leo-editor/leo/core/leoCommands.py", line 2278, in executeAnyCommand
    return command(event)

  File "/Users/swot/app/leo-editor/leo/core/leoGlobals.py", line 238, in commander_command_wrapper
    method(event=event)

  File "/Users/swot/app/leo-editor/leo/commands/commanderFileCommands.py", line 259, in open_outline
    open_completer(c, closeFlag, fileName)

  File "/Users/swot/app/leo-editor/leo/commands/commanderFileCommands.py", line 204, in open_completer
    c2 = g.openWithFileName(fileName, old_c=c)

  File "/Users/swot/app/leo-editor/leo/core/leoGlobals.py", line 3906, in openWithFileName
    return g.app.loadManager.loadLocalFile(fileName, gui, old_c)

  File "/Users/swot/app/leo-editor/leo/core/leoApp.py", line 3295, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)

  File "/Users/swot/app/leo-editor/leo/core/leoApp.py", line 3333, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)

  File "/Users/swot/app/leo-editor/leo/core/leoApp.py", line 3502, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)

  File "/Users/swot/app/leo-editor/leo/core/leoFileCommands.py", line 699, in openLeoFile
    silent=silent,

  File "/Users/swot/app/leo-editor/leo/core/leoFileCommands.py", line 575, in getLeoFile
    recoveryNode = fc.readExternalFiles(fileName)

  File "/Users/swot/app/leo-editor/leo/core/leoFileCommands.py", line 659, in readExternalFiles
    c.atFileCommands.readAll(c.rootPosition(), force=False)

  File "/Users/swot/app/leo-editor/leo/core/leoAtFile.py", line 476, in readAll
    at.readFileAtPosition(force, p)

  File "/Users/swot/app/leo-editor/leo/core/leoAtFile.py", line 530, in readFileAtPosition
    at.read(p, force=force)

  File "/Users/swot/app/leo-editor/leo/core/leoAtFile.py", line 360, in read
    FastAtRead(c, gnx2vnode).read_into_root(contents, fileName, root)

  File "/Users/swot/app/leo-editor/leo/core/leoAtFile.py", line 3668, in read_into_root
    contents = contents.replace('\r','')

**AttributeError: 'NoneType' object has no attribute 'replace'**

wrote recent file: /Users/swot/.leo/.leoRecentFiles.txt
wrote /Users/swot/.leo/leo.session

**Comment by wangzhaohe** [comment]
After run: touch ~/.Leo/learn_mysql.md

python launchLeo.py runs well now.

**Comment by edreamleo** [comment]
I am going to close this issue in favor of #1466, which gives more details.
