### ISSUE TITLE
Rename @file, remove original external file and Leo can no longer save

### ISSUE THREAD

**Issue by btheado** [leo-editor/leo-editor#1469]
Here is a failing pytest to illustrate the issue:

```python
@pytest.fixture(scope="session")
def bridge():
    return leoBridge.controller(gui='nullGui',
        loadPlugins=False, readSettings=False,
        silent=False, verbose=False)

@pytest.fixture
def tree_F1(bridge, tmpdir):
    """
        Simple one node tree with an @file matching name of the node
    """
    c = bridge.openLeoFile(str(tmpdir.join("tree_F1.leo")))
    p = c.rootPosition()
    p.h = "@file 1"
    p.b = "b_1"
    return c

def test_save_after_external_file_rename(bridge, tree_F1, tmpdir):
    # Create a new outline with @file node and save it
    c = tree_F1
    c.save()

    # Rename the @file node and save
    p1 = c.rootPosition()
    p1.h = "@file 1_renamed"
    c.save()

    # Remove the original "@file 1" from the disk
    tmpdir.join("1").remove()

    # Change the @file contents, save and reopen the outline
    p1.b = "b_1_changed"
    c.save()
    c.close()
    c = bridge.openLeoFile(c.fileName())
    p1 = c.rootPosition()
    assert p1.b == "b_1_changed"
```

This exception is displayed:

```
exception writing: /tmp/pytest-of-btheado/pytest-85/test_save_after_external_file_0/1_renamed
Traceback (most recent call last):

  File "/home/btheado/src/leo-editor/leo/core/leoAtFile.py", line 1323, in write
    if not fileName or not at.precheck(fileName, root):

  File "/home/btheado/src/leo-editor/leo/core/leoAtFile.py", line 2524, in precheck
    if not at.shouldPromptForDangerousWrite(fileName, root):

  File "/home/btheado/src/leo-editor/leo/core/leoAtFile.py", line 3085, in shouldPromptForDangerousWrite
    if os.path.samefile(k, fn) and p.h in d.get(k, set()):

  File "/usr/lib/python3.7/genericpath.py", line 100, in samefile
    s1 = os.stat(f1)

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-btheado/pytest-85/test_save_after_external_file_0/1'
```

**Comment by edreamleo** [comment]
@btheado Thanks for the unit testing code.

Fixed at rev ee55d6. Unit testing complete in devel at rev 336e5e.

**Comment by btheado** [comment]
Confirmed it looks fixed to me too. Thanks.
