### ISSUE TITLE
Traceback import nbformat (5.0.3)

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1476]
After upgrading nbformat package https://github.com/jupyter/nbformat to 5.0.3 I get this traceback:

Leo 6.2-b1-devel, devel branch, build b51bcaa8b5
2020-01-05 19:47:27 -0500
Python 3.8.1, PyQt version 5.14.0
Windows 10 AMD64 (build 10.0.18362) SP0
can not import leo.plugins.importers.ipynb
can not import leo.plugins.importers.ipynb
current dir: N:/git/leo-editor
load dir: N:/git/leo-editor/leo/core
global config dir: N:/git/leo-editor/leo/config
home dir: C:/Users/lewis
reading settings in N:/git/leo-editor/leo/config/leoSettings.leo
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 515, in loadOnePluginHelper
    __import__(moduleName)

  File "N:\git\leo-editor\leo\plugins\viewrendered.py", line 244, in <module>
    import nbformat

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\nbformat\__init__.py", line 32, in <module>
    from .validator import validate, ValidationError

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\nbformat\validator.py", line 12, in <module>
    from jsonschema import ValidationError

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\jsonschema\__init__.py", line 34, in <module>
    __version__ = metadata.version("jsonschema")

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 493, in version
    return distribution(distribution_name).version

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 466, in distribution
    return Distribution.from_name(distribution_name)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 172, in from_name
    dist = next(dists, None)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 407, in <genexpr>
    cls._search_path(path, pattern)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 433, in _search_path
    if not root.is_dir():

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1400, in is_dir
    return S_ISDIR(self.stat().st_mode)

  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1191, in stat
    return self._accessor.stat(self)

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'N:\\git\\leo-editor\\ N:\\git\\leo-editor\\leo'

**Comment by edreamleo** [comment]
I am going to close this. Surely this is a nbformat issue.
