### ISSUE TITLE
leo_cloud plugin errors

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1483]
Just started getting these errors a few weeks ago, don't recall in which Leo version they started. Using the leo_cloud plugin, I get these error messages on reading from cloud:

`Reading from cloud...
Read RGK_Other
Traceback (most recent call last):
  File "...\leo\leo\plugins\qt_idle_time.py", line 111, in call_handler
self.handler(self)
  File "...\leo\leo\plugins\leo_cloud.py", line 334, in bg_post_process
self.load_clouds(from_background=from_background)
  File "...\leo\leo\plugins\leo_cloud.py", line 472, in load_clouds
self.read_current(p=self.c.vnode2position(lc_v))
  File "...\leo\leo\plugins\leo_cloud.py", line 521, in read_current
self.c.setChanged(changedFlag=True)
TypeError: setChanged() got an unexpected keyword argument 'changedFlag'`

Environment:

`Leo 6.2-b1-devel, devel branch, build 5f57d8bde7
2020-01-29 08:47:39 -0600
Python 3.7.3, PyQt version 5.9.6
Windows 10 AMD64 (build 10.0.18362) SP0`

**Comment by edreamleo** [comment]
Fixed at a187a78.
