### ISSUE TITLE
viewrendered3. TypeError: setHtml(self, str): too many arguments

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1543]
Testing the viewrendered3 plugin. Alt+0 launches a floating blank vr3 window, and gives the following error:

Leo Log Window
Leo 6.3-devel, devel branch, build d8e3e722da
2020-03-20 07:43:09 -0500
Python 3.8.2, PyQt version 5.14.0
Windows 10 AMD64 (build 10.0.18362) SP0
[snip]
hook failed: idle, <bound method ViewRenderedController3.update of <leo.plugins.viewrendered3.ViewRenderedController3 object at 0x0000021C47048670>>, <no module>
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 322, in callTagHandler
result = handler(tag, keywords)

  File "N:\git\leo-editor\leo\plugins\viewrendered3.py", line 1402, in update
f(_tree, keywords)

  File "N:\git\leo-editor\leo\plugins\viewrendered3.py", line 2089, in update_rst
self.set_html(h, w)

  File "N:\git\leo-editor\leo\plugins\viewrendered3.py", line 1286, in set_html
w.setHtml(s, url_base)

TypeError: setHtml(self, str): too many arguments

**Comment by edreamleo** [comment]
Fixed in 6.2 and devel. I did a bit more testing, but there are no guarantees.
