### ISSUE TITLE
Remove unexpected calls in redraw logic

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1548]
See [this post](https://groups.google.com/d/msg/leo-editor/KhlPSiYxyDc/YsDHhxsNAgAJ). 

g.toUnicodeFileEncoding was called 2504395 times; os.path.normpath was called 1128328 times.

**Comment by vitalije** [comment]
It is already done in the f71fc76c45

The drawing code is already almost twice as fast as it used to be before f71fc76c45.

However, I would like to try to clean a bit more code in the leoTree and qt_tree. There are some unused methods, attributes,...

**Comment by edreamleo** [comment]
@vitalije Thanks for this. Please close when complete.

**Comment by LewisNeal** [comment]
Hi I'm running Leo build 30f75363f3
Python 3.8.2, PyQt version 5.14.0
Windows 10 AMD64 (build 10.0.18362) SP0

After selecting text and deleting I get these messages in log pane:

Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 299, in new_cmd_wrapper
func(self, event=event)

  File "N:\git\leo-editor\leo\commands\editCommands.py", line 1291, in backwardDeleteCharacter
self.endCommand(changed=changed, setLabel=False)

  File "N:\git\leo-editor\leo\commands\baseCommands.py", line 50, in endCommand
c.frame.body.onBodyChanged(undoType=b.undoType,

  File "N:\git\leo-editor\leo\core\leoFrame.py", line 641, in onBodyChanged
c.redraw_after_icons_changed()

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 2972, in redraw_after_icons_changed
c.frame.tree.redraw_after_icons_changed()

  File "N:\git\leo-editor\leo\plugins\qt_tree.py", line 588, in redraw_after_icons_changed
self.updateVisibleIcons(p)

  File "N:\git\leo-editor\leo\plugins\qt_tree.py", line 1027, in updateVisibleIcons
self.updateIcon(p, force=True)

  File "N:\git\leo-editor\leo\plugins\qt_tree.py", line 1018, in updateIcon
icon = self.getIcon(p) # sets p.v.iconVal

  File "N:\git\leo-editor\leo\plugins\qt_tree.py", line 944, in getIcon
self.getCompositeImage(p, p.v.computeIcon())

AttributeError: 'LeoQtTree' object has no attribute 'getCompositeImage'
[end]

**Comment by vitalije** [comment]
Sorry, about that it was just a typo. Fix is on 0c9b5a5ca794dedd3dc05cb52b40a01d35baeb67

**Comment by LewisNeal** [comment]
Thanks, all fixed
