### ISSUE TITLE
crash Leo 6.3-devel, devel branch, build 30f75363f3

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1549]
1. Leo-editor display follow Traceback when input in body panel.
2. Leo-editor crash when input in outline node.

Leo Log Window
Leo 6.3-devel, devel branch, build 30f75363f3
2020-03-29 21:45:08 +0200
Python 3.7.3, PyQt version 5.12.3
darwin

***

Traceback (most recent call last):

  File "/Users/swot/app/leo-editor/leo/core/leoCommands.py", line 2286, in executeAnyCommand
    return command(event)

  File "/Users/swot/app/leo-editor/leo/core/leoGlobals.py", line 245, in commander_command_wrapper
    method(event=event)

  File "/Users/swot/app/leo-editor/leo/commands/commanderFileCommands.py", line 365, in save
    c.fileCommands.save(c.mFileName)

  File "/Users/swot/app/leo-editor/leo/core/leoFileCommands.py", line 1068, in save
    c.redraw_after_icons_changed()

  File "/Users/swot/app/leo-editor/leo/core/leoCommands.py", line 2972, in redraw_after_icons_changed
    c.frame.tree.redraw_after_icons_changed()

  File "/Users/swot/app/leo-editor/leo/plugins/qt_tree.py", line 588, in redraw_after_icons_changed
    self.updateVisibleIcons(p)

  File "/Users/swot/app/leo-editor/leo/plugins/qt_tree.py", line 1027, in updateVisibleIcons
    self.updateIcon(p, force=True)

  File "/Users/swot/app/leo-editor/leo/plugins/qt_tree.py", line 1018, in updateIcon
    icon = self.getIcon(p)  # sets p.v.iconVal

  File "/Users/swot/app/leo-editor/leo/plugins/qt_tree.py", line 944, in getIcon
    self.getCompositeImage(p, p.v.computeIcon())

AttributeError: 'LeoQtTree' object has no attribute 'getCompositeImage'

**Comment by wangzhaohe** [comment]
The problem is in 4b457edee6c0d67207c9d44f5e4184b298fe558b

**Comment by technatica** [comment]
Same here:
Leo 6.3-devel, devel branch, build 4b457edee6
2020-03-29 16:56:25 +0200
Python 3.7.4, PyQt version 5.9.6
linux

**Comment by LewisNeal** [comment]
Further info:
Open multiple leo files, edit one then close and save the modified file.
All other Tabs also close and Leo closes completely. The other files should remain open.

**Comment by vitalije** [comment]
Fixed at 0c9b5a5ca794dedd3dc05cb52b40a01d35baeb67
Sorry about that. It was just a typo. I missed it because I have settings tree-declutter = True. From now on I will have to test it with both True and False,
