### ISSUE TITLE
Leo IPython error on new leo file

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#155]
When starting Leo in ipython mode if the first thing I do is create a new leofile (Ctrl+N) then I get the following output:

```
C:\MyPrograms\leo-editor>python launchLeo.py --ipython
leoID=jlunz (in C:\Users\8748\.leo)
reading settings in C:\MyPrograms\leo-editor\leo\config\leoSettings.leo
reading settings in C:\Users\8748\.leo\myLeoSettings.leo
reading settings in C:\Users\8748\.leo\workbook.leo

** isPython3: False
Leo 5.0-final, build 20150305163031, Thu Mar  5 16:30:31 CST 2015
Not running from a git repo
Python 2.7.8, PyQt version 4.8.6
Windows 7 AMD64 (build 6.1.7601) SP1
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-17524.json
Traceback (most recent call last):

  File "C:\MyPrograms\leo-editor\leo\core\leoPlugins.py", line 357, in callTagHandler
    result = handler(tag,keywords)

  File "C:\MyPrograms\leo-editor\leo\plugins\todo.py", line 99, in onCreate
    todoController(c)

  File "C:\MyPrograms\leo-editor\leo\plugins\todo.py", line 400, in __init__
    self.ui = todoQtUI(self)

  File "C:\MyPrograms\leo-editor\leo\plugins\todo.py", line 130, in __init__
    form_class, base_class = uic.loadUiType(uiPath)

  File "C:\Anaconda\lib\site-packages\PyQt4\uic\__init__.py", line 202, in loadUiType
    from PyQt4 import QtGui

  File "C:\Anaconda\lib\site-packages\IPython\external\qt_loaders.py", line 47, in load_module
    """ % (fullname, loaded_api()))

ImportError:
    Importing PyQt4 disabled by IPython, which has
    already imported an Incompatible QT Binding: pyqtv1
```

This happens every time I create a new leofile

**Comment by JohnLunzer** [comment]
My discovery came from doing some experiments with a stand alone ipython qt console. I believe these issues are coming from using the Qt API v1 versus the v2 ( think it should always be using v2). 

If you: 
```
import PyQt4

%gui qt

import PyQt4

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-0c3b8c686717> in <module>()
----> 1 import PyQt4

C:\Anaconda\lib\site-packages\IPython\external\qt_loaders.pyc in load_module(self, fullname)
     45     Importing %s disabled by IPython, which has
     46     already imported an Incompatible QT Binding: %s
---> 47     """ % (fullname, loaded_api()))
     48 
     49 ID = ImportDenier()

ImportError: 
    Importing PyQt4 disabled by IPython, which has
    already imported an Incompatible QT Binding: pyqtv1
````

The second import will fail. This is the same error that Leo reports.

I found a lead on, http://cyrille.rossant.net/making-pyqt4-pyside-and-ipython-work-together/ which contains the following code snippit:
```
import sip
try:
    sip.setapi('QDate', 2)
    sip.setapi('QDateTime', 2)
    sip.setapi('QString', 2)
    sip.setapi('QtextStream', 2)
    sip.setapi('Qtime', 2)
    sip.setapi('QUrl', 2)
    sip.setapi('QVariant', 2)
except ValueError, e:
    raise RuntimeError('Could not set API version (%s): did you import PyQt4 directly?' % e)
```

Now if in the stand alone if I run: 
```
import PyQt4

import sip
try:
    sip.setapi('QDate', 2)
    sip.setapi('QDateTime', 2)
    sip.setapi('QString', 2)
    sip.setapi('QtextStream', 2)
    sip.setapi('Qtime', 2)
    sip.setapi('QUrl', 2)
    sip.setapi('QVariant', 2)
except ValueError, e:
    raise RuntimeError('Could not set API version (%s): did you import PyQt4 directly?' % e)

%gui qt

import PyQt4
```

The second import doesn't fail. My uncertainty is I'm not sure where you would inject this code to ensure the v2 API is loaded. I'm also not sure what the ipython qtconsole "%gui qt" magic does.

**Comment by edreamleo** [comment]
Thanks for this research.  I'll look into it asap.  I'd like to fix this for b1.

**Comment by JohnLunzer** [comment]
I found a resolution. Updating Ipython to 3.0.0. Now when you create a new Leo document there is no errors. 

This does not bode well for those stuck with older Ipython installations but I'm guessing if you're using Leo you're probably not stuck with an old version of Ipython.

I will let you close this, as I'm not sure if this is a "good enough" resolution.

**Comment by edreamleo** [comment]
I'm not quite sure what to do with this. Leo's --ipython options works with IPython 2.7 on both Windows and Ubuntu.  So perhaps this is more of an installation issue.

I think I'll close this.  There is nothing I plan to do, and the closed item will still be available for reference.
