### ISSUE TITLE
Settings -> Open a Theme File gives a "file not found" error on Arch Linux

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#1621]
https://github.com/leo-editor/leo-editor/blob/49c5e4fa3cd617524f167e2e114f89d76549bbda/leo/commands/commanderFileCommands.py#L1025

Changing this line to:

    g.subprocess.Popen(command, shell=True) 

Fixes it on my system.

**Comment by gatesphere** [comment]
Log from my system, running branch "master", before the fix:

import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): '<redacted>'
Leo 6.2.1 final, master branch, build 49c5e4fa3c
2020-03-30 08:39:10 -0500

(python:2519): Gtk-WARNING **: 22:26:32.516: Failed to measure available space: The specified location is not supported

(python:2519): Gtk-WARNING **: 22:26:32.516: Failed to measure available space: The specified location is not supported
Traceback (most recent call last):

  File "/home/blah/src/leo-editor/leo/core/leoCommands.py", line 2286, in executeAnyCommand
    return command(event)

  File "/home/blah/src/leo-editor/leo/core/leoGlobals.py", line 245, in commander_command_wrapper
    method(event=event)

  File "/home/blah/src/leo-editor/leo/commands/commanderFileCommands.py", line 1025, in open_theme_file
    g.subprocess.Popen(command)

  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python /home/blah/src/leo-editor/leo/core/runLeo.py "/home/blah/src/leo-editor/leo/themes/LeoBlackSolarized.leo"'

**Comment by XCaminhante** [comment]
I had the same problem in Debian

**Comment by edreamleo** [comment]
The fix to #1564 should also have fixed this issue.  Please reopen if necessary.
