### ISSUE TITLE
AttributeError: 'JEditColorizer' object has no attribute 'findFirstValidAtLanguageDirective'

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1704]
run vr3, errors displayed

happend after git pull: d9367016487a9304a4f35f8f848651347f127683

Leo Log Window
Leo 6.3-devel, devel branch, build e8319a6290
2020-10-10 14:25:04 -0500
Python 3.7.3, PyQt version 5.12.1
darwin
***
Traceback (most recent call last):

  File "/Users/swot/app/leo-editor/leo/core/leoPlugins.py", line 322, in callTagHandler
    result = handler(tag, keywords)

  File "/Users/swot/app/leo-editor/leo/plugins/viewrendered3.py", line 1529, in update
    _kind = pc.get_kind(p) or self.default_kind

  File "/Users/swot/app/leo-editor/leo/plugins/viewrendered3.py", line 2974, in get_kind
    language = self.get_language(p1)

  File "/Users/swot/app/leo-editor/leo/plugins/viewrendered3.py", line 3000, in get_language
    return colorizer.findFirstValidAtLanguageDirective(p.copy())

AttributeError: 'JEditColorizer' object has no attribute 'findFirstValidAtLanguageDirective'

**Comment by edreamleo** [comment]
Thanks for this report. Rev cbdad18f9 in devel fixes this bug.
