### ISSUE TITLE
act-on-node on @jinja nodes

### ISSUE THREAD

**Issue by sprajagopal** [leo-editor/leo-editor#1735]
First of all, amazing project. I love the concepts and I really wish to use it.
After much installation difficulties, I managed to run leo. I have heard so much about the templating the capabilities of leo so I wanted to understand how to use a single template node and use it in multiple places in the file.
I know that jinja has this capability and a quick search showed that leo has a jinja plugin.
I couldn't actually use the plugin. From what I saw in the source code I thought this should work:
1. A `@jinja` node: `@jinja <path-to-template-file>`
2. Within this node, I created child nodes with the names of the template files' variables.
4. I also made sure that the template file does exist.
4. Made an `@enabled-plugins` node with the following contents:
```
jinjarender.py
valuespace.py
```
3. After that I tried `act-on-node` on the `@jinja` node and I got this error:
```
Traceback (most recent call last):

  File "/home/p/leo/leo/leo/lib/python3.6/site-packages/leo/core/leoGlobals.py", line 296, in new_cmd_wrapper
    func(self, event=event)

  File "/home/p/leo/leo/leo/lib/python3.6/site-packages/leo/commands/controlCommands.py", line 126, in actOnNode
    g.act_on_node(self.c, self.c.p, event)

  File "/home/p/leo/leo/leo/lib/python3.6/site-packages/leo/core/leoPlugins.py", line 66, in __call__
    raise TryNext

leo.core.leoPlugins.TryNext
```

So it didn't reach jinja plugin at all. There's an error at the `leoPlugins.py` stage itself. 
I'd love to add documentation to the jinja plugin. But I really need more info on how to make this work.

**Comment by sprajagopal** [comment]
So, I restarted leo and now I can do `act-on-node` without errors. I get a message saying:
```
Rendering /home/p/.leo/sample.jinja
```
Is the rendered output supposed to be present in the `@jinja` node?

**Comment by sprajagopal** [comment]
Ended up rewriting `leo/plugins/jinjarender.py` as:
``` python
#@+leo-ver=5-thin
#@+node:ville.20110409151021.5699: * @file ../plugins/jinjarender.py
#@+<< docstring >>
#@+node:ville.20110409151021.5700: ** << docstring >>
''' Render @jinja nodes.

- sudo apt-get install python-jinja2

Create headline like this:

@jinja ~/foo.txt

Select the node and do alt-x act-on-node

Conceptually, acts like @nosent - tree is parsed,
template is expanded and content is written to the file.

Requires "valuespace" plugin. Fetches vars from valuespace.

'''
#@-<< docstring >>

__version__ = '0.1'
#@+<< version history >>
#@+node:ville.20110409151021.5701: ** << version history >>
#@@killcolor
#@+at
#
# 0.1 Ville M. Vainio:
#
#     * First version
#
#@-<< version history >>

#@+<< imports >>
#@+node:ville.20110409151021.5702: ** << imports >>
import leo.core.leoGlobals as g

from pathlib import Path
from leo.core import leoPlugins
    # Uses leoPlugins.TryNext

try:
    from jinja2 import Template
except ImportError:
    Template = None
#@-<< imports >>

#@+others
#@+node:ville.20110409151021.5703: ** init
def init ():
    '''Return True if the plugin has loaded successfully.'''
    print("Calling jinja plugin")
    ok = bool(Template)
    if ok:
        g.plugin_signon(__name__)
        jinja_install()
    return ok
#@+node:ville.20110409151021.5705: ** install & act-on-node
#@+node:ekr.20120525090541.10863: *3* untangle
def untangle(c,p):

    return g.getScript(c,p,
        useSelectedText=False,
        useSentinels=False)

#@+node:ekr.20120525090541.10864: *3* jinja_render
def jinja_render(template, fname, d):
    print(Path(template).read_text())
    tmpl = Template(Path(template).read_text())
    print(tmpl)
    out = tmpl.render(d)
    print("out:", out)
    open(fname,"w").write(out)

#@+node:ekr.20120525090541.10865: *3* jinja_act_on_node
def jinja_act_on_node(c,p, event):
    h = p.h

    #print "try act"
    if not h.startswith('@jinja '):
        raise leoPlugins.TryNext

    template_data = {}
    for child in p.children():
        if child.h == "template":
            template_path = g.os_path_finalize_join(c.getNodePath(p), untangle(c, child).strip())
            print("template_path: ", template_path)
        elif child.h == "variables":
            for template_var_node in child.children():
                template_data[template_var_node.h] = untangle(c, template_var_node).strip()
            print("template_data: ", template_data)

    if not template_path:
        raise leoPlugins.TryNext

    #print "act"
    tail = h[7:].strip()
    pth = c.getNodePath(p)
    fullpath = g.os_path_finalize_join(pth, tail)
    g.es("Rendering "+ fullpath)
    jinja_render(template_path, fullpath, template_data)

#@+node:ekr.20120525090541.10866: *3* jinja_install
def jinja_install():
    g.act_on_node.add(jinja_act_on_node, 50)

#@+node:ekr.20120525090541.10867: *3* class JinjaCl
class JinjaCl:
    #@+others
    #@+node:ekr.20120525090541.10868: *4* __init__
    def __init__(self, c):
        self.c = c
    #@+node:ekr.20120525090541.10869: *4* __call__
    def __call__(self,body):
        """ Render body through jinja

        To be used from @cl nodes
        """
        #print "jinja called on",body
        tmpl = Template(body)
        out = tmpl.render(self.c.vs)
        return out

    #@-others
#@-others
#@-leo
```

The behaviour now is:
1. Create a `@jinja` node with a output filename
2. Create two children for `@jinja` node
3. A `template` child holds the relative path of the template file
4. A `variables` child holds the template variables *as children*. You could have children of this variables node such as **key1** with contents `value1`. In the template body, all *{{ key1 }}* occurrences are replaced with `value1`.
TODO:
Nested key,val pairs for templating.

**Comment by edreamleo** [comment]
On Sun, Nov 15, 2020 at 11:22 AM sprajagopal <notifications@github.com>
wrote:

Hi,

Welcome aboard. It's great when people get Leo. And thanks for your recent
PR.

Edward

**Comment by edreamleo** [comment]
On Sun, Nov 15, 2020 at 9:21 AM sprajagopal <notifications@github.com>
wrote:

> First of all, amazing project. I love the concepts and I really wish to
> use it.
>
Thanks for the kind words :-)

Edward
