### ISSUE TITLE
ekr-qt branch. AttributeError

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1886]
Opening a leo file, CheatSheet-leo in this example:

Leo Log Window
Leo 6.4-devel, ekr-qt branch, build 4d8e79c881
2021-04-10 17:35:12 -0500
Python 3.9.2, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19041) SP0reading settings in N:/git/leo-editor/leo/doc/quickstart.leo

Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 515, in loadOnePluginHelper
__import__(moduleName)

  File "N:\git\leo-editor\leo\plugins\stickynotes.py", line 77, in <module>
QFont = QtCore.QFont

AttributeError: module 'PyQt5.QtCore' has no attribute 'QFont'

read outline in 0.05 seconds
[end]

**Comment by edreamleo** [comment]
Fixed at rev d441f12 in the ekr-qt branch.
