### ISSUE TITLE
ekr-qt branch. AttributeError: 'Shadow' object

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#1891]
Leo build d5a26c0a42 does not start. The splash screen appears and remains.
Python 3.9.2, PyQt version 5.15.2
Windows [10.0.19042.867]

N:\git\leo-editor>launchleo.py

Empty setting name in False
set parent @settings
Leo 6.4-devel, ekr-qt branch, build d5a26c0a42
2021-04-12 10:56:14 -0500
VR3: *** No matplotlib
setHomeDirectory.py g.app.homeDir set to c:\
Can not load session
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoApp.py", line 2402, in doPostPluginsInit
    g.app.sessionManager.load_session(c1, aList)

  File "N:\git\leo-editor\leo\core\leoSessions.py", line 80, in load_session
    g.app.loadManager.loadLocalFile(fn, gui=g.app.gui, old_c=c)

  File "N:\git\leo-editor\leo\core\leoApp.py", line 3089, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)

  File "N:\git\leo-editor\leo\core\leoApp.py", line 3110, in openFileByName
    c = g.app.newCommander(fileName=fn, gui=gui, previousSettings=previousSettings)

  File "N:\git\leo-editor\leo\core\leoApp.py", line 1618, in newCommander
    c = leoCommands.Commands(fileName,

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 77, in __init__
    c.finishCreate()

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 404, in finishCreate
    c.frame.finishCreate()

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 2124, in finishCreate
    self.top = frameFactory.createFrame(leoFrame=self)

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 4530, in createFrame
    dw.construct(master=tabw)

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 203, in construct
    main_splitter, secondary_splitter = self.createMainWindow()

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 259, in createMainWindow
    self.createBodyPane(main_splitter)

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 318, in createBodyPane
    lineWidget = qt_text.LeoLineTextWidget(c, body)

  File "N:\git\leo-editor\leo\plugins\qt_text.py", line 414, in __init__
    self.setFrameStyle(self.StyledPanel | Shadow.Sunken)

AttributeError: 'Shadow' object has no attribute 'Sunken'

Can not create empty workbook
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoApp.py", line 2415, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()

  File "N:\git\leo-editor\leo\core\leoApp.py", line 2458, in openEmptyWorkBook
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)

  File "N:\git\leo-editor\leo\core\leoApp.py", line 3089, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)

  File "N:\git\leo-editor\leo\core\leoApp.py", line 3110, in openFileByName
    c = g.app.newCommander(fileName=fn, gui=gui, previousSettings=previousSettings)

  File "N:\git\leo-editor\leo\core\leoApp.py", line 1618, in newCommander
    c = leoCommands.Commands(fileName,

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 77, in __init__
    c.finishCreate()

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 404, in finishCreate
    c.frame.finishCreate()

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 2124, in finishCreate
    self.top = frameFactory.createFrame(leoFrame=self)

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 4530, in createFrame
    dw.construct(master=tabw)

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 203, in construct
    main_splitter, secondary_splitter = self.createMainWindow()

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 259, in createMainWindow
    self.createBodyPane(main_splitter)

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 318, in createBodyPane
    lineWidget = qt_text.LeoLineTextWidget(c, body)

  File "N:\git\leo-editor\leo\plugins\qt_text.py", line 414, in __init__
    self.setFrameStyle(self.StyledPanel | Shadow.Sunken)

AttributeError: 'Shadow' object has no attribute 'Sunken'
[end]

**Comment by edreamleo** [comment]
I believe this has been fixed in the ekr-qt branch.

**Comment by LewisNeal** [comment]
Yes this has been fixed. Thanks

**Comment by edreamleo** [comment]
@LewisNeal Thanks for the confirmation.
