### ISSUE TITLE
refresh-from-disk on @auto-md and @auto TypeError

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#1930]
Leo Log Window
Leo 6.4-devel, devel branch, build 3af29adae9
2021-05-07 06:16:28 -0500
Python 3.7.3, PyQt version 5.12.1
Darwin

```
Traceback (most recent call last):

  File "/Users/swot/app/leo-editor/leo/core/leoKeys.py", line 2462, in callAltXFunction
    func(event)

  File "/Users/swot/app/leo-editor/leo/core/leoGlobals.py", line 234, in commander_command_wrapper
    method(event=event)

  File "/Users/swot/app/leo-editor/leo/commands/commanderFileCommands.py", line 332, in refreshFromDisk
    p = at.readOneAtAutoNode(fn, p)

TypeError: readOneAtAutoNode() takes 2 positional arguments but 3 were given
```

**Comment by wangzhaohe** [comment]
Tested, run well.  Thanks!
