### ISSUE TITLE
Failed assert in leoExternalFiles.py

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1959]
Tom P reports this crash during shutdown:
```
wrote recent file: C:/Users/tom/.leo/.leoRecentFiles.txt
Traceback (most recent call last):

  File "c:\tom\git\leo-editor\leo\core\leoApp.py", line 62, in on_idle
    callback()

  File "c:\tom\git\leo-editor\leo\core\leoExternalFiles.py", line 150, in on_idle
    assert len(self.unchecked_files) < n

AssertionError

removing callback: <bound method ExternalFilesController.on_idle of <leo.core.leoExternalFiles.ExternalFilesController object at 0x000001CA18A42A90>>
```
~~~

**Comment by edreamleo** [comment]
The fix was straightforward.
