### ISSUE TITLE
traceback using graphcanvas.py

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#196]
Loading a leo file with some graph nodes, I get this traceback when graphcanvas.py is active. It occurred with recent build 73c2943c8b11.
All the output is to console. There are no tracebacks in the leo log.
I have disabled all plugins except backlink and graphcanvas.

** isPython3: True
Leo 5.1-final, build 20150613073508, Sat Jun 13 07:35:08 CDT 2015
Git repo info: branch = master, commit = 73c2943c8b11
Python 3.4.3, PyQt version 5.4.2
Windows 7 AMD64 (build 6.1.7601) SP1
reading settings in N:\leo\DServe_Eff_Filters.leo
Traceback (most recent call last):
  File "n:\git\leo-editor\leo\plugins\qt_frame.py", line 3301, in qt_add_command
_callback
    return command()
  File "n:\git\leo-editor\leo\core\leoCommands.py", line 5691, in add_commandCal
lback
    val = command()
  File "n:\git\leo-editor\leo\core\leoApp.py", line 3584, in recentFilesCallback

    c.openRecentFile(name)
  File "n:\git\leo-editor\leo\core\leoCommands.py", line 1154, in openRecentFile

    c2 = g.openWithFileName(fn, old_c=c)
  File "n:\git\leo-editor\leo\core\leoGlobals.py", line 2693, in openWithFileNam
e
    return g.app.loadManager.loadLocalFile(fileName, gui, old_c)
  File "n:\git\leo-editor\leo\core\leoApp.py", line 3247, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "n:\git\leo-editor\leo\core\leoApp.py", line 3284, in openFileByName
    ok = lm.readOpenedLeoFile(c, gui, fn, readAtFileNodesFlag, theFile)
  File "n:\git\leo-editor\leo\core\leoApp.py", line 3454, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)
  File "n:\git\leo-editor\leo\core\leoFileCommands.py", line 821, in openLeoFile

    silent=silent,
  File "n:\git\leo-editor\leo\core\leoFileCommands.py", line 677, in getLeoFile
    c.redraw()
  File "n:\git\leo-editor\leo\core\leoCommands.py", line 5771, in redraw
    p2 = c.frame.tree.redraw(p)
  File "n:\git\leo-editor\leo\plugins\qt_tree.py", line 173, in full_redraw
    self.drawTopTree(p)
  File "n:\git\leo-editor\leo\plugins\qt_tree.py", line 251, in drawTopTree
    self.drawTree(p)
  File "n:\git\leo-editor\leo\plugins\qt_tree.py", line 264, in drawTree
    self.drawChildren(p, parent_item=item)
  File "n:\git\leo-editor\leo\plugins\qt_tree.py", line 202, in drawChildren
    self.drawTree(child, parent_item)
  File "n:\git\leo-editor\leo\plugins\qt_tree.py", line 262, in drawTree
    item = self.drawNode(p, parent_item)
  File "n:\git\leo-editor\leo\plugins\qt_tree.py", line 220, in drawNode
    item = self.createTreeItem(p, parent_item)
  File "n:\git\leo-editor\leo\plugins\qt_tree.py", line 939, in createTreeItem
    g.visit_tree_item(self.c, p, item)
  File "n:\git\leo-editor\leo\core\leoPlugins.py", line 52, in __call__
    ret = cmd(*args, **kw)
  File "n:\git\leo-editor\leo\plugins\graphcanvas.py", line 76, in colorize_head
lines_visitor
    item.setBackgroundColor(0, QtGui.QColor(p.v.u['_bklnk']['color']))
AttributeError: 'QTreeWidgetItem' object has no attribute 'setBackgroundColor'

Regards
Lewis

**Comment by LewisNeal** [comment]
Thankyou for fixing this. 
Lewis

**Comment by edreamleo** [comment]
On Tue, Jul 7, 2015 at 8:50 AM, LewisNeal <notifications@github.com> wrote:

> Thankyou for fixing this.
>
​You're welcome.

EKR
