### ISSUE TITLE
quicksearch plugin crash

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2012]
Running build 9bfdf909fb using quicksearch plugin. Typing characters into the Nav pane - once the 3rd character is entered Leo hard crashes.

Leo Log Window
Leo 6.4-devel, devel branch, build 9bfdf909fb
2021-06-27 06:01:45 -0500
Python 3.9.5, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19042) SP0
[snip]
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\threadutil.py", line 287, in run
    self.do_work(inp)
  File "N:\git\leo-editor\leo\plugins\threadutil.py", line 266, in do_work
    self.output = self.worker(inp)
  File "N:\git\leo-editor\leo\plugins\quicksearch.py", line 384, in searcher
    res =  self.bgSearch(exp)
  File "N:\git\leo-editor\leo\plugins\quicksearch.py", line 644, in bgSearch
    hm = self.find_h(hpat, hNodes, flags)
  File "N:\git\leo-editor\leo\plugins\quicksearch.py", line 664, in find_h
    pc.mo = m
AttributeError: 'Position' object has no attribute 'mo'

**Comment by edreamleo** [comment]
@LewisNeal As Thomas says, this may be due to slots.

**Comment by edreamleo** [comment]
I just fixed #2013, so threadutil.py won't ever crash (I think). Now, you will see the following, modulo the path to Leo's plugin folder.
```
Traceback (most recent call last):
  File "c:\leo.repo\leo-editor\leo\plugins\threadutil.py", line 299, in do_work
    self.output = self.worker(inp)
  File "c:\leo.repo\leo-editor\leo\plugins\quicksearch.py", line 384, in searcher
    res =  self.bgSearch(exp)
  File "c:\leo.repo\leo-editor\leo\plugins\quicksearch.py", line 644, in bgSearch
    hm = self.find_h(hpat, hNodes, flags)
  File "c:\leo.repo\leo-editor\leo\plugins\quicksearch.py", line 664, in find_h
    pc.mo = m
AttributeError: 'Position' object has no attribute 'mo'

threadutil.py: unexpected exception in NowOrLater.callit

Traceback (most recent call last):
  File "c:\leo.repo\leo-editor\leo\plugins\threadutil.py", line 119, in callit
    self.w(work)
  File "c:\leo.repo\leo-editor\leo\plugins\quicksearch.py", line 403, in throttledDump
    hm,bm = lst[-1]
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by edreamleo** [comment]
Imo, there was never any need to inject a "mo" attribute into positions.

Slots were essential in detecting this "unauthorized" intrusion into Positions.

**Comment by LewisNeal** [comment]
Quicksearch plugin is now working correctly. Thanks

**Comment by edreamleo** [comment]
@LewisNeal Thanks for the confirmation.
