### ISSUE TITLE
Leo exits when showing tooltips at startup

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2127]
```
Uncaught exception in Leo...

Traceback (most recent call last):
  File "c:\leo.repo\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "c:\leo.repo\leo-editor\leo\core\runLeo.py", line 86, in run
    g.app.loadManager.load(fileName, pymacs)
  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 2370, in load
    g.app.gui.runMainLoop()
  File "c:\leo.repo\leo-editor\leo\plugins\qt_gui.py", line 1174, in runMainLoop
    g.app.gui.show_tips()
  File "c:\leo.repo\leo-editor\leo\plugins\qt_gui.py", line 1289, in show_tips
    m = self.DialogWithCheckBox(controller=self, tip=tip)
  File "c:\leo.repo\leo-editor\leo\plugins\qt_gui.py", line 1248, in __init__
    self.setIcon(self.Information)
AttributeError: 'DialogWithCheckBox' object has no attribute 'Information'
```
Hah! A crash in qt_gui.runMainLoop prevents the main loop from starting.  Easily fixed!

**Comment by edreamleo** [comment]
Fixed at rev 5be9a9a.
