### ISSUE TITLE
Crash in  leo_excepthook

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2144]
```
File "c:\Tom\git\leo-editor\leo\core\runLeo.py", line 16, in leo_excepthook
    print('\nUncaught exception in Leo...\n', flush=True)

AttributeError: 'PyInterp' object has no attribute 'flush'
```

**Comment by edreamleo** [comment]
@tbpassin How did this crash happen?  The traceback makes no sense.  Furthermore, the following stand-alone test works as expected

```
import sys
import traceback

def leo_excepthook(typ, val, tb):
    # Like g.es_exception.
    lines = traceback.format_exception(typ, val, tb)
    print('\nUncaught exception in Leo...\n', flush=True)
    for line in lines:
        print(line.rstrip(), flush=True)
        
sys.excepthook = leo_excepthook

print(a)  # Generate an uncaught exception.
```

**Comment by tbpassin** [comment]
I just now stopped and restarted Leo and reproduced the error.  In the Python Console pane, I ran `site.getusersitepackages()` without - oops! - importing _site_ first.  I got the same error message in the Log pane, with the Python Console showing `Uncaught exception in Leo...` . 

Using

```
Leo 6.4b2, master branch, build ee0a3334b4
2021-08-16 04:32:32 -0500
Python 3.9.5, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19043) 
```

The full gory error message in the Log pane (only the first line of which shows my actual error) was

```  File "<input>", line 1, in <module>

NameError: name 'site' is not defined

 During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\Tom\git\leo-editor\leo\plugins\python_terminal.py", line 335, in run_code
    interp.runcode(the_code)

  File "C:\Program Files\Python39\lib\code.py", line 94, in runcode
    self.showtraceback()

  File "C:\Program Files\Python39\lib\code.py", line 148, in showtraceback
    sys.excepthook(ei[0], ei[1], last_tb)

  File "c:\Tom\git\leo-editor\leo\core\runLeo.py", line 16, in leo_excepthook
    print('\nUncaught exception in Leo...\n', flush=True)

AttributeError: 'PyInterp' object has no attribute 'flush'

 During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\Tom\git\leo-editor\leo\plugins\python_terminal.py", line 289, in keyPressEvent
    self.doEnter(event)

  File "c:\Tom\git\leo-editor\leo\plugins\python_terminal.py", line 398, in doEnter
    compile_and_run_lines(exec_lines)

  File "c:\Tom\git\leo-editor\leo\plugins\python_terminal.py", line 329, in compile_and_run_lines
    return run_code(the_code)

  File "c:\Tom\git\leo-editor\leo\plugins\python_terminal.py", line 340, in run_code
    interp.showtraceback()

  File "C:\Program Files\Python39\lib\code.py", line 148, in showtraceback
    sys.excepthook(ei[0], ei[1], last_tb)

  File "c:\Tom\git\leo-editor\leo\core\runLeo.py", line 16, in leo_excepthook
    print('\nUncaught exception in Leo...\n', flush=True)

AttributeError: 'PyInterp' object has no attribute 'flush'
```

**Comment by edreamleo** [comment]
@tbpassin Thanks for this. The crash happens in the infamous python_terminal.py plugin.

This is an interesting puzzle. Clearly, the plugin is messing around :-)

**Comment by tbpassin** [comment]
I confirm that with the same (wrong) code, the Python Console did not crash with this changeset.
