### ISSUE TITLE
Right click context menu on outline tree nodes causes crash

### ISSUE THREAD

**Issue by daveuu** [leo-editor/leo-editor#223]
After a recent ArchLinux system update, Leo immediately exits because of a crash when right clicking on outline tree nodes. The instant the menu should appear, the whole Leo window disappears. I believe the relevant change was pyqt5-common 5.5-2 to 5.5.1-1 as packaged for ArchLinux. Below is version information and the traceback.
````
** isPython3: True
Leo 5.1-final, build 20150416183122, Thu Apr 16 18:31:22 CDT 2015
Not running from a git repo
Python 3.5.0, PyQt version 5.5.1
linux
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/leo/plugins/qt_tree.py", line 514, in onContextMenu
    h(c,p,menu)
  File "/usr/lib/python3.5/site-packages/leo/plugins/quickMove.py", line 468, in popup
    a.connect(a, QtCore.SIGNAL("triggered()"), wrap)
AttributeError: 'QAction' object has no attribute 'connect'
Aborted (core dumped)
````

**Comment by daveuu** [comment]
I just tested the current main branch of this repository and I could not reproduce the problem. Sorry! I should have done that first. This works:
````
** isPython3: True
Leo 5.1-final, build 20151122092056, Sun Nov 22 09:20:56 CST 2015
Git repo info: branch = master, commit = 3d1b58ca463c
Python 3.5.0, PyQt version 5.5.1
linux
````
Keep up the good work! Leo is awesome.
