### ISSUE TITLE
Crash in findMatchingBracket

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2240]
```
Traceback (most recent call last):
  File "C:\leo.repo\leo-editor\leo\unittests\core\test_leoCommands.py", line 241, in test_c_findMatchingBracket
    c.findMatchingBracket(event=None)
  File "C:\leo.repo\leo-editor\leo\commands\commanderEditCommands.py", line 623, in findMatchingBracket
    g.MatchBrackets(c, p, language).run()
  File "C:\leo.repo\leo-editor\leo\core\leoGlobals.py", line 1439, in run
    left, right, ch, index = self.expand_range(s, left, right, max_right)
  File "C:\leo.repo\leo-editor\leo\core\leoGlobals.py", line 1181, in expand_range
    (s[left] not in self.brackets or expand and not expanded)
IndexError: string index out of range
```

**Comment by edreamleo** [comment]
Rev 7e4c205 in devel adds some guards, and improves a unit test.

I was not able to reproduce the crash.
