### ISSUE TITLE
print-plugins-info fails with error messages

### ISSUE THREAD

**Issue by robcrutchfield** [leo-editor/leo-editor#232]
Selecting print-plugins-info from the Plugins menu generates these
  messages:

  exception executing command
  Traceback (most recent call last):
    File "c:\leo.repo\leo-editor\leo\core\leoCommands.py", line 5120, in doCommand
    File "c:\leo.repo\leo-editor\leo\core\leoGlobals.py", line 1335, in wrapper
    File "c:\leo.repo\leo-editor\leo\plugins\qt_frame.py", line 2773, in fullyExpandLogPane
    File "c:\leo.repo\leo-editor\leo\plugins\qt_frame.py", line 2548, in divideLeoSplitter
    File "c:\leo.repo\leo-editor\leo\plugins\qt_frame.py", line 2557, in divideLeoSplitter2
    File "c:\leo.repo\leo-editor\leo\plugins\qt_frame.py", line 2563, in divideAnySplitter
  RuntimeError: wrapped C/C++ object of type NestedSplitter has been deleted

  I'm using Leo 5.1 final, and the version of Python that came with it, 2.7.8; pyQT version 4.8.6
  Windows 8.1

**Comment by edreamleo** [comment]
I can not reproduce this problem on the latest builds. 5.1 final is ancient history now.
