### ISSUE TITLE
OK/Show Next Tip - no attribute 'show_tips_flag'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2389]
At startup clicking OK/Show Next Tip gives error:
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1228, in runMainLoop
g.app.gui.show_tips(c)

  File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1343, in show_tips
self.update_tips_setting()

  File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1356, in update_tips_setting
if c and self.show_tips_flag != c.config.getBool('show-tips', default=False):

AttributeError: 'LeoQtGui' object has no attribute 'show_tips_flag'

_Leo Log Window
Leo 6.6b2-devel, devel branch, build 464d9fbbe9
2022-01-22 08:20:12 -0500
Python 3.10.1, PyQt version 6.2.2
Windows 10 AMD64 (build 10.0.19042) SP0_

**Comment by tbpassin** [comment]
Not seeing that; same change set, but Python 3.9.9 on Windows.

**Comment by edreamleo** [comment]
@LewisNeal Thanks.  I didn't realize you filed a new issue. I have just created #2390, so I'll close this issue.
