### ISSUE TITLE
Bookmarks plugin errors

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#243]
Python 3.4.3, PyQt version 5.4.1
Windows 8 AMD64 (build 6.2.9200)

The following errors in the terminal window when loading .leo files with the bookmarks.py plugin enabled:

Traceback (most recent call last):
  File "D:\Synced\github repos\leo\leo\plugins\bookmarks.py", line 426, in minimumSize
    size += QtCore.QSize(2 * self.margin(), 2 * self.margin())
AttributeError: 'FlowLayout' object has no attribute 'margin'
reading settings in D:\Synced\github repos\leo\leo\config\exampleSettings.leo
Traceback (most recent call last):
  File "D:\Synced\github repos\leo\leo\plugins\bookmarks.py", line 419, in sizeHint
    return self.minimumSize()
  File "D:\Synced\github repos\leo\leo\plugins\bookmarks.py", line 426, in minimumSize
    size += QtCore.QSize(2 * self.margin(), 2 * self.margin())
AttributeError: 'FlowLayout' object has no attribute 'margin'

**Comment by largo84** [comment]
That was fast! Works here, thanks!
