### ISSUE TITLE
Crash in leoAst.py while beautifying viewrendered3.py

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2446]
See PR #2447. The crash arises from this statement at line 854 of viewrendered3.py:
```python
raise ImportError from None
```
Here is the traceback:
```
beautify-files: viewrendered3.py
Traceback (most recent call last):

  File "c:\leo.repo\leo-editor\leo\core\leoKeys.py", line 2490, in callAltXFunction
    func(event)

  File "c:\leo.repo\leo-editor\leo\core\leoBeautify.py", line 76, in orange_files
    changed = leoAst.Orange(settings=settings).beautify_file(filename)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 2686, in beautify_file
    contents, encoding, tokens, tree = tog.init_from_file(filename)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1275, in init_from_file
    list(self.create_links(tokens, tree))

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1254, in create_links
    next(self.visitor(tree))

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1506, in visitor
    yield from method(node)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1688, in do_Module
    yield from self.gen(node.body)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1345, in gen
    yield from self.visitor(z)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1497, in visitor
    yield from self.visitor(z)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1506, in visitor
    yield from method(node)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 2430, in do_Try
    yield from self.gen(node.handlers)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1345, in gen
    yield from self.visitor(z)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1497, in visitor
    yield from self.visitor(z)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1506, in visitor
    yield from method(node)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 2287, in do_ExceptHandler
    yield from self.gen(node.body)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1345, in gen
    yield from self.visitor(z)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1497, in visitor
    yield from self.visitor(z)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1506, in visitor
    yield from method(node)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 2412, in do_Raise
    yield from self.gen(cause)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1345, in gen
    yield from self.visitor(z)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1506, in visitor
    yield from method(node)

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1761, in do_Constant
    yield from self.gen_token('name', repr(node.value))

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1354, in gen_token
    yield from self.visitor(self.sync_token(kind, val))  # type:ignore

  File "c:\leo.repo\leo-editor\leo\core\leoAst.py", line 1391, in sync_token
    raise AssignLinksError(

leo.core.leoAst.AssignLinksError:        file: C:/leo.repo/leo-editor/leo/plugins/viewrendered3.py
   line 854: raise ImportError from None
Looking for: name.'None'
      found: name.'from'
token.index: 307
```

**Comment by tbpassin** [comment]
Yes, just go ahead and change it to, say:

```
except ImportError as e:
    g.es('Viewrendered3: cannot import QT modules')
    raise ImportError from eexcept ImportError as e:
    g.es('Viewrendered3: cannot import QT modules')
    raise ImportError from e
```

This  doesn't crash but also doesn't give you an error message that VR3 didn't start, except for a message that one if it's commands isn't available.  But how could this happen unless some major part of pyqt wasn't there - in that happens, we've got bigger problems anyway?

**Comment by edreamleo** [comment]
@tbpassin The VR3 crash is merely a symptom of a bug in leoAst.py which must be fixed.  I definitely do *not* want to make this bug go away by changing VR3.
