### ISSUE TITLE
iLeo not working

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2462]
Running iLeo the QtConsole does not load. 

>launchleo.py --ipython

Empty setting name in False
set parent @settings
Leo 6.6-rc1-devel, devel branch, build 9cd7803270
2022-03-04 07:45:45 -0600
VR3: *** No nbformat
[snip]

To connect another client to this kernel, use:
    --existing kernel-7480.json
ERROR:tornado.application:Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x00000246B10F49D0>)
Traceback (most recent call last):
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\kernelbase.py", line 416, in advance_eventloop
    eventloop(self)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\eventloops.py", line 137, in loop_qt5
    return loop_qt4(kernel)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\eventloops.py", line 119, in loop_qt4
    _notify_stream_qt(kernel, kernel.shell_stream)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\eventloops.py", line 40, in _notify_stream_qt
    notifier = QtCore.QSocketNotifier(fd, QtCore.QSocketNotifier.Read, kernel.app)
AttributeError: type object 'QSocketNotifier' has no attribute 'Read'

**Comment by tbpassin** [comment]
This seems to be a bug in ipython.  In the last two lines of the traceback, `QtCore.QSocketNotifier.Read` should be `QtCore.QSocketNotifier.Type.Read`

You could try fixing that in _eventloops.py_, and if that works, file a bug with ipython.  Or maybe there's a newer version that has it fixed.

**Comment by LewisNeal** [comment]
I fixed _eventloops.py_ as suggested.  This is the new traceback:

[snip]
File "C:\Users\lewisneal\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\eventloops.py", line 121, in loop_qt4
    _loop_qt(kernel.app)
  File "C:\Users\lewisneal\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\eventloops.py", line 105, in _loop_qt
    app.exec_()
AttributeError: 'QApplication' object has no attribute 'exec_'

**Comment by tbpassin** [comment]
Too bad, that would have been simple.  Well, it doesn't seem to be a Leo problem, so I would suggest that you file a bug with them.

One possibility - if you are using PyQt6, it might still work with PyQt5.  There were some pesky changes with pyqt6, and this code may not have been adjusted for them yet.
