### ISSUE TITLE
Leo crashes at Quit using --gui=console

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2467]
See PR #2468.

Running 6.6-rc1-devel, devel branch, build eeb0789a98
Python 3.10.2, Windows 10 AMD64 (build 10.0.19042) SP0

launchleo.py --gui=console

Highlight the _Quit Leo_ button press enter, Leo crashes with no option to save Y/N
[snip]
Uncaught exception in Leo...
Traceback (most recent call last):
  File "N:\git\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "N:\git\leo-editor\leo\core\runLeo.py", line 90, in run
    g.app.loadManager.load(fileName, pymacs)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2253, in load
    g.app.gui.runMainLoop()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1552, in runMainLoop
    self.curses_app.run()
  File "N:\git\leo-editor\leo\external\npyscreen\apNPSApplication.py", line 44, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "N:\git\leo-editor\leo\external\npyscreen\npyssafewrapper.py", line 47, in wrapper
    wrapper_no_fork(call_function)
  File "N:\git\leo-editor\leo\external\npyscreen\npyssafewrapper.py", line 106, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "N:\git\leo-editor\leo\external\npyscreen\apNPSApplication.py", line 37, in __remove_argument_call_main
    return self.main()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2737, in main
    g.app.gui.run()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1568, in run
    self.top_form.edit()
  File "N:\git\leo-editor\leo\external\npyscreen\fm_form_edit_loop.py", line 110, in edit
    self._widgets__[self.editw].edit()
  File "N:\git\leo-editor\leo\external\npyscreen\wgwidget.py", line 521, in edit
    self._edit_loop()
  File "N:\git\leo-editor\leo\external\npyscreen\wgwidget.py", line 341, in _edit_loop
    self.get_and_use_key_press()
  File "N:\git\leo-editor\leo\external\npyscreen\wgwidget.py", line 574, in get_and_use_key_press
    self.handle_input(ch)
  File "N:\git\leo-editor\leo\external\npyscreen\wgwidget.py", line 108, in handle_input
    f(i)
  File "N:\git\leo-editor\leo\external\npyscreen\wgbutton.py", line 116, in h_toggle
    self.whenPressed()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 710, in whenPressed
    g.app.onQuit()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 1346, in onQuit
    g.app.gui.close_event(QCloseEvent())  # type:ignore
AttributeError: 'LeoCursesGui' object has no attribute 'close_event'

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report. This issue is likely due to recent changes in how Leo handles clicks in the close box of a Leo window.

**Comment by edreamleo** [comment]
@LewisNeal PR #2434 probably contains the changes that broke the console gui plugin.
