### ISSUE TITLE
minimal footprint request and dependency on _tkinter?

### ISSUE THREAD

**Issue by shakfu** [leo-editor/leo-editor#2512]
See PR #2517.

- [x] g.EmergencyDialog should fall back to printing its message if tkinter does not exist.
- [x] general_yes_no_dialog (in leoserver.py) should return 'yes' if tkinter does not exit.

**Original report**

I just tried to `pip install leo` on macOS Catalina using homebrew python 3.9.10 and it broke because of the following:

```python
setting leoID from os.getenv('USER'): 'me'

Uncaught exception in Leo...
Traceback (most recent call last):
  File "$HOME/Downloads/leoenv/bin/leo", line 8, in <module>
    sys.exit(run())
  File "$HOME/Downloads/leoenv/lib/python3.9/site-packages/leo/core/runLeo.py", line 90, in run
    g.app.loadManager.load(fileName, pymacs)
  File "$HOME/Downloads/leoenv/lib/python3.9/site-packages/leo/core/leoApp.py", line 2241, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "$HOME/Downloads/leoenv/lib/python3.9/site-packages/leo/core/leoApp.py", line 2437, in doPrePluginsInit
    lm.initApp(verbose)
  File "$HOME/Downloads/leoenv/lib/python3.9/site-packages/leo/core/leoApp.py", line 2658, in initApp
    g.app.setLeoID(verbose=verbose)
  File "$HOME/Downloads/leoenv/lib/python3.9/site-packages/leo/core/leoApp.py", line 1049, in setLeoID
    self.setIdFromDialog()
  File "$HOME/Downloads/leoenv/lib/python3.9/site-packages/leo/core/leoApp.py", line 1136, in setIdFromDialog
    dialog = g.TkIDDialog()
  File "$HOME/Downloads/leoenv/lib/python3.9/site-packages/leo/core/leoGlobals.py", line 2046, in __init__
    super().__init__(self.title, self.message)
  File "$HOME/Downloads/leoenv/lib/python3.9/site-packages/leo/core/leoGlobals.py", line 489, in __init__
    self.createTopFrame()
  File "$HOME/Downloads/leoenv/lib/python3.9/site-packages/leo/core/leoGlobals.py", line 2058, in createTopFrame
    import tkinter as Tk
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

Given the requirement for pyqt, qt, and all the other requirements (a virtualenv for leo alone is around 542MB) is _tkinter also required?

It would be great to have a minimal footprint for leo if possible if all of the other stuff is not required and one just wants to do some basic literate programming.

**Comment by edreamleo** [comment]
@shakfu Thanks for this report.  I'll remove the dependency on _tkinter if possible.

**Comment by shakfu** [comment]
Thanks Edward!

**Comment by edreamleo** [comment]
PR #2517 completes this issue.

**Comment by shakfu** [comment]
Thanks very much for the rapid fix, Edward!

**Comment by edreamleo** [comment]
@shakfu You're welcome. It's good to (mostly) get rid of the tkinter dependency.
