### ISSUE TITLE
test-all fails during test discovery if _curses has not been installed

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2514]
Félix reports the following, which seems reasonable (expected) when _curses has not been installed.

There are many imports of curses/_curses in npyscreen, so changing the npyscreen code itself seems out of the question.
```
======================================================================
ERROR: leo.external.npyscreen (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: leo.external.npyscreen
Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python37-32\lib\unittest\loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python37-32\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\prog\leo-editor\leo\external\npyscreen\__init__.py", line 8, in <module>
    from .wgwidget                  import TEST_SETTINGS, ExhaustedTestInput, add_test_input_from_iterable, add_test_input_ch
  File "C:\prog\leo-editor\leo\external\npyscreen\wgwidget.py", line 9, in <module>
    import curses
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python37-32\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by edreamleo** [comment]
I am going to mark this issue as "Can'tFix". Devs can install curses, or live with the unit testing error.
