### ISSUE TITLE
show-buttons command. ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2536]
See PR #2547.

The show-buttons command is giving this traceback:

_Leo Log Window
Leo 6.6-rc1-devel, devel branch, build 55a9ae46b0
2022-03-27 09:26:48 -0500
Python 3.10.4, PyQt version 6.2.3
Windows 10 AMD64 (build 10.0.19044) SP0
read outline in 0.19 seconds
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 285, in new_cmd_wrapper
func(self, event=event)

  File "N:\git\leo-editor\leo\core\leoKeys.py", line 2570, in printButtons
p, script = z

ValueError: too many values to unpack (expected 2)_

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report. It's too late to fix for 6.6.
