### ISSUE TITLE
test-all command gives different results when installed with pypi

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2633]
See PR #2662. See [this post](https://groups.google.com/g/leo-editor/c/cOctuPU4HGc/m/UtVpKLF8AwAJ).  There are two problems:

1. [Minor, won't fix] The test-all command does not work when run from the "pip installed" Leo because the leo-editor directory does not exist.  g.run_unit_tests could run tests from python/lib/site-packages/leo instead, but imo this kind of hack is too ugly.  **Workaround**:  run `python -m unittest` from site-packages/leo. This should work provided that the following is fixed:

2. [Serious] Running `python -m unittest` from the site-packages/leo directory shows 7 failures because `pip install leo` does not install the leo/test directory:
   - The execute-script command requires this directory!
   - Several unit tests require leo/test/test.leo.
```console
c:\Python\Python3.10\Lib\site-packages\leo>C:\Python\Python3.10\python.exe -m unittest
...........s...........................................................................s.................................sss....................................................s......FF.................................................................................................................................................................................................................................................................................................E..................F.............................................................................................................................................................................................................................................................................................................................................................................................................................FFF...........Fs
======================================================================
ERROR: test_remove (unittests.core.test_leoAtFile.TestAtFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python\Python3.10\Lib\site-packages\leo\unittests\core\test_leoAtFile.py", line 412, in test_remove
    f = open(path, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Python/Python3.10/lib/site-packages/leo/core/../test/xyzzy'

======================================================================
FAIL: test_lm_openAnyLeoFile (unittests.core.test_leoApp.TestApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python\Python3.10\Lib\site-packages\leo\unittests\core\test_leoApp.py", line 69, in test_lm_openAnyLeoFile
    assert g.os_path_exists(testDir), testDir
AssertionError: C:/Python/Python3.10/lib/site-packages/leo/core/../test

======================================================================
FAIL: test_official_g_app_directories (unittests.core.test_leoApp.TestApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python\Python3.10\Lib\site-packages\leo\unittests\core\test_leoApp.py", line 22, in test_official_g_app_directories
    assert g.os_path_exists(g.os_path_abspath(val)), 'non-existent g.app directory: %s' % ivar
AssertionError: non-existent g.app directory: testDir

======================================================================
FAIL: test_bridge (unittests.core.test_leoBridge.TestBridge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python\Python3.10\Lib\site-packages\leo\unittests\core\test_leoBridge.py", line 31, in test_bridge
    self.assertTrue(os.path.exists(test_dot_leo), msg=test_dot_leo)
AssertionError: False is not true : c:/Python/Python3.10/Lib/site-packages/leo/test/test.leo

======================================================================
FAIL: test_find_commands (unittests.core.test_leoserver.TestLeoServer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python\Python3.10\Lib\site-packages\leo\unittests\core\test_leoserver.py", line 176, in test_find_commands
    assert os.path.exists(test_dot_leo), repr(test_dot_leo)
AssertionError: 'C:/Python/Python3.10/lib/site-packages/leo/test/test.leo'

======================================================================
FAIL: test_most_public_server_methods (unittests.core.test_leoserver.TestLeoServer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python\Python3.10\Lib\site-packages\leo\unittests\core\test_leoserver.py", line 76, in test_most_public_server_methods
    assert os.path.exists(test_dot_leo), repr(test_dot_leo)
AssertionError: 'C:/Python/Python3.10/lib/site-packages/leo/test/test.leo'

======================================================================
FAIL: test_open_and_close (unittests.core.test_leoserver.TestLeoServer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python\Python3.10\Lib\site-packages\leo\unittests\core\test_leoserver.py", line 146, in test_open_and_close
    assert os.path.exists(test_dot_leo), repr(test_dot_leo)
AssertionError: 'C:/Python/Python3.10/lib/site-packages/leo/test/test.leo'

======================================================================
FAIL: test_syntax_of_all_files (unittests.test_syntax.TestSyntax)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python\Python3.10\Lib\site-packages\leo\unittests\test_syntax.py", line 40, in test_syntax_of_all_files
    self.assertTrue(g.os_path_exists(path), msg=path)
AssertionError: False is not true : C:/Python/Python3.10/lib/site-packages/leo/test

----------------------------------------------------------------------
Ran 923 tests in 9.542s

FAILED (failures=7, errors=1, skipped=7)
```

**Comment by edreamleo** [comment]
I am going to close this issue. Please reopen if necessary after Leo 6.6.2 is released.
