### ISSUE TITLE
Unable to run leo 6.6.2 due to possible Tkinter dependency

### ISSUE THREAD

**Issue by shakfu** [leo-editor/leo-editor#2674]
Hi Edward,

I'm on macOS Catalina with homebrew python 3.9.13 (I don't have tkinter installed). I'm unable to run leo (please see below), and I get an error which seems to be due to a residual tkinter dependency: 

```bash

$ virtualenv leonv
created virtual environment CPython3.9.13.final.0-64 in 644ms
  creator CPython3Posix(dest=$HOME/Downloads/leonv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=$HOME/Library/Application Support/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

$ source leonv/bin/activate
(leonv) vole:Downloads sa$ pip install leo
Collecting leo
  Downloading leo-6.6.2-py3-none-any.whl (13.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 4.9 MB/s eta 0:00:00
Collecting asttokens
  Downloading asttokens-2.0.5-py2.py3-none-any.whl (20 kB)
Collecting pyenchant
  Downloading pyenchant-3.2.2-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 KB 3.4 MB/s eta 0:00:00
Collecting PyQt5>=5.12
  Downloading PyQt5-5.15.6-cp36-abi3-macosx_10_13_x86_64.whl (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 10.1 MB/s eta 0:00:00
Collecting pyflakes
  Downloading pyflakes-2.4.0-py2.py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.7/69.7 KB 3.3 MB/s eta 0:00:00
Collecting meta
  Downloading meta-1.0.2.tar.gz (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 KB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting flexx
  Downloading flexx-0.8.4-py2.py3-none-any.whl (351 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 351.6/351.6 KB 7.7 MB/s eta 0:00:00
Collecting docutils
  Downloading docutils-0.18.1-py2.py3-none-any.whl (570 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.0/570.0 KB 8.7 MB/s eta 0:00:00
Collecting sphinx
  Downloading Sphinx-4.5.0-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 10.7 MB/s eta 0:00:00
Collecting nbformat
  Downloading nbformat-5.4.0-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.3/73.3 KB 3.4 MB/s eta 0:00:00
Collecting PyQtWebEngine
  Downloading PyQtWebEngine-5.15.5-cp36-abi3-macosx_10_13_x86_64.whl (186 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 186.5/186.5 KB 7.1 MB/s eta 0:00:00
Collecting build>=0.6.0
  Downloading build-0.8.0-py3-none-any.whl (17 kB)
Collecting pyshortcuts>=1.7
  Downloading pyshortcuts-1.8.2-py3-none-any.whl (248 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.9/248.9 KB 7.8 MB/s eta 0:00:00
Collecting pylint
  Using cached pylint-2.13.9-py3-none-any.whl (438 kB)
Collecting black
  Downloading black-22.3.0-cp39-cp39-macosx_10_9_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 10.1 MB/s eta 0:00:00
Collecting packaging>=19.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 KB 1.6 MB/s eta 0:00:00
Collecting pep517>=0.9.1
  Downloading pep517-0.12.0-py2.py3-none-any.whl (19 kB)
Collecting tomli>=1.0.0
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting PyQt5-sip<13,>=12.8
  Downloading PyQt5_sip-12.10.1-cp39-cp39-macosx_10_9_x86_64.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 KB 4.8 MB/s eta 0:00:00
Collecting PyQt5-Qt5>=5.15.2
  Downloading PyQt5_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (40.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 MB 10.2 MB/s eta 0:00:00
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting typing-extensions>=3.10.0.0
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting mypy-extensions>=0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting pathspec>=0.9.0
  Downloading pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting click>=8.0.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 3.7 MB/s eta 0:00:00
Collecting platformdirs>=2
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting dialite>=0.5.2
  Downloading dialite-0.5.3-py3-none-any.whl (8.8 kB)
Collecting webruntime>=0.5.6
  Downloading webruntime-0.5.8-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.7/53.7 KB 2.8 MB/s eta 0:00:00
Collecting tornado
  Downloading tornado-6.1-cp39-cp39-macosx_10_9_x86_64.whl (416 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 416.6/416.6 KB 7.8 MB/s eta 0:00:00
Collecting pscript>=0.7.7
  Downloading pscript-0.7.7-py3-none-any.whl (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.7/126.7 KB 5.6 MB/s eta 0:00:00
Collecting traitlets>=5.1
  Downloading traitlets-5.2.1.post0-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.6/106.6 KB 5.4 MB/s eta 0:00:00
Collecting jupyter-core
  Using cached jupyter_core-4.10.0-py3-none-any.whl (87 kB)
Collecting fastjsonschema
  Downloading fastjsonschema-2.15.3-py3-none-any.whl (22 kB)
Collecting jsonschema>=2.6
  Downloading jsonschema-4.5.1-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 KB 4.1 MB/s eta 0:00:00
Collecting isort<6,>=4.2.5
  Downloading isort-5.10.1-py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.4/103.4 KB 5.2 MB/s eta 0:00:00
Collecting mccabe<0.8,>=0.6
  Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting astroid<=2.12.0-dev0,>=2.11.5
  Using cached astroid-2.11.5-py3-none-any.whl (250 kB)
Collecting dill>=0.2
  Downloading dill-0.3.5.1-py2.py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.8/95.8 KB 4.4 MB/s eta 0:00:00
Collecting PyQtWebEngine-Qt5>=5.15.2
  Downloading PyQtWebEngine_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (77.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 MB 9.2 MB/s eta 0:00:00
Collecting sphinxcontrib-serializinghtml>=1.1.5
  Downloading sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.0/94.0 KB 4.3 MB/s eta 0:00:00
Collecting alabaster<0.8,>=0.7
  Downloading alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
Collecting babel>=1.3
  Downloading Babel-2.10.1-py3-none-any.whl (9.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 11.0 MB/s eta 0:00:00
Collecting sphinxcontrib-applehelp
  Downloading sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.2/121.2 KB 4.6 MB/s eta 0:00:00
Collecting snowballstemmer>=1.1
  Downloading snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.0/93.0 KB 4.1 MB/s eta 0:00:00
Collecting sphinxcontrib-htmlhelp>=2.0.0
  Downloading sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.5/100.5 KB 4.8 MB/s eta 0:00:00
Collecting imagesize
  Downloading imagesize-1.3.0-py2.py3-none-any.whl (5.2 kB)
Collecting sphinxcontrib-qthelp
  Downloading sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 KB 4.0 MB/s eta 0:00:00
Collecting docutils
  Downloading docutils-0.17.1-py2.py3-none-any.whl (575 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 575.5/575.5 KB 9.1 MB/s eta 0:00:00
Collecting requests>=2.5.0
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 2.7 MB/s eta 0:00:00
Collecting Jinja2>=2.3
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 KB 5.4 MB/s eta 0:00:00
Collecting importlib-metadata>=4.4
  Downloading importlib_metadata-4.11.4-py3-none-any.whl (18 kB)
Collecting sphinxcontrib-devhelp
  Downloading sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.7/84.7 KB 3.7 MB/s eta 0:00:00
Collecting Pygments>=2.0
  Downloading Pygments-2.12.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 10.2 MB/s eta 0:00:00
Collecting sphinxcontrib-jsmath
  Downloading sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting wrapt<2,>=1.11
  Downloading wrapt-1.14.1-cp39-cp39-macosx_10_9_x86_64.whl (35 kB)
Requirement already satisfied: setuptools>=20.0 in ./leonv/lib/python3.9/site-packages (from astroid<=2.12.0-dev0,>=2.11.5->pylint->leo) (62.1.0)
Collecting lazy-object-proxy>=1.4.0
  Downloading lazy_object_proxy-1.7.1-cp39-cp39-macosx_10_9_x86_64.whl (22 kB)
Collecting pytz>=2015.7
  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 503.5/503.5 KB 8.8 MB/s eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.8.0-py3-none-any.whl (5.4 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1-cp39-cp39-macosx_10_9_x86_64.whl (13 kB)
Collecting attrs>=17.4.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 KB 3.2 MB/s eta 0:00:00
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp39-cp39-macosx_10_9_universal2.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 KB 3.7 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 KB 4.2 MB/s eta 0:00:00
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 2.7 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.5.18.1-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.2/155.2 KB 6.7 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 KB 6.2 MB/s eta 0:00:00
Building wheels for collected packages: meta
  Building wheel for meta (setup.py) ... done
  Created wheel for meta: filename=meta-1.0.2-py3-none-any.whl size=59239 sha256=d387eb338d481bd0429ab0ffc45aa14955349c672acd3ca9b0083e2d7db2c0fa
  Stored in directory: $HOME/Library/Caches/pip/wheels/5d/f5/bc/0c39a222937664b32176cb1136074d6e353ce9a366907b13f6
Successfully built meta
Installing collected packages: snowballstemmer, pytz, PyQtWebEngine-Qt5, PyQt5-Qt5, pscript, mypy-extensions, meta, fastjsonschema, dialite, alabaster, zipp, wrapt, webruntime, urllib3, typing-extensions, traitlets, tornado, tomli, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, six, pyshortcuts, pyrsistent, PyQt5-sip, pyparsing, Pygments, pyflakes, pyenchant, platformdirs, pathspec, mccabe, MarkupSafe, lazy-object-proxy, isort, imagesize, idna, docutils, dill, click, charset-normalizer, certifi, babel, attrs, requests, PyQt5, pep517, packaging, jupyter-core, jsonschema, Jinja2, importlib-metadata, flexx, black, asttokens, astroid, sphinx, PyQtWebEngine, pylint, nbformat, build, leo
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 PyQt5-5.15.6 PyQt5-Qt5-5.15.2 PyQt5-sip-12.10.1 PyQtWebEngine-5.15.5 PyQtWebEngine-Qt5-5.15.2 Pygments-2.12.0 alabaster-0.7.12 astroid-2.11.5 asttokens-2.0.5 attrs-21.4.0 babel-2.10.1 black-22.3.0 build-0.8.0 certifi-2022.5.18.1 charset-normalizer-2.0.12 click-8.1.3 dialite-0.5.3 dill-0.3.5.1 docutils-0.17.1 fastjsonschema-2.15.3 flexx-0.8.4 idna-3.3 imagesize-1.3.0 importlib-metadata-4.11.4 isort-5.10.1 jsonschema-4.5.1 jupyter-core-4.10.0 lazy-object-proxy-1.7.1 leo-6.6.2 mccabe-0.7.0 meta-1.0.2 mypy-extensions-0.4.3 nbformat-5.4.0 packaging-21.3 pathspec-0.9.0 pep517-0.12.0 platformdirs-2.5.2 pscript-0.7.7 pyenchant-3.2.2 pyflakes-2.4.0 pylint-2.13.9 pyparsing-3.0.9 pyrsistent-0.18.1 pyshortcuts-1.8.2 pytz-2022.1 requests-2.27.1 six-1.16.0 snowballstemmer-2.2.0 sphinx-4.5.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5 tomli-2.0.1 tornado-6.1 traitlets-5.2.1.post0 typing-extensions-4.2.0 urllib3-1.26.9 webruntime-0.5.8 wrapt-1.14.1 zipp-3.8.0

$ leo

setting leoID from os.getenv('USER'): 'sa'
Invalid Leo ID: 'sa'

Your id should contain only letters and numbers
and must be at least 3 characters in length.

leoID.txt not found

Please enter an id that identifies you uniquely.
Your git/cvs/bzr login name is a good choice.

Leo uses this id to uniquely identify nodes.

Your id should contain only letters and numbers
and must be at least 3 characters in length.


Uncaught exception in Leo...
Traceback (most recent call last):
  File "$HOME/Downloads/leonv/bin/leo", line 8, in <module>
    sys.exit(run())
  File "$HOME/Downloads/leonv/lib/python3.9/site-packages/leo/core/runLeo.py", line 90, in run
    g.app.loadManager.load(fileName, pymacs)
  File "$HOME/Downloads/leonv/lib/python3.9/site-packages/leo/core/leoApp.py", line 2170, in load
    lm.doPrePluginsInit(fileName, pymacs)  # sets lm.options and lm.files
  File "$HOME/Downloads/leonv/lib/python3.9/site-packages/leo/core/leoApp.py", line 2353, in doPrePluginsInit
    lm.initApp(verbose)
  File "$HOME/Downloads/leonv/lib/python3.9/site-packages/leo/core/leoApp.py", line 2570, in initApp
    g.app.setLeoID(verbose=verbose)
  File "$HOME/Downloads/leonv/lib/python3.9/site-packages/leo/core/leoApp.py", line 1021, in setLeoID
    self.setIdFromDialog()
  File "$HOME/Downloads/leonv/lib/python3.9/site-packages/leo/core/leoApp.py", line 1112, in setIdFromDialog
    dialog.run()
  File "$HOME/Downloads/leonv/lib/python3.9/site-packages/leo/core/leoGlobals.py", line 580, in run
    self.top.geometry("%dx%d%+d%+d" % (300, 200, 50, 50))
AttributeError: 'NoneType' object has no attribute 'geometry'

(leonv) $ leo --version

Leo 6.6.2
Python 3.9.13
darwin

```

**Comment by edreamleo** [comment]
On Tue, May 24, 2022 at 11:04 AM Shakeeb Alireza ***@***.***>
wrote:

> I'm on macOS Catalina with homebrew python 3.9.13 (I don't have tkinter
> installed). I'm unable to run leo (please see below), and I get an error
> which seems to be due to a residual tkinter dependency:
>
Thanks for this report. It looks like setup.py must require tk.

This will be part of 6.6.2, part deux (or is it trois?), coming tomorrow.

Edward

**Comment by edreamleo** [comment]
Fixed at rev [4b222b](https://github.com/leo-editor/leo-editor/commit/4b222ba0c4184134ca415f23a0e4461f829bd526) in devel.

**Comment by edreamleo** [comment]
@shakfu Note that the fix won't become effective until the next "pip installable" version of Leo 6.6.2.
