### ISSUE TITLE
Tree Scroll Up/Down Throws Exception

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#2678]
This is using PgUp and PgDn keys to scroll.

```
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "c:\Tom\git\leo-editor\leo\core\leoGlobals.py", line 300, in new_cmd_wrapper
    func(self, event=event)
  File "c:\Tom\git\leo-editor\leo\commands\editCommands.py", line 3508, in scrollDownPage
    self.scrollHelper(event, 'down', 'page')
  File "c:\Tom\git\leo-editor\leo\commands\editCommands.py", line 3533, in scrollHelper
    w.scrollDelegate(kind)
  File "c:\Tom\git\leo-editor\leo\plugins\qt_tree.py", line 1249, in scrollDelegate
    vScroll.setValue(val + delta)
```

**Comment by edreamleo** [comment]
Fixed in d9f4540: This looks like a Qt bug: all the quantities involved are supposed to be ints.

**Comment by tbpassin** [comment]
Not getting ints, though:

```
def scrollDelegate(self, kind: str) -> None:
        # ...
        val = vScroll.value()
        print(val, delta)
        vScroll.setValue(val + delta)

>>> 0 -17.666666666666668
```

**Comment by edreamleo** [comment]
@tbpassin Oops. I intended to do what you suggest.

**Comment by edreamleo** [comment]
@tbpassin I don't understand. d9f45406 contains the code you suggest.

**Comment by tbpassin** [comment]
Oh, I see, somehow you snuck in an update and I didn't realize.  OK, I'll close the issue.
