### ISSUE TITLE
leoserver.py crashes on Ctrl-c with python 3.6

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2782]
Launch leoserver.py with python 3.6:
```console
>C:\Python\Python3.6\python.exe leo\core\leoserver.py
Starting LeoBridge Server 1.0.3 (Launch with -h for help)
LeoServer: init leoBridge in  0.5 sec.
LeoBridge started at localhost on port: 32125.
Ctrl+c to break
```
Hit Ctrl-c:
```console
Process interrupted
Checking for changed commanders...
Traceback (most recent call last):
  File "leo\core\leoserver.py", line 5274, in <module>
    main()
  File "leo\core\leoserver.py", line 5266, in main
    cancel_tasks(asyncio.all_tasks(loop), loop)
AttributeError: module 'asyncio' has no attribute 'all_tasks'
Terminate batch job (Y/N)? y
```

**Comment by edreamleo** [comment]
I am going to close this issue. It is not important enough to fix. Worse, attempted fixes would create worse problems. The simple and good enough solution is to use Python 3.9+
