### ISSUE TITLE
mod_scripting.py Attribute error

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#2793]
See PR #2794. Happily, this typo does not affect Leo 6.6.4.

Leo Log Window
Leo 6.6.5-devel, devel branch, build bb110d40f0
2022-09-01 12:24:54 -0500
Python 3.10.6, PyQt version 6.3.1
Windows 10 AMD64 (build 10.0.19044) SP0
read outline in 0.07 seconds
hook failed: open2, <function onCreate at 0x00000185251D2DD0>, leo.plugins.mod_scripting
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 324, in callTagHandler
result = handler(tag, keywords)
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 338, in onCreate
sc.createAllButtons()
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 560, in createAllButtons
self.createCommonButtons()
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 772, in createCommonButtons
self.createCommonButton(p, script, rclicks)
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 832, in createCommonButton
self.registerAllCommands(
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 1154, in registerAllCommands
k.registerCommand(
  File "N:\git\leo-editor\leo\core\leoKeys.py", line 3015, in registerCommand
g.trace('redefining', commandName, f, '->', func)
  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 6157, in trace
arg = repr(arg)
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 370, in __repr__
c = self.cs
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 378, in __getattr__
raise AttributeError # Returning None is not correct.
AttributeError

**Comment by LewisNeal** [comment]
Any leo file with a @button node continues to give Attribute error.

_Leo Log Window
Leo 6.7.0-devel, devel branch, build cd30f44365
2022-09-13 17:04:21 -0500
Python 3.10.6, PyQt version 6.3.1
Windows 10 AMD64 (build 10.0.19044) SP0
read outline in 0.04 seconds
hook failed: open2, <function onCreate at 0x0000011349363D00>, leo.plugins.mod_scripting
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoPlugins.py", line 355, in callTagHandler
result = handler(tag, keywords)
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 339, in onCreate
sc.createAllButtons()
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 589, in createAllButtons
func(p)
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 903, in handleAtButtonNode
self.createLocalAtButtonHelper(p, h, statusLine, verbose=False)
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 639, in createLocalAtButtonHelper
self.registerAllCommands(
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 1155, in registerAllCommands
k.registerCommand(
  File "N:\git\leo-editor\leo\core\leoKeys.py", line 3016, in registerCommand
g.trace('redefining', commandName, f, '->', func)
  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 6163, in trace
arg = repr(arg)
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 373, in __repr__
return f"AtButtonCallback {c.shortFileName()} gnx: {self.gns} len(script): {n}"
  File "N:\git\leo-editor\leo\plugins\mod_scripting.py", line 379, in __getattr__
raise AttributeError # Returning None is not correct.
AttributeError_

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report.

**Comment by edreamleo** [comment]
@LewisNeal Fixed via PR #2854.
