### ISSUE TITLE
Unable to run pip installed leo (6.7.0) from virtualenv

### ISSUE THREAD

**Issue by shakfu** [leo-editor/leo-editor#2901]
Hi,

Are there any dependencies for leo which are not pip installable?

For some reason, I am unable to install leo via a virtualenv.  I am macOS (Catalina) running python 3.10.6 (installed using Homebrew):

First create a virtualenv and `activate` it.

```bash
$ virtualenv leonv
created virtual environment CPython3.10.6.final.0-64 in 573ms
  creator CPython3Posix(dest=$HOME/Downloads/leonv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=$HOME/Library/Application Support/virtualenv)
    added seed packages: pip==22.2.2, setuptools==65.3.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
$ source leonv/bin/activate
```

Install leo via leo

```bash
(leonv) $ pip install leo
Collecting leo
  Using cached leo-6.7.0-py3-none-any.whl (9.8 MB)
Collecting build>=0.6.0
  Using cached build-0.8.0-py3-none-any.whl (17 kB)
Collecting meta
  Using cached meta-1.0.2-py3-none-any.whl
Collecting pyflakes
  Using cached pyflakes-2.5.0-py2.py3-none-any.whl (66 kB)
Collecting sphinx
  Using cached sphinx-5.2.3-py3-none-any.whl (3.2 MB)
Collecting flexx
  Using cached flexx-0.8.4-py2.py3-none-any.whl (351 kB)
Collecting PyQtWebEngine
  Using cached PyQtWebEngine-5.15.6-cp37-abi3-macosx_10_13_x86_64.whl (187 kB)
Collecting pyshortcuts>=1.7
  Using cached pyshortcuts-1.8.2-py3-none-any.whl (248 kB)
Collecting docutils
  Using cached docutils-0.19-py3-none-any.whl (570 kB)
Collecting nbformat
  Using cached nbformat-5.6.1-py3-none-any.whl (77 kB)
Collecting black
  Using cached black-22.8.0-cp310-cp310-macosx_10_9_x86_64.whl (1.4 MB)
Collecting pyenchant
  Using cached pyenchant-3.2.2-py3-none-any.whl (55 kB)
Collecting PyQt5>=5.15
  Using cached PyQt5-5.15.7-cp37-abi3-macosx_10_13_x86_64.whl (7.0 MB)
Collecting asttokens
  Using cached asttokens-2.0.8-py2.py3-none-any.whl (23 kB)
Collecting tk
  Using cached tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting pylint
  Using cached pylint-2.15.3-py3-none-any.whl (507 kB)
Collecting pep517>=0.9.1
  Using cached pep517-0.13.0-py3-none-any.whl (18 kB)
Collecting packaging>=19.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting PyQt5-Qt5>=5.15.0
  Using cached PyQt5_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (40.5 MB)
Collecting PyQt5-sip<13,>=12.11
  Using cached PyQt5_sip-12.11.0-cp310-cp310-macosx_10_9_universal2.whl (142 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pathspec>=0.9.0
  Using cached pathspec-0.10.1-py3-none-any.whl (27 kB)
Collecting click>=8.0.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting platformdirs>=2
  Using cached platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting pscript>=0.7.7
  Using cached pscript-0.7.7-py3-none-any.whl (126 kB)
Collecting tornado
  Using cached tornado-6.2-cp37-abi3-macosx_10_9_x86_64.whl (419 kB)
Collecting webruntime>=0.5.6
  Using cached webruntime-0.5.8-py3-none-any.whl (53 kB)
Collecting dialite>=0.5.2
  Using cached dialite-0.5.3-py3-none-any.whl (8.8 kB)
Collecting fastjsonschema
  Using cached fastjsonschema-2.16.2-py3-none-any.whl (22 kB)
Collecting jsonschema>=2.6
  Using cached jsonschema-4.16.0-py3-none-any.whl (83 kB)
Collecting jupyter-core
  Using cached jupyter_core-4.11.1-py3-none-any.whl (88 kB)
Collecting traitlets>=5.1
  Using cached traitlets-5.4.0-py3-none-any.whl (107 kB)
Collecting dill>=0.2
  Using cached dill-0.3.5.1-py2.py3-none-any.whl (95 kB)
Collecting isort<6,>=4.2.5
  Using cached isort-5.10.1-py3-none-any.whl (103 kB)
Collecting tomlkit>=0.10.1
  Downloading tomlkit-0.11.5-py3-none-any.whl (35 kB)
Collecting mccabe<0.8,>=0.6
  Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting astroid<=2.14.0-dev0,>=2.12.10
  Using cached astroid-2.12.10-py3-none-any.whl (263 kB)
Collecting PyQtWebEngine-Qt5>=5.15.0
  Using cached PyQtWebEngine_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (77.9 MB)
Collecting babel>=2.9
  Using cached Babel-2.10.3-py3-none-any.whl (9.5 MB)
Collecting sphinxcontrib-htmlhelp>=2.0.0
  Using cached sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl (100 kB)
Collecting requests>=2.5.0
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting sphinxcontrib-devhelp
  Using cached sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting alabaster<0.8,>=0.7
  Using cached alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
Collecting sphinxcontrib-qthelp
  Using cached sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Collecting sphinxcontrib-applehelp
  Using cached sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
Collecting snowballstemmer>=2.0
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Collecting sphinxcontrib-jsmath
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting imagesize>=1.3
  Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.5
  Using cached sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94 kB)
Collecting Pygments>=2.12
  Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Collecting Jinja2>=3.0
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting wrapt<2,>=1.11
  Using cached wrapt-1.14.1-cp310-cp310-macosx_10_9_x86_64.whl (35 kB)
Collecting lazy-object-proxy>=1.4.0
  Using cached lazy_object_proxy-1.7.1-cp310-cp310-macosx_10_9_x86_64.whl (22 kB)
Collecting pytz>=2015.7
  Using cached pytz-2022.2.1-py2.py3-none-any.whl (500 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp310-cp310-macosx_10_9_x86_64.whl (13 kB)
Collecting attrs>=17.4.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.18.1-cp310-cp310-macosx_10_9_universal2.whl (81 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Installing collected packages: tk, snowballstemmer, pytz, PyQtWebEngine-Qt5, PyQt5-Qt5, pscript, mypy-extensions, meta, fastjsonschema, dialite, alabaster, wrapt, webruntime, urllib3, traitlets, tornado, tomlkit, tomli, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, six, pyshortcuts, pyrsistent, PyQt5-sip, pyparsing, Pygments, pyflakes, pyenchant, platformdirs, pathspec, mccabe, MarkupSafe, lazy-object-proxy, isort, imagesize, idna, docutils, dill, click, charset-normalizer, certifi, babel, attrs, requests, PyQt5, pep517, packaging, jupyter-core, jsonschema, Jinja2, flexx, black, asttokens, astroid, sphinx, PyQtWebEngine, pylint, nbformat, build, leo
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 PyQt5-5.15.7 PyQt5-Qt5-5.15.2 PyQt5-sip-12.11.0 PyQtWebEngine-5.15.6 PyQtWebEngine-Qt5-5.15.2 Pygments-2.13.0 alabaster-0.7.12 astroid-2.12.10 asttokens-2.0.8 attrs-22.1.0 babel-2.10.3 black-22.8.0 build-0.8.0 certifi-2022.9.24 charset-normalizer-2.1.1 click-8.1.3 dialite-0.5.3 dill-0.3.5.1 docutils-0.19 fastjsonschema-2.16.2 flexx-0.8.4 idna-3.4 imagesize-1.4.1 isort-5.10.1 jsonschema-4.16.0 jupyter-core-4.11.1 lazy-object-proxy-1.7.1 leo-6.7.0 mccabe-0.7.0 meta-1.0.2 mypy-extensions-0.4.3 nbformat-5.6.1 packaging-21.3 pathspec-0.10.1 pep517-0.13.0 platformdirs-2.5.2 pscript-0.7.7 pyenchant-3.2.2 pyflakes-2.5.0 pylint-2.15.3 pyparsing-3.0.9 pyrsistent-0.18.1 pyshortcuts-1.8.2 pytz-2022.2.1 requests-2.28.1 six-1.16.0 snowballstemmer-2.2.0 sphinx-5.2.3 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5 tk-0.1.0 tomli-2.0.1 tomlkit-0.11.5 tornado-6.2 traitlets-5.4.0 urllib3-1.26.12 webruntime-0.5.8 wrapt-1.14.1
```

Running leo now **fails** with the following error

```bash
(leonv) $ leo

setting leoID from os.getenv('USER'): 'me'
Invalid Leo ID: 'me'

Your id should contain only letters and numbers
and must be at least 3 characters in length.

leoID.txt not found

Please enter an id that identifies you uniquely.
Your git/cvs/bzr login name is a good choice.

Leo uses this id to uniquely identify nodes.

Your id should contain only letters and numbers
and must be at least 3 characters in length.


Uncaught exception in Leo...
Traceback (most recent call last):
  File "$HOME/Downloads/leonv/bin/leo", line 8, in <module>
    sys.exit(run())
  File "$HOME/Downloads/leonv/lib/python3.10/site-packages/leo/core/runLeo.py", line 92, in run
    g.app.loadManager.load(fileName, pymacs)
  File "$HOME/Downloads/leonv/lib/python3.10/site-packages/leo/core/leoApp.py", line 2199, in load
    lm.doPrePluginsInit(fileName, pymacs)  # sets lm.options and lm.files
  File "$HOME/Downloads/leonv/lib/python3.10/site-packages/leo/core/leoApp.py", line 2382, in doPrePluginsInit
    lm.initApp(verbose)
  File "$HOME/Downloads/leonv/lib/python3.10/site-packages/leo/core/leoApp.py", line 2599, in initApp
    g.app.setLeoID(verbose=verbose)
  File "$HOME/Downloads/leonv/lib/python3.10/site-packages/leo/core/leoApp.py", line 1056, in setLeoID
    self.setIdFromDialog()
  File "$HOME/Downloads/leonv/lib/python3.10/site-packages/leo/core/leoApp.py", line 1147, in setIdFromDialog
    dialog.run()
  File "$HOME/Downloads/leonv/lib/python3.10/site-packages/leo/core/leoGlobals.py", line 594, in run
    self.top.geometry("%dx%d%+d%+d" % (300, 200, 50, 50))
AttributeError: 'NoneType' object has no attribute 'geometry'
```

**Comment by edreamleo** [comment]
@shakfu Not that I know of. However, the traceback is complaining about os.getenv('USER'):
```console
​setting leoID from os.getenv('USER'): 'me'
Invalid Leo ID: 'me'

Your id should contain only letters and numbers
and must be at least 3 characters in length.
```
Perhaps Leo 6.7.0 changed the test of the id. Please try setting os.getenv to three or more characters. Alternatively, you can set .leoID.txt.
