### ISSUE TITLE
Leo fails to start with --gui=console

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3008]
running 335c3591b7
Python 3.10.8, 
Windows 10 AMD64 (build 10.0.19044) SP0

>python launchLeo.py --gui=console
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoApp.py", line 920, in createCursesGui
    from leo.plugins import cursesGui2

  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 319, in <module>
    class LeoTreeData(npyscreen.TreeData):

  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 338, in LeoTreeData
    content = Union[str, Position]

NameError: name 'Position' is not defined

can not create curses gui.

**Comment by edreamleo** [comment]
@LewisNeal Thanks for this report. I'll fix this bug immediately.

**Comment by edreamleo** [comment]
Closed via PR #3009.
