### ISSUE TITLE
QUrl assertion fails for all uses of leoBridge

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#320]
I ran into this a month or two ago and worked around it by commenting out the assert.  It seems to happen every time leoBridge is used to open a Leo-Editor file.  That is all qurl.py does:

# qurl.py
```
import leo.core.leoBridge as leoBridge

bridge = leoBridge.controller(gui='nullGui', verbose=False,
    loadPlugins = False, readSettings = False)
leoG = bridge.g
leoG = bridge.globals()
cmdr = bridge.openLeoFile('t1.leo')

cmdr.save()
```
# run output for Python 2 and Python 3
```
2016-10-04 09:55:22 /pri/git/leo_bug_demos/Qurl
$ python qurl.py
Traceback (most recent call last):
  File "qurl.py", line 4, in <module>
    loadPlugins = False, readSettings = False)
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 65, in controller
    gBridgeController = BridgeController(gui, loadPlugins, readSettings, silent, tracePlugins, verbose)
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 83, in __init__
    self.initLeo()
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 109, in initLeo
    leoGlobals.app = leoApp.LeoApp()
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 625, in __init__
    import leo.core.leoFrame as leoFrame
  File "/pri/git/leo-editor/leo/core/leoFrame.py", line 13, in <module>
    import leo.core.leoColorizer as leoColorizer
  File "/pri/git/leo-editor/leo/core/leoColorizer.py", line 12, in <module>
    from leo.core.leoQt import isQt5, Qsci, QtCore, QtGui, QtWidgets
  File "/pri/git/leo-editor/leo/core/leoQt.py", line 49, in <module>
    assert QUrl # for pyflakes
AssertionError
2016-10-04 09:55:32 /pri/git/leo_bug_demos/Qurl
$ python3 qurl.py
Traceback (most recent call last):
  File "qurl.py", line 4, in <module>
    loadPlugins = False, readSettings = False)
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 65, in controller
    gBridgeController = BridgeController(gui, loadPlugins, readSettings, silent, tracePlugins, verbose)
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 83, in __init__
    self.initLeo()
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 109, in initLeo
    leoGlobals.app = leoApp.LeoApp()
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 625, in __init__
    import leo.core.leoFrame as leoFrame
  File "/pri/git/leo-editor/leo/core/leoFrame.py", line 13, in <module>
    import leo.core.leoColorizer as leoColorizer
  File "/pri/git/leo-editor/leo/core/leoColorizer.py", line 12, in <module>
    from leo.core.leoQt import isQt5, Qsci, QtCore, QtGui, QtWidgets
  File "/pri/git/leo-editor/leo/core/leoQt.py", line 49, in <module>
    assert QUrl # for pyflakes
AssertionError
2016-10-04 09:55:47 /pri/git/leo_bug_demos/Qurl
```
# Leo-Editor Version:
Leo Log Window
Leo 5.4-devel, build 20160722143100, Fri, Jul 22, 2016  2:31:00 PM
Git repo info: branch = master, commit = b8ef1885acd2

**Comment by edreamleo** [comment]
Rev 497eb0c removes this assert statement. Pyflakes is happy with both Python 2 and 3, so I don't see any need for the assert.

Please reopen if problems remain.
