### ISSUE TITLE
Fix crash in openUrlHelper

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3278]
```console
Traceback (most recent call last):

  File "C:\Repos\leo-editor\leo\core\leoGlobals.py", line 7437, in openUrlOnClick
    return openUrlHelper(event, url)

  File "C:\Repos\leo-editor\leo\core\leoGlobals.py", line 7558, in openUrlHelper
    m = re.match(IMPORTSre, line)

UnboundLocalError: local variable 'line' referenced before assignment
```
One might have thought that pylint would have found this, but no.

**Comment by edreamleo** [comment]
Closed via PR #3279.
