### ISSUE TITLE
Cannot Open LeoPyRef.leo

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#3298]
[ Later - Aha! This happens when I comment out a plugin in the @enabled-plugins node in the outline's settings. It seems to happen for any plugin, not just one specific one.]

[Later -I tried resetting the branch, and now I can open LeoPyRef again. I'm not aware of making any changes to the outline, except for saving after marking a node or two, so I don't know what happened to cause this.  But maybe it's not about the @files-ness of the batch.py file as it seemed from the stack trace]

This just started happening.  It seems to be related to the mode file _batch.py_ having sentinels, unlike most of the mode files (there are one or two others, I think).  Here's the stack trace:

```
scan_lines batch.py: warning: inserting unexpected line: '#@+leo-ver=5-thin'
Traceback (most recent call last):

  File "c:\Tom\git\leo-editor\leo\core\leoCommands.py", line 2610, in doCommand
    return_value = command_func(event)
                   ^^^^^^^^^^^^^^^^^^^

  File "c:\Tom\git\leo-editor\leo\core\leoGlobals.py", line 244, in commander_command_wrapper
    method(event=event)

  File "c:\Tom\git\leo-editor\leo\commands\commanderHelpCommands.py", line 158, in openLeoPyRef
    c2 = g.openWithFileName(path, old_c=c)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\Tom\git\leo-editor\leo\core\leoGlobals.py", line 3709, in openWithFileName
    return g.app.loadManager.loadLocalFile(fileName, gui, old_c)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\Tom\git\leo-editor\leo\core\leoApp.py", line 2974, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\Tom\git\leo-editor\leo\core\leoApp.py", line 3055, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\Tom\git\leo-editor\leo\core\leoApp.py", line 3246, in readOpenedLeoFile
    v = c.fileCommands.openLeoFile(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "c:\Tom\git\leo-editor\leo\core\leoFileCommands.py", line 993, in openLeoFile
    v, ratio = self.getLeoFile(
               ^^^^^^^^^^^^^^^^

  File "c:\Tom\git\leo-editor\leo\core\leoFileCommands.py", line 953, in getLeoFile
    recoveryNode = fc.readExternalFiles()
                   ^^^^^^^^^^^^^^^^^^^^^^

  File "c:\Tom\git\leo-editor\leo\core\leoFileCommands.py", line 1009, in readExternalFiles
    c.atFileCommands.readAll(c.rootPosition())

  File "c:\Tom\git\leo-editor\leo\core\leoAtFile.py", line 344, in readAll
    at.readFileAtPosition(p)

  File "c:\Tom\git\leo-editor\leo\core\leoAtFile.py", line 405, in readFileAtPosition
    at.readOneAtCleanNode(p)

  File "c:\Tom\git\leo-editor\leo\core\leoAtFile.py", line 556, in readOneAtCleanNode
    FastAtRead(c, gnx2vnode).read_into_root(contents, fileName, root)

  File "c:\Tom\git\leo-editor\leo\core\leoAtFile.py", line 3544, in read_into_root
    self.scan_lines(comment_delims, first_lines, lines, path, start_i)

  File "c:\Tom\git\leo-editor\leo\core\leoAtFile.py", line 3255, in scan_lines
    assert v != root_v
           ^^^^^^^^^^^

AssertionError
```

It seems to me that Leo used to be able to read files with sentinels even if it was expecting none - I would see the sentinels but they would just be normal lines, not doing any Leo-esque things.

```
Leo 6.7.3-devel, devel branch, build 27df347781
2023-04-21 17:05:08 -0500
Python 3.11.3, PyQt version 6.4.3
Windows 10 AMD64 (build 10.0.19044) SP0
```

**Comment by edreamleo** [comment]
@tbpassin Everything works for me in `devel`. I recently updated `LeoPyRef.leo` by making the three files in `leo/modes` to be `@file` nodes.

**Comment by tbpassin** [comment]
In line with my later update to to the issue, please go to the @settings tree in LeoPyRef and comment out, say, the todo plugin and save.  Close the outline and then try to open it again.  On my machine this reliably causes loading the outline to fail.  As soon as I uncomment the plugin (by doing a git reset since I can't edit it in Leo) it will load again.

**Comment by tbpassin** [comment]
OK, I see there has been an update since I last pulled from GitHub.  This changed the external file type for those files like batch.py from @clean to @file.  The previous changeset had sentinels in the files but @clean nodes in LeoPyRef. This has cured the problem I was having.  It's weird though, to have a wrong at-file type cause the entire outline to fail to open.

**Comment by edreamleo** [comment]
@tbpassin The `@clean` read logic compares two strings: one (supposedly) *without* sentinels and one *with* sentinels. But if the version without sentinels actually *does* sentinels then bizarre things will happen. So there's no great mystery. 

Leo's `@clean` read logic could check for an `@+leo` opening sentinel, but I don't want to do this. The resulting complication could do more harm than good.
