### ISSUE TITLE
Fix failing unit tests on some installations

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3497]
See PR #3498. Viktor reports the following unit test failures:

<details>

```console
I installed Leo 6.7.4 from PyPI also into a Debian 11 VM.

When I run the unit tests there, I receive similar errors. - See attached log:

    (Leo) user@debian-leo-study-vm:~/PyVE/PyPI/Leo$
    (Leo) user@debian-leo-study-vm:~/PyVE/PyPI/Leo$ cd lib64/python3.9/site-packages/leo
    (Leo) user@debian-leo-study-vm:~/PyVE/PyPI/Leo/lib64/python3.9/site-packages/leo$
    (Leo) user@debian-leo-study-vm:~/PyVE/PyPI/Leo/lib64/python3.9/site-packages/leo$ python -m unittest
    ................................................................................
    ................................................................................
    ...........................FF...................................................
    ....................................................s.......s...................
    ................................................................................
    ................................................................................
    ................................................................................
    ........................................F.......................................
    ...............................................s................................
    ..................................................s.............................
    .............................................................cursesGui2.py: Tk module required for clipboard handling.
    s...s.....
    ======================================================================
    FAIL: test_diff_two_branches (unittests.commands.test_editFileCommands.TestEditFileCommands)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/user/PyVE/PyPI/Leo/lib/python3.9/site-packages/leo/unittests/commands/test_editFileCommands.py", line 67, in test_diff_two_branches
        self.assertEqual(c.lastTopLevel().h, expected_last_headline)
    AssertionError: '@file leoGlobals.py' != 'git-diff-branches master devel'
    - @file leoGlobals.py
    + git-diff-branches master devel


    ======================================================================
    FAIL: test_diff_two_revs (unittests.commands.test_editFileCommands.TestEditFileCommands)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/user/PyVE/PyPI/Leo/lib/python3.9/site-packages/leo/unittests/commands/test_editFileCommands.py", line 121, in test_diff_two_revs
        self.assertEqual(c.lastTopLevel().h.strip(), expected_last_headline)
    AssertionError: 'root' != 'git diff revs: HEAD'
    - root
    + git diff revs: HEAD


    ======================================================================
    FAIL: test_per_commander_data (unittests.core.test_leoGlobals.TestGlobals)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/user/PyVE/PyPI/Leo/lib/python3.9/site-packages/leo/unittests/core/test_leoGlobals.py", line 294, in test_per_commander_data
        self._test_per_commander_data()
      File "/home/user/PyVE/PyPI/Leo/lib/python3.9/site-packages/leo/unittests/core/test_leoGlobals.py", line 178, in _test_per_commander_data
        self.assertTrue(os.path.exists(z), msg=repr(z))
    AssertionError: False is not true : '/home/user/PyVE/PyPI/Leo/lib/python3.9/site-packages/launchLeo.py'

    ----------------------------------------------------------------------
    Ran 871 tests in 8.914s

    FAILED (failures=3, skipped=6)
    (Leo) user@debian-leo-study-vm:~/PyVE/PyPI/Leo/lib64/python3.9/site-packages/leo$ 
```

</details>

These failures occur because `site-packages` contains only a `leo` directory, not a `leo-editor` directory. As a result, `launchLeo.py` does not exist, for example. I suspect that there is no easy fix for the missing `leo-editor` directory. See [this documentation page](https://leo-editor.github.io/leo-editor/installing.html#pypi-install-caveat).

**Comment by edreamleo** [comment]
Closed via PR #3498.

**Comment by edreamleo** [comment]
I am reopening this issue. PR #2498 is not good enough.

**Comment by edreamleo** [comment]
I am going to close this issue again. The issue with running unit tests after `pip install leo` is an edge case, of no practical importance to most users.  The PR may have suppressed the failing tests, but even if it doesn't there should be no real problem.
