### ISSUE TITLE
Leo crashes on open unless pyenchant is installed

### ISSUE THREAD

**Issue by jrhutchinson5359** [leo-editor/leo-editor#3582]
Dev branch was working fine on Friday Sept 22. Pulled new changes this morning and received the following crash. Note my workspace has 2 Leo files open in it, I assume this is why there are two instances of the crash, as Leo tries to open both files.

Leo does not open either file after producing this trace:

<details>

```console

tmp $ Leo 6.7.5-devel, devel branch, build c46189296b
2023-09-25 01:31:31 -0500
Python 3.9.2, PyQt version 5.15.2
Windows 10 AMD64 (build 10.0.19041) SP0
expand_css_constants Unresolved @constants
[
     0: '@screencast-font-style'
]

Can not load session
Traceback (most recent call last):

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoApp.py", line 2307, in doPostPluginsInit
    g.app.sessionManager.load_session(c1, aList)

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoSessions.py", line 72, in load_session
    g.app.loadManager.loadLocalFile(fn, gui=g.app.gui, old_c=c)

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoApp.py", line 3012, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoApp.py", line 3073, in openFileByName
    c = g.app.newCommander(

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoApp.py", line 1514, in newCommander
    c = leoCommands.Commands(fileName,

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoCommands.py", line 154, in __init__
    c.finishCreate()  # Slightly slow.

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoCommands.py", line 436, in finishCreate
    c.frame.log.finishCreate()

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\plugins\qt_frame.py", line 2596, in finishCreate
    c.spellCommands.openSpellTab()

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\commands\spellCommands.py", line 429, in openSpellTab
    self.handler = SpellTabHandler(c, tabName)

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\commands\spellCommands.py", line 661, in __init__
    self.spellController = DefaultWrapper(c)  # type:ignore

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\commands\spellCommands.py", line 188, in __init__
    self.user_fn = self.find_user_dict()

AttributeError: 'DefaultWrapper' object has no attribute 'find_user_dict'

expand_css_constants Unresolved @constants
[
     0: '@screencast-font-style'
]

Can not create workbook
Traceback (most recent call last):

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoApp.py", line 2321, in doPostPluginsInit
    c1 = lm.openWorkBook()

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoApp.py", line 2365, in openWorkBook
    c = self.loadLocalFile(fn, gui=g.app.gui, old_c=None)

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoApp.py", line 3012, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoApp.py", line 3073, in openFileByName
    c = g.app.newCommander(

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoApp.py", line 1514, in newCommander
    c = leoCommands.Commands(fileName,

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoCommands.py", line 154, in __init__
    c.finishCreate()  # Slightly slow.

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\core\leoCommands.py", line 436, in finishCreate
    c.frame.log.finishCreate()

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\plugins\qt_frame.py", line 2596, in finishCreate
    c.spellCommands.openSpellTab()

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\commands\spellCommands.py", line 429, in openSpellTab
    self.handler = SpellTabHandler(c, tabName)

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\commands\spellCommands.py", line 661, in __init__
    self.spellController = DefaultWrapper(c)  # type:ignore

  File "C:\cygwin64\home\jrhut\src\leo-editor\leo-editor\leo\commands\spellCommands.py", line 188, in __init__
    self.user_fn = self.find_user_dict()

AttributeError: 'DefaultWrapper' object has no attribute 'find_user_dict'

</details?

**Comment by largo84** [comment]
I have the same problem, cannot open Leo after updating.

**Comment by gatesphere** [comment]
I had the same issue on Arch Linux earlier today.  I resolved it by installing pyenchant.  It appears that pyenchant may inadvertently be a requirement now, rather than an option.

**Comment by edreamleo** [comment]
@jrhutchinson5359 @gatesphere @largo84 Thanks for your testing and comments.

I'll make sure pyenchant remains optional!

**Comment by edreamleo** [comment]
@jrhutchinson5359 @gatesphere @largo84 The fixes are now in devel. Please reopen #3582 to report any further problems.

**Comment by edreamleo** [comment]
Fixed via PR #3583.

**Comment by jrhutchinson5359** [comment]
John Hutchinson
***@***.***
+1 732 705-1343 (voice + text)
The current version in Devel appears to be working now.

Thanks,
=John

**Comment by edreamleo** [comment]
@jrhutchinson5359 Thanks for the confirmation.
