### ISSUE TITLE
'DefaultDict' object has no attribute 'd'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3859]
Leo fails to start:

Leo 6.7.9-devel, devel branch, build 9b0cbd30de
2024-04-09 16:45:54 -0500
Python 3.12.2, PyQt version 6.6.3
Windows 10 AMD64 (build 10.0.19045) SP0
VR3: *** No Markdown ***
Can not load session
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoApp.py", line 2307, in doPostPluginsInit
    g.app.sessionManager.load_session(c1, aList)

  File "N:\git\leo-editor\leo\core\leoSessions.py", line 72, in load_session
    g.openWithFileName(fn, gui=g.app.gui, old_c=c)

  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 3236, in openWithFileName
    return g.app.loadManager.openWithFileName(fileName, gui, old_c)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoApp.py", line 3010, in openWithFileName
    return lm.openExistingLeoFile(file_name, gui, old_c)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoApp.py", line 3209, in openExistingLeoFile
    c = g.app.newCommander(
        ^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoApp.py", line 1516, in newCommander
    c = leoCommands.Commands(fileName,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 164, in __init__
    c.finishCreate()  # Slightly slow.
    ^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 466, in finishCreate
    c.frame.log.finishCreate()

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 2602, in finishCreate
    c.spellCommands.openSpellTab()

  File "N:\git\leo-editor\leo\commands\spellCommands.py", line 442, in openSpellTab
    self.handler = SpellTabHandler(c, tabName)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\commands\spellCommands.py", line 674, in __init__
    self.spellController = DefaultWrapper(c)  # type:ignore
                           ^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\commands\spellCommands.py", line 184, in __init__
    g.app.spellDict = DefaultDict().d  # 2024/04/09: bug fix.
                      ^^^^^^^^^^^^^^^

AttributeError: 'DefaultDict' object has no attribute 'd'

Can not create workbook
Traceback (most recent call last):

  File "N:\git\leo-editor\leo\core\leoApp.py", line 2321, in doPostPluginsInit
    c1 = lm.openWorkBook()
         ^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoApp.py", line 2365, in openWorkBook
    c = g.openWithFileName(fn, gui=g.app.gui, old_c=None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 3236, in openWithFileName
    return g.app.loadManager.openWithFileName(fileName, gui, old_c)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoApp.py", line 3010, in openWithFileName
    return lm.openExistingLeoFile(file_name, gui, old_c)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoApp.py", line 3209, in openExistingLeoFile
    c = g.app.newCommander(
        ^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoApp.py", line 1516, in newCommander
    c = leoCommands.Commands(fileName,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 164, in __init__
    c.finishCreate()  # Slightly slow.
    ^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\core\leoCommands.py", line 466, in finishCreate
    c.frame.log.finishCreate()

  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 2602, in finishCreate
    c.spellCommands.openSpellTab()

  File "N:\git\leo-editor\leo\commands\spellCommands.py", line 442, in openSpellTab
    self.handler = SpellTabHandler(c, tabName)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\commands\spellCommands.py", line 674, in __init__
    self.spellController = DefaultWrapper(c)  # type:ignore
                           ^^^^^^^^^^^^^^^^^

  File "N:\git\leo-editor\leo\commands\spellCommands.py", line 184, in __init__
    g.app.spellDict = DefaultDict().d  # 2024/04/09: bug fix.
                      ^^^^^^^^^^^^^^^

AttributeError: 'DefaultDict' object has no attribute 'd'

**Comment by LewisNeal** [comment]
@tbpassin your suggested fix in spellCommands.py works.

**Comment by tbpassin** [comment]
I'm not planning to do a PR for this - I assume Edward will pick it up in his next round of changes ...

**Comment by tbpassin** [comment]
This problem seems to have been fixed in today's changeset, so I'll close the issue.
