### ISSUE TITLE
editpane.py plugin - object has no attribute 'QsciScintilla'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3894]
See PR #4024.

Leo 6.7.9-devel, devel branch, build 15f6b5fa8d
Python 3.12.1, PyQt version 6.7.0
Windows 10 AMD64 (build 10.0.19045) SP0

Running command edit-pane-csv command gives this error:

<details><summary><b>Traceback</b></summary>
<br>

Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 2730, in doCommand
return_value = command_func(event)
^^^^^^^^^^^^^^^^^^^
  File "N:\git\leo-editor\leo\plugins\editpane\editpane.py", line 61, in edit_pane_csv
w.insert(-1, LeoEditPane(c=c, show_control=False, lep_type='EDITOR-CSV'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\git\leo-editor\leo\plugins\editpane\editpane.py", line 105, in __init__
self.load_modules()
  File "N:\git\leo-editor\leo\plugins\editpane\editpane.py", line 401, in load_modules
modules.append(import_module('leo.plugins.editpane.' + name))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python3\Lib\importlib\__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "N:\git\leo-editor\leo\plugins\editpane\vanillascintilla.py", line 24, in <module>
class LEP_VanillaScintilla(Qsci.QsciScintilla):
^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'QsciScintilla'

</details?

**Comment by edreamleo** [comment]
Closed via PR #4024. Feel free to reopen if problems remain.

**Comment by LewisNeal** [comment]
The editpane.py plugin is working again. Thanks for the fix.

**Comment by edreamleo** [comment]
@LewisNeal You're welcome. Thanks for your testing.
