### ISSUE TITLE
--gui=console error -  'StatusLineWrapper' object has no attribute 'computeStatusUnl'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3904]
Leo console gui fails to start
launchleo.py --gui=console

_Leo 6.7.9-devel, devel branch, build ef0334290e
2024-05-07 09:03:33 -0500
Python 3.12.2, Leo Console Gui (npyscreen)
Windows 10 AMD64 (build 10.0.19045) SP0

Uncaught exception in Leo...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "N:\git\leo-editor\leo\core\runLeo.py", line 108, in <module>
    run()
  File "N:\git\leo-editor\leo\core\runLeo.py", line 96, in run
    g.app.loadManager.load(fileName, pymacs)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2263, in load
    g.app.gui.runMainLoop()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1583, in runMainLoop
    self.curses_app.run()  # run calls CApp.main(), which calls CGui.run().
    ^^^^^^^^^^^^^^^^^^^^^
  File "N:\git\leo-editor\leo\external\npyscreen\apNPSApplication.py", line 44, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\git\leo-editor\leo\external\npyscreen\npyssafewrapper.py", line 47, in wrapper
    wrapper_no_fork(call_function)
  File "N:\git\leo-editor\leo\external\npyscreen\npyssafewrapper.py", line 106, in wrapper_no_fork
    return_code = call_function(_SCREEN)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "N:\git\leo-editor\leo\external\npyscreen\apNPSApplication.py", line 37, in __remove_argument_call_main
    return self.main()
           ^^^^^^^^^^^
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 2708, in main
    g.app.gui.run()
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1596, in run
    self.top_form = self.createCursesTop()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "N:\git\leo-editor\leo\plugins\cursesGui2.py", line 1317, in createCursesTop
    c.frame.tree.set_status_line(c.p)
  File "N:\git\leo-editor\leo\core\leoFrame.py", line 1707, in set_status_line
    s = c.frame.computeStatusUnl(p)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\git\leo-editor\leo\core\leoFrame.py", line 903, in computeStatusUnl
    return self.statusLine.computeStatusUnl(p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StatusLineWrapper' object has no attribute 'computeStatusUnl'_
<end>

windows curses v2.3.3a1 and v2.3.3 both worked when running Leo build https://github.com/leo-editor/leo-editor/commit/d84e34255abf321b4f144a104dc9062b76076381.

**Comment by LewisNeal** [comment]
The error first occured running build 91762ed

**Comment by LewisNeal** [comment]
Fixed with 9f111a9
Thanks
