### ISSUE TITLE
A unit test fails after merging PR #3843

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3944]
After merging PR #3943 the `TestLeoServer.test_find_commands` unit test fails.

I am responsible for mistake: the leoserver code followed my erroneous code.

```console
======================================================================
ERROR: test_find_commands (leo.unittests.core.test_leoserver.TestLeoServer.test_find_commands)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 2170, in find_def
    patterns = fc.make_patterns(alt_word)
               ^^^^^^^^^^^^^^^^
AttributeError: 'LeoFind' object has no attribute 'make_patterns'. Did you mean: '_make_patterns'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Repos\leo-editor\leo\unittests\core\test_leoserver.py", line 199, in test_find_commands
    answer = self._request(method, {"log": log, "find_text": "def"})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\unittests\core\test_leoserver.py", line 63, in _request
    response = server._do_message(d)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 4895, in _do_message
    result = func(action, param)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 4911, in _do_server_command
    return func(param)
           ^^^^^^^^^^^
  File "C:\Repos\leo-editor\leo\core\leoserver.py", line 2213, in find_def
    raise ServerError(f"{tag}: Running find symbol definition gave exception: {e}")
leo.core.leoserver.ServerError: find_def: Running find symbol definition gave exception: 'LeoFind' object has no attribute 'make_patterns'
```

**Comment by edreamleo** [comment]
Fixed via PR #3945.
