### ISSUE TITLE
Crash in VR plugin while executing a check button in leoSettings.leo

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3949]
See PR #3951.
```console
hook failed: after-create-leo-frame, <function onCreate at 0x00000266C4318D60>, leo.plugins.viewrendered
Traceback (most recent call last):

  File "C:\Repos\leo-editor\leo\core\leoPlugins.py", line 348, in callTagHandler
    result = handler(tag, keywords)
             ^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Repos\leo-editor\leo\plugins\viewrendered.py", line 342, in onCreate
    vr = viewrendered(keys)
         ^^^^^^^^^^^^^^^^^^

  File "C:\Repos\leo-editor\leo\plugins\viewrendered.py", line 417, in viewrendered
    main_splitter = gui.find_widget_by_name(c, 'main_splitter')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Repos\leo-editor\leo\plugins\qt_gui.py", line 1525, in find_widget_by_name
    if w.objectName() == name:
       ^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'objectName'
```

**Comment by edreamleo** [comment]
Fixed via PR #3951.
