### ISSUE TITLE
AttributeError: 'VNodeBase' object has no attribute '_import_lines'

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#400]
Saved outline, closed outline but not Leo, then did git reset --hard and re-opened outline from Recent files.

```
Exception running Py_Importer
Traceback (most recent call last):

  File "/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/core/leoImport.py", line 936, in scanner_for_ext_cb
    return scanner.run(s, parent, prepass=prepass)

  File "/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/plugins/importers/linescanner.py", line 450, in run
    self.generate_nodes(s, parent)

  File "/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/plugins/importers/linescanner.py", line 520, in generate_nodes
    self.post_pass(parent)

  File "/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/plugins/importers/linescanner.py", line 726, in post_pass
    self.unindent_all_nodes(parent)

  File "/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/plugins/importers/linescanner.py", line 813, in unindent_all_nodes
    lines = self.get_lines(p)

  File "/mnt/usr1/usr1/home/tbrown/t/Package/leo/git/leo-editor/leo/plugins/importers/linescanner.py", line 175, in get_lines
    return  p.v._import_lines

AttributeError: 'VNodeBase' object has no attribute '_import_lines'
```

at cc0c286f3.

**Comment by edreamleo** [comment]
Fixed in master at 4bb2f967.

This was an ancient bug.  Not sure why it started showing up now.
