### ISSUE TITLE
CTRL-Click For Definition Needs A Guard

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4031]
I was Ctrl-clicking in some code in LeoPyRef.leo and got a failure, which so far hasn't repeated.  I don't know exactly what I did to cause this, but at least Leo continued to work:

```
Traceback (most recent call last):
  File "c:\Tom\git\leo-editor\leo\core\leoGlobals.py", line 7297, in openUrlOnClick
    return openUrlHelper(event, url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Tom\git\leo-editor\leo\core\leoGlobals.py", line 7397, in openUrlHelper
    matches = c.findCommands.find_def(event)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Tom\git\leo-editor\leo\core\leoFind.py", line 556, in find_def
    return self.do_find_def(word)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Tom\git\leo-editor\leo\core\leoFind.py", line 567, in do_find_def
    if not word.strip():
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```
I'm in my own branch that is based on devel as it was two days ago.

**Comment by edreamleo** [comment]
@tbpassin PR #4017 fixes this.
