### ISSUE TITLE
Two unit tests fail with Python 3.13

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4156]
See PR #4169. With Python 3.13:

- `TT.test_visitors_exist` fails.
- `leo/external/npyscreen/__init__.py throws an exception, causing an error in `unittest discover`.

```console
======================================================================
ERROR: leo.external.npyscreen (unittest.loader._FailedTest.leo.external.npyscreen)
----------------------------------------------------------------------
ImportError: Failed to import test module: leo.external.npyscreen
Traceback (most recent call last):
  File "C:\Python\Python3.13\Lib\unittest\loader.py", line 429, in _find_test_path
    package = self._get_module_from_name(name)
  File "C:\Python\Python3.13\Lib\unittest\loader.py", line 339, in _get_module_from_name
    __import__(name)
    ~~~~~~~~~~^^^^^^
  File "C:\Repos\leo-editor\leo\external\npyscreen\__init__.py", line 8, in <module>
    from .wgwidget                  import TEST_SETTINGS, ExhaustedTestInput, add_test_input_from_iterable, add_test_input_ch
  File "C:\Repos\leo-editor\leo\external\npyscreen\wgwidget.py", line 10, in <module>
    import curses
  File "C:\Python\Python3.13\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'


======================================================================
FAIL: test_visitors_exist (leo.unittests.core.test_leoAst.TestTokens.test_visitors_exist)
Ensure that visitors exist for all ast nodes.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Repos\leo-editor\leo\unittests\core\test_leoAst.py", line 2818, in test_visitors_exist
    assert not errors, msg
           ^^^^^^^^^^
AssertionError: 68 node types, 32 op types, 1 errors

----------------------------------------------------------------------
```

**Comment by edreamleo** [comment]
Fixed via PR #4169.
