### ISSUE TITLE
leo/scripts/pylint_leo fails

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/leo-editor#4212]
When run in the leo/scripts directory, the traceback is

```
C:\Tom\git\leo-editor\leo\scripts>py pylint_leo.py
pylint_leo.py
Traceback (most recent call last):
  File "C:\Tom\git\leo-editor\leo\scripts\pylint_leo.py", line 25, in <module>
    rc_file_name = PylintCommand(c=None).get_rc_file()  # #4191.
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Roaming\Python\Python312\site-packages\leo\commands\checkerCommands.py", line 655, in get_rc_file
    local_dir = g.os_path_dirname(c.fileName())
                                  ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fileName'
```

**Comment by edreamleo** [comment]
I am closing this issue. pylint_leo is not meant to be run from the leo/scripts directory.

**Comment by tbpassin** [comment]
How is it intended to be run?

**Comment by tbpassin** [comment]
> Via the scripts in leo/scripts

`leo/scripts` **is** the current directory from which I ran pylint_leo.py and got the stack trace.

Based on the stack trace, the `c.fileName()` fails because  `c` is not known at that point.

**Comment by edreamleo** [comment]
@tbpassin I don't know what's going on with your installation. The following works for me:
```console
C:\Repos\leo-editor>python -m leo.scripts.pylint_leo
pylint_leo.py
```
The following does not work for me, but I don't care:
```console
C:\Repos\leo-editor\leo\scripts>python -m pylint_leo
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Repos\leo-editor\leo\scripts\pylint_leo.py", line 14, in <module>
    from leo.commands.checkerCommands import PylintCommand
ModuleNotFoundError: No module named 'leo'
```
Please, let's move on.

**Comment by edreamleo** [comment]
@tbpassin Please remember to report `pylint --version` when discussing pylint complaints. I see nothing wrong:
```
pylint --version
pylint 3.3.1
astroid 3.3.5
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]
```
It would be shocking if I did see any complaints. I *always* run `pylint-leo.cmd` after pulling *anything* into devel. This command file contains:
```cmd
cd c:\Repos\leo-editor
python -m leo.scripts.pylint_leo
```
