### ISSUE TITLE
Potential bug in settings

### ISSUE THREAD

**Issue by breisfeld** [leo-editor/leo-editor#434]
```
$ uname -a
Darwin local.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
```

```
git rev-parse origin/master
8f01f57131ae2b934efaad33c5d676327c68f92d
```

```
$ python
Python 3.5.3 |Anaconda custom (x86_64)| (default, Feb 22 2017, 20:51:01)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

```
$ python launchLeo.py

setting leoID from os.getenv('USER'): '<user>'
reading settings in /Users/<user>/build-dirs/leo-editor/leo/config/leoSettings.leo
reading settings in /Users/<user>/.leo/myLeoSettings.leo
Using default leo file name:
/Users/<user>/.leo/workbook.leo

** isPython3: True
Leo 5.4, build 20170301100728, Wed Mar  1 10:07:28 CST 2017
Git repo info: branch = master, commit = 8f01f57131ae
Python 3.5.3, PyQt version 5.6.2
darwin
reading settings in /Users/<user>/build-dirs/leo-editor/leo/doc/CheatSheet.leo
wrote recent file: /Users/<user>/.leo/.leoRecentFiles.txt
reading settings in /Users/<user>/.leo/myLeoSettings.leo
read only: unl:///Users/<user>/build-dirs/leo-editor/leo/config/leoSettings.leo
error parsing unl:///Users/<user>/build-dirs/leo-editor/leo/config/leoSettings.leo
Traceback (most recent call last):

  File "/Users/<user>/build-dirs/leo-editor/leo/core/leoFileCommands.py", line 1243, in parse_leo_file
    s = str(s, encoding='utf-8')

TypeError: coercing to str: need a bytes-like object, NoneType found

exception executing command
Traceback (most recent call last):

  File "/Users/<user>/build-dirs/leo-editor/leo/core/leoCommands.py", line 5501, in doCommand
    val = command(event)

  File "/Users/<user>/build-dirs/leo-editor/leo/core/leoConfig.py", line 2149, in f
    self.find_setting(setting)

  File "/Users/<user>/build-dirs/leo-editor/leo/core/leoConfig.py", line 2112, in find_setting
    unl = self.copy_to_my_settings(unl, which=2)

  File "/Users/<user>/build-dirs/leo-editor/leo/core/leoConfig.py", line 2068, in copy_to_my_settings
    c2 = g.app.loadManager.openSettingsFile(path)

  File "/Users/<user>/build-dirs/leo-editor/leo/core/leoApp.py", line 1903, in openSettingsFile
    readAtFileNodesFlag=False, silent=True)

  File "/Users/<user>/build-dirs/leo-editor/leo/core/leoFileCommands.py", line 833, in openLeoFile
    silent=silent,

  File "/Users/<user>/build-dirs/leo-editor/leo/core/leoFileCommands.py", line 698, in getLeoFile
    theFile.close()

AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by edreamleo** [comment]
Strange. I can't reproduce this simply by removing `~/.leo/myLeoSettings.leo`, despite receiving the log message:

    Using default leo file name:

Even more strange is the log message:

    read only: unl:///Users/<user>/build-dirs/leo-editor/leo/config/leoSettings.leo

Where is `unl:///` coming from? @breisfeld Do you have any ideas?

The logic that reads settings files is (necessarily) long and difficult.  I want to make minimal changes to it.

First, I'll add a guard in `fc.parse_leo_file`. This will fix the proximal cause of the crash. It may not be enough.

**Comment by edreamleo** [comment]
The traceback provides other clues, again fairly strange.  It appears that a command is being executed on startup: the second traceback starts with `c.doCommand` and contains a call to `sf.copy_to_my_settings` later on.

@breisfeld Is there something you aren't telling me?  Did you get the entire traceback on startup, or did you execute a reload-settings command later?

In any case, it looks like `sf..copy_to_my_settings` should also contain a guard.

**Comment by edreamleo** [comment]
The `unl///` mystery can be traced to `sf.copy_to_my_settings`. It is supposed to undo additions made by `p.get_UNL`, which formerly added `file://` but now adds `unl://`.

So another part of the fix will be to  `sf.copy_to_my_settings`.

**Comment by edreamleo** [comment]
Rev abfe828 makes the changes noted above.  All tests pass.

Please reopen if there are further problems.
