### ISSUE TITLE
Cannot open leoSettings.leo file

### ISSUE THREAD

**Issue by daiwhea** [leo-editor/leo-editor#475]
When I updated to MacOS 10.12.4, my old 4.7.1 leo cannot run. So I updated to Python3.6 and PyQt5. And now leoeditor can be shown. But it cannot open even the leoSetting.leo file shipped with leo itself. 

I don't sure it's a bug or not. Below is the output. Would you please have a look at it? Thanks.

$ /usr/local/homebrew/Cellar/python3/3.6.1/bin/python3 /Users/xxxxx/dev/ide/Leo-5.5/launchLeo.py  /Users/xxxxx/dev/ide/leo-5.5/leo/config/leoSettings.leo
setting leoID from os.getenv('USER'): 'xxxxx'
reading settings in /Users/xxxxx/dev/ide/leo-5.5/leo/config/leoSettings.leo
error parsing /Users/xxxxx/dev/ide/leo-5.5/leo/config/leoSettings.leo
Traceback (most recent call last):

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 1264, in parse_leo_file
    parser.parse(theFile) # expat does not support parseString

  File "/usr/local/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)

  File "/usr/local/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)

  File "/usr/local/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)

  File "/private/tmp/python3-20170423-57120-18xo3jz/Python-3.6.1/Modules/pyexpat.c", line 414, in StartElement

  File "/usr/local/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/expatreader.py", line 322, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 265, in startElement
    func(attrs)

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 310, in startGlobals
    ratio, ratio2 = c.cacher.getCachedGlobalFileRatios()

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoCache.py", line 238, in getCachedGlobalFileRatios
    key = self.fileKey(c.mFileName, self.globals_tag)

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoCache.py", line 134, in fileKey
    m.update(branch)

TypeError: Unicode-objects must be encoded before hashing

error parsing /Users/xxxxx/dev/ide/leo-5.5/leo/config/leoSettings.leo
Traceback (most recent call last):

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 1264, in parse_leo_file
    parser.parse(theFile) # expat does not support parseString

  File "/usr/local/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)

  File "/usr/local/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)

  File "/usr/local/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)

  File "/private/tmp/python3-20170423-57120-18xo3jz/Python-3.6.1/Modules/pyexpat.c", line 414, in StartElement

  File "/usr/local/homebrew/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/sax/expatreader.py", line 322, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 265, in startElement
    func(attrs)

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 310, in startGlobals
    ratio, ratio2 = c.cacher.getCachedGlobalFileRatios()

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoCache.py", line 238, in getCachedGlobalFileRatios
    key = self.fileKey(c.mFileName, self.globals_tag)

  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoCache.py", line 134, in fileKey
    m.update(branch)

TypeError: Unicode-objects must be encoded before hashing

Traceback (most recent call last):
  File "/Users/xxxxx/dev/ide/Leo-5.5/launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/runLeo.py", line 63, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoApp.py", line 2060, in load
    ok = lm.doPostPluginsInit()
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoApp.py", line 2649, in doPostPluginsInit
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoApp.py", line 2886, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoApp.py", line 2923, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoApp.py", line 3093, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 833, in openLeoFile
    silent=silent,
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 667, in getLeoFile
    recoveryNode = fc.readExternalFiles(fileName)
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 799, in readExternalFiles
    fc.setPositionsFromVnodes()
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoFileCommands.py", line 1349, in setPositionsFromVnodes
    str_pos = c.cacher.getCachedStringPosition()
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoCache.py", line 256, in getCachedStringPosition
    key = self.fileKey(c.mFileName, self.globals_tag)
  File "/Users/xxxxx/dev/ide/leo-5.5/leo/core/leoCache.py", line 134, in fileKey
    m.update(branch)
TypeError: Unicode-objects must be encoded before hashing

**Comment by edreamleo** [comment]
This may be a duplicate issue. In any event, I'll give it top priority.  Expect a fix later today or early tomorrow.

**Comment by daiwhea** [comment]
Great! Thanks a lot.

**Comment by edreamleo** [comment]
Please reopen if there are further problems.
