### ISSUE TITLE
Traceback when executing `goto-prev-history-node` between chapters

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#548]
If I am in a chapter view and execute `goto-prev-history-node` to go to a different chapter view I get:

```
Traceback (most recent call last):

File "leo-editor\leo\core\leoGlobals.py", line 2317, in wrapper
func(self, event=event)

File "leo-editor\leo\core\leoCommands.py", line 7018, in goToPrevHistory
c.nodeHistory.goPrev()

File "leo-editor\leo\core\leoHistory.py", line 42, in goPrev
self.select(p, chapter)

File "leo-editor\leo\core\leoHistory.py", line 58, in select
c.selectPosition(p) # Calls cc.selectChapterForPosition

File "leo-editor\leo\core\leoCommands.py", line 7175, in selectPosition
cc.selectChapterForPosition(p)

File "leo-editor\leo\core\leoChapters.py", line 344, in selectChapterForPosition
c.redraw_later()

AttributeError: 'Commands' object has no attribute 'redraw_later'
```
To create a direct history between two chapters I simply used `chapter-select`.

I'm on the most recent master as of Sept 7th 2017, Python 2.7.

**Comment by edreamleo** [comment]
On Thu, Sep 7, 2017 at 12:56 PM, John Lunzer <notifications@github.com>
wrote:

> If I am in a chapter view and execute goto-prev-history-node to go to a
> different chapter view I get:
>
> Traceback (most recent call last):
>
>
> File "leo-editor\leo\core\leoChapters.py", line 344, in selectChapterForPosition
> c.redraw_later()
>
> AttributeError: 'Commands' object has no attribute 'redraw_later'
>
>
​Fixed at rev ecbf202.  Somehow the redraw branch didn't get completely
merged into master.

Edward
