### ISSUE TITLE
AttributeError: 'LeoApp' object has no attribute 'cacher'

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#556]
This is a leoBridge bug.  It has existed since at least:
```
Leo 5.5, build 20170816073453, Wed Aug 16 07:34:53 UTC 2017
Git repo info: branch = master, commit = 546047bfd20e
 ```

It also exists in the latest version:
```
Leo 5.6, build 20171020132815, Fri, Oct 20, 2017  1:28:15 PM
Git repo info: branch = master, commit = e996713191de
```

no_cacher.py is a very simple program that demonstrates the bug.

no_cacher.leo is a minimal Leo-Editor file used by no_cacher.py.

no_cacher.py and no_cacher.leo are in gist:
```
https://gist.github.com/SegundoBob/7d961d8bab6d7e51e465372ae1582394
```

## Test System:
```
Xubuntu 16.04
Python 2.7.12, LeoGui: dummy version
Python 3.5.2, LeoGui: dummy version
```
## Test Runs:
```
$ python2 no_cacher.py
setting leoID from os.getenv('USER'): 'bob'

Leo 5.5, build 20170816073453, Wed Aug 16 07:34:53 UTC 2017
Git repo info: branch = master, commit = 546047bfd20e
Python 2.7.12, LeoGui: dummy version
linux2
** isPython3: False
** caching enabled

reading settings in /pri/git/leo_bug_demos/no_cacher/no_cacher.leo
wrote recent file: /home/bob/.leo/.leoRecentFiles.txt
Traceback (most recent call last):
  File "no_cacher.py", line 33, in <module>
    main()
  File "no_cacher.py", line 29, in main
    cmdrIn.close()
  File "/pri/git/leo-editor/leo/core/leoCommands.py", line 2080, in close
    g.app.closeLeoWindow(self.frame, new_c=new_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 964, in closeLeoWindow
    g.app.finishQuit()
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1193, in finishQuit
    g.app.cacher.commit()
AttributeError: 'LeoApp' object has no attribute 'cacher'
2017-10-21 16:03:23 /pri/git/leo_bug_demos/no_cacher

$ python3 no_cacher.py
setting leoID from os.getenv('USER'): 'bob'

Leo 5.5, build 20170816073453, Wed Aug 16 07:34:53 UTC 2017
Git repo info: branch = master, commit = 546047bfd20e
Python 3.5.2, LeoGui: dummy version
linux
** isPython3: True
** caching enabled

reading settings in /pri/git/leo_bug_demos/no_cacher/no_cacher.leo
wrote recent file: /home/bob/.leo/.leoRecentFiles.txt
Traceback (most recent call last):
  File "no_cacher.py", line 33, in <module>
    main()
  File "no_cacher.py", line 29, in main
    cmdrIn.close()
  File "/pri/git/leo-editor/leo/core/leoCommands.py", line 2080, in close
    g.app.closeLeoWindow(self.frame, new_c=new_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 964, in closeLeoWindow
    g.app.finishQuit()
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1193, in finishQuit
    g.app.cacher.commit()
AttributeError: 'LeoApp' object has no attribute 'cacher'

2017-10-21 16:04:17 /pri/git/leo_bug_demos/no_cacher
$ python2 no_cacher.py
setting leoID from os.getenv('USER'): 'bob'

Leo 5.6, build 20171020132815, Fri, Oct 20, 2017  1:28:15 PM
Git repo info: branch = master, commit = e996713191de
Python 2.7.12, LeoGui: dummy version
linux2
** isPython3: False
** caching enabled

reading settings in /pri/git/leo_bug_demos/no_cacher/no_cacher.leo
wrote recent file: /home/bob/.leo/.leoRecentFiles.txt
Traceback (most recent call last):
  File "no_cacher.py", line 33, in <module>
    main()
  File "no_cacher.py", line 29, in main
    cmdrIn.close()
  File "/pri/git/leo-editor/leo/core/leoCommands.py", line 2103, in close
    g.app.closeLeoWindow(self.frame, new_c=new_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 964, in closeLeoWindow
    g.app.finishQuit()
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1193, in finishQuit
    g.app.cacher.commit()
AttributeError: 'LeoApp' object has no attribute 'cacher'
2017-10-21 16:11:00 /pri/git/leo_bug_demos/no_cacher

$ python3 no_cacher.py
setting leoID from os.getenv('USER'): 'bob'

Leo 5.6, build 20171020132815, Fri, Oct 20, 2017  1:28:15 PM
Git repo info: branch = master, commit = e996713191de
Python 3.5.2, LeoGui: dummy version
linux
** isPython3: True
** caching enabled

reading settings in /pri/git/leo_bug_demos/no_cacher/no_cacher.leo
wrote recent file: /home/bob/.leo/.leoRecentFiles.txt
Traceback (most recent call last):
  File "no_cacher.py", line 33, in <module>
    main()
  File "no_cacher.py", line 29, in main
    cmdrIn.close()
  File "/pri/git/leo-editor/leo/core/leoCommands.py", line 2103, in close
    g.app.closeLeoWindow(self.frame, new_c=new_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 964, in closeLeoWindow
    g.app.finishQuit()
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1193, in finishQuit
    g.app.cacher.commit()
AttributeError: 'LeoApp' object has no attribute 'cacher'
2017-10-21 16:11:44 /pri/git/leo_bug_demos/no_cacher

**Comment by SegundoBob** [comment]
Fix confirmed.
