### ISSUE TITLE
Hyperlink click does not launch the page

### ISSUE THREAD

**Issue by satishgoda** [leo-editor/leo-editor#571]
## Runtime Environment Info

```
Leo 5.6, build 20170925164553, Mon Sep 25 16:45:53 CDT 2017
pyqt-4.11.4.1
python-2.7.3.40
qt-4.8.5
```

## The Problem

The body of my outline node contains the following code

```
@language rest

http://leoeditor.com/running.html
```

When I view the page via vr command and click the link, I get the following error (on Linux and Windows respectively)

## Linux

```python
Traceback (most recent call last):

  File "/work/td/tools/leo/5.6/Leo-5.6/leo/core/leoGlobals.py", line 6999, in openUrlOnClick
    return openUrlHelper(event, url)

  File "/work/td/tools/leo/5.6/Leo-5.6/leo/core/leoGlobals.py", line 7042, in openUrlHelper
    if url and g.isValidUrl(url):

  File "/work/td/tools/leo/5.6/Leo-5.6/leo/core/leoGlobals.py", line 6967, in isValidUrl
    if url.lower().startswith('unl:' + '//') or url.startswith('#'):

AttributeError: 'QString' object has no attribute 'lower'
```

## Windows

```python
Traceback (most recent call last):

  File "leo\core\leoGlobals.py", line 6999, in openUrlOnClick

  File "leo\core\leoGlobals.py", line 7042, in openUrlHelper

  File "leo\core\leoGlobals.py", line 6967, in isValidUrl

AttributeError: 'QString' object has no attribute 'lower'
```

**Comment by edreamleo** [comment]
This only happens when clicking the link in the VR pane, and only with Python 2.
