### ISSUE TITLE
cft error

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#627]
The clone-find-tag command (cft) generates this error message after typing in a tag that I know exists:

Traceback (most recent call last):

  File "D:\Synced\github repos\leo\leo\plugins\qt_events.py", line 131, in eventFilter
    k.masterKeyHandler(event)

  File "D:\Synced\github repos\leo\leo\core\leoKeys.py", line 3315, in masterKeyHandler
    done = k.doMode(event, state, stroke)

  File "D:\Synced\github repos\leo\leo\core\leoKeys.py", line 3398, in doMode
    k.getArg(event, stroke=stroke)

  File "D:\Synced\github repos\leo\leo\core\leoKeys.py", line 3015, in getArg
    tabList, completion, oneCharacter, stroke, useMinibuffer)

  File "D:\Synced\github repos\leo\leo\core\leoKeys.py", line 1444, in get_arg
    ga.do_end(event, char, stroke)

  File "D:\Synced\github repos\leo\leo\core\leoKeys.py", line 1501, in do_end
    handler(event)

  File "D:\Synced\github repos\leo\leo\core\leoFind.py", line 880, in minibufferCloneFindTag1
    self.cloneFindTag(k.arg)

  File "D:\Synced\github repos\leo\leo\core\leoFind.py", line 1514, in cloneFindTag
    found = self.createCloneTagNodes(clones)

  File "D:\Synced\github repos\leo\leo\core\leoFind.py", line 1539, in createCloneTagNodes
    p2 = p.copy()

AttributeError: 'VNodeBase' object has no attribute 'copy'

**Comment by edreamleo** [comment]
On Wed, Dec 6, 2017 at 11:06 AM, Rob Keeney <notifications@github.com>
wrote:

> The clone-find-tag command (cft) generates this error message after typing
> in a tag that I know exists:
>
​Fixed at ​5b06ee1, including several tricky changes to nodetags.py.

The nodetags changes guarantee that most args to most methods are
positions, not a wretched mix of positions and vnodes.

I've tested these nodetags changes as thoroughly as I know how.  Please
report any problems.

Edward

**Comment by largo84** [comment]
Right-click is supposed to delete a tag from the selected node. This no longer works after this change.

**Comment by edreamleo** [comment]
Fixed at a78a638.
