### ISSUE TITLE
Javascript importer crashes on jqterm.js

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#653]
The initial report is [here](https://groups.google.com/d/msg/leo-editor/xyO4LQHrAWQ/vsxVX60DAQAJ). The jqterm.js file can be found [here](https://raw.githubusercontent.com/jcubic/jquery.terminal/master/js/jquery.terminal.js).

Running `leo jsimport-example.leo --no-cache` crashes as follows:

```
Traceback (most recent call last):

  File "c:\leo.repo\leo-editor\leo\core\leoApp.py", line 1483, in scanner_for_ext_cb
    return scanner.run(s, parent)

  File "c:\leo.repo\leo-editor\leo\plugins\importers\linescanner.py", line 463, in run
    self.generate_nodes(s, parent)

  File "c:\leo.repo\leo-editor\leo\plugins\importers\linescanner.py", line 530, in generate_nodes
    self.gen_lines(s, parent)

  File "c:\leo.repo\leo-editor\leo\plugins\importers\linescanner.py", line 599, in gen_lines
    tail_p = self.end_block(line, new_state, stack)

  File "c:\leo.repo\leo-editor\leo\plugins\importers\linescanner.py", line 649, in end_block
    self.cut_stack(new_state, stack)

  File "c:\leo.repo\leo-editor\leo\plugins\importers\linescanner.py", line 626, in cut_stack
    assert len(stack) > 1, stack # <

AssertionError: [Target: JS_ScanState context: '' curlies: 0 parens: 0 @others: 1 refs: 0 p: @auto jqterm.js]
```

**Comment by edreamleo** [comment]
Recent revs add error recovery to i.cut_stack.  With this recovery in place, jqterm.js imports perfectly, albeit with a log message from i.cut_stack.

Furthermore, js_i.clean_headline now does a better job of cleaning function headlines.
