### ISSUE TITLE
sqlite3.ProgrammingError: Cannot operate on a closed database.

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#658]
# First Problem: sqlite3.ProgrammingError: Cannot operate on a closed # database.
This is another leoBridge problem and it repeats reliably.  To show the problem run the test Python script [opOnClosedSqlite3.py](https://gist.github.com/SegundoBob/d595717a433276164e8846b641b16a1f#file-oponclosedsqlite3-py).

# Second Problem: Internal Leo error in check_gnx
Script opOnClosedSqlite3.py also shows a second problem:
```
Internal Leo error in check_gnx
getNewIndex: gnx clash bob.20180125143918.2: v: <VNode 7f99af4160f0 newHeadline> v2: <VNode 7f99af40f710 NewHeadline>
Called from <module>, main, insertAfter, __init__, new_vnode_helper, getNewIndex
Please report this error to Leo's developers
```
This second problem is reported at the beginning of the second run of opOnClosedSqlite3.py in the test procedure.

## Test Procedure
You can execute opOnClosedSqlite3.py with either Python2 or Python3.  They both produce the same results.

opOnClosedSqlite3.py creates two files in the same directory in which it exists:  bugdemo00.leo and bugdemo01.leo.  If they already exist, it reuses them.

The first time you run opOnClosedSqlite3.py files  bugdemo00.leo and bugdemo01.leo should not exist.  The second time you run opOnClosedSqlite3.py they should exist.  You can do the two runs in rapid succession or with a long pause between the runs.  The results are the same:
```
2018-01-25 14:32:51 /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3
$ python3 opOnClosedSqlite3.py
Traceback (most recent call last):
  File "opOnClosedSqlite3.py", line 23, in <module>
    main()
  File "opOnClosedSqlite3.py", line 20, in main
    cmdrX.close()
  File "/pri/git/leo-editor/leo/commands/commanderFileCommands.py", line 51, in close
    g.app.closeLeoWindow(self.frame, new_c=new_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1277, in closeLeoWindow
    g.app.forgetOpenFile(fn=c.fileName(), force=True)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1398, in forgetOpenFile
    aList = d.get(tag) or []
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 934, in get
    if not self.has_key(key):return default
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 945, in has_key
    for row in self.conn.execute(sql, (key,)):
sqlite3.ProgrammingError: Cannot operate on a closed database.
2018-01-25 14:39:08 /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3
$ python3 opOnClosedSqlite3.py

Internal Leo error in check_gnx
getNewIndex: gnx clash bob.20180125143918.2: v: <VNode 7f99af4160f0 newHeadline> v2: <VNode 7f99af40f710 NewHeadline>
Called from <module>, main, insertAfter, __init__, new_vnode_helper, getNewIndex
Please report this error to Leo's developers
Traceback (most recent call last):
  File "opOnClosedSqlite3.py", line 23, in <module>
    main()
  File "opOnClosedSqlite3.py", line 13, in main
    cmdrX = bridge.openLeoFile('bugdemo{0:02d}.leo'.format(fidx))
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 259, in openLeoFile
    c = self.createFrame(fileName)
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 293, in createFrame
    c = g.openWithFileName(fileName)
  File "/pri/git/leo-editor/leo/core/leoGlobals.py", line 3318, in openWithFileName
    return g.app.loadManager.loadLocalFile(fileName, gui, old_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 3058, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 3099, in openFileByName
    ok = lm.readOpenedLeoFile(c, fn, readAtFileNodesFlag, theFile)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 3274, in readOpenedLeoFile
    readAtFileNodesFlag=readAtFileNodesFlag)
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 843, in openLeoFile
    silent=silent,
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 658, in getLeoFile
    g.app.checkForOpenFile(c, fileName)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1376, in checkForOpenFile
    aList = g.app.db.get(tag) or []
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 934, in get
    if not self.has_key(key):return default
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 945, in has_key
    for row in self.conn.execute(sql, (key,)):
sqlite3.ProgrammingError: Cannot operate on a closed database.
2018-01-25 14:39:18 /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3
```

# Test System
The test results were the same for the Leo-Editor version I happened to be using and for the latest Leo-Editor version:
**Latest**
```
Leo Log Window
Leo 5.6, build 20180125132834, Thu Jan 25 13:28:34 CST 2018
Git repo info: branch = master, commit = 269041ff1398
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True
caching enabled
```

**Earlier**
```
Leo Log Window
Leo 5.6, build 20171117105807, Fri Nov 17 10:58:07 CST 2017
Git repo info: branch = master, commit = cf2f7e2e5715
Python 3.5.2, PyQt version 5.5.1
linux
isPython3: True
caching enabled
```

**Comment by edreamleo** [comment]
Thanks for this detailed report.  It should greatly help the author of this plugin.

**Comment by vitalije** [comment]
### Regarding the first error (operating on closed connection)
when you close controller created by the leoBridge module, it closes also global application instance. In other words, if you want to use bridge several times for opening different files, you should not close any of them until you have finished all the work. After that, it should be enough to call close method on the last used commander.

The other possibility is to use:
```python
g.app.closeLeoWindow(cmdrX.frame, finish_quit=False)
```
instead of
```python
cmdrX.close()
```

### Regarding the other problem (gnx clash)
It requires further investigation. I suspect it too has something to do with difference in initialization procedure when using leoBridge.

**Comment by vitalije** [comment]
I have just saw recently added comment
```python
# Careful: this test is no longer guaranteed.
if p.v.context == c:
```
in leoGlobals module. I don't know why is this now not guaranteed, but I do know that computing proper gnx depends on it. So `if p.v.context != c` it means that it is likely to have gnx clash.

This change is dated Jan 24 2018, but my Leo hasn't been updated since Jan 17 2018, so it seems the problem existed even before.

**Comment by edreamleo** [comment]
On Fri, Jan 26, 2018 at 4:20 AM, Виталије Милошевић <
notifications@github.com> wrote:

> I have just saw recently added comment
>
> # Careful: this test is no longer guaranteed.
> ​​
> if p.v.context == c:
>
> in leoGlobals module. I don't know why is this now not guaranteed, but I
> do know that computing proper gnx depends on it. So if p.v.context != c
> it means that it is likely to have gnx clash.
>
​It's no longer guaranteed because common @button nodes pass (store) a
position in myLeoSettings.leo that are then used in other .leo files.

This guard only occurs in g.handleScriptException, so in normal operation
nothing bad is ever going to happen.  It is needed because the guarded
text, c.goToScriptLineNumber(n, p), will fail in c.redraw otherwise.

The assert in c.redraw is pretty stupid. The assert should probably be
changed into a test and warning.

> This change is dated Jan 24 2018, but my Leo hasn't been updated since Jan
> 17 2018, so it seems the problem existed even before.
>
​No. The violation of the test is something brand new :-)

Edward

**Comment by edreamleo** [comment]
I just realized that the new code might be confusing you:

    if p.v.context == c:
        try:
            c.goToScriptLineNumber(n, p)
            << dump the lines near the error >>
        except Exception:
            g.es_print('Unexpected exception in g.handleScriptException')
            g.es_exception()

The previous code was just:

    c.goToScriptLineNumber(n, p)
    << dump the lines near the error >>

For safety, the code should always have been:

    try:
        c.goToScriptLineNumber(n, p)
        << dump the lines near the error >>
    except Exception:
        g.es_print('Unexpected exception in g.handleScriptException')
        g.es_exception()

The actual new code suppresses the "Unexpected exception" message when in fact we expect it.  It's kinda like wearing both braces and a belt ;-) HTH.

**Comment by SegundoBob** [comment]
On 01/26/2018 02:11 AM, Виталије Милошевић wrote:
> 
>       Regarding the first error (operating on closed connection)
> 
> when you close controller created by the leoBridge module, it closes
> also global application instance. In other words, if you want to use
> bridge several times for opening different files, you should not close
> any of them until you have finished all the work. After that, it should
> be enough to call close method on the last used commander.
> 
> The other possibility is to use:
> 
> g.app.closeLeoWindow(cmdrX.frame, finish_quit=False)
> 
> instead of
> 
> cmdrX.close()

vitalije,

Thanks for quickly looking at the problem.

Edward K. Ream,

Are these finicky, non-intuitive restrictions necessary?  Ideally
leoBridge would be easy to use.

Closing a file as soon as it is no longer needed is good programming
practice.  If a script needs to open a large number of files, it may be
necessary to close a file before the script is finished.

Perhaps, cmdr.close() should not close the global application instance?
I confess that I don't know what "close the global application instance"
means.  My guess is that it means the leoBridge object. If so, this
behavior is very objectionable.  Closing a commander created by a
leoBridge object, should not close the leoBridge object.

If this strange behavior can't be eliminated, could the "finish_quit"
optional argument be added to cmdr.close().  The restriction that you
must call cmdr.close(finish_quit=False) instead of cmdr.close() is
slightly better than you must call g.app.closeLeoWindow(cmdr.frame,
finish_quit=False).

Hopefully, job termination can be trusted to "close the application" and
it is not necessary to explicitly call cmdr.close(finish_quit=True) for
the last commander closed?

-- 
Segundo Bob
SegundoBob@gmail.com

**Comment by edreamleo** [comment]
On Fri, Jan 26, 2018 at 1:45 PM, SegundoBob <notifications@github.com>
wrote:

On 01/26/2018 02:11 AM, Виталије Милошевић wrote:
> >
> > Regarding the first error (operating on closed connection)
> >
> > when you close controller created by the leoBridge module, it closes
> > also global application instance. In other words, if you want to use
> > bridge several times for opening different files, you should not close
> > any of them until you have finished all the work.

​[snip]

​[@]​
> ​ ​
> Edward K. Ream,
>
> Are these finicky, non-intuitive restrictions necessary? Ideally
> leoBridge would be easy to use.
>

​The bridge controller is a thin wrapper around the Leo app, that is, the
LeoApp class. When closing the last commander, the LeoApp ​class naturally
shuts down. Imo, this is completely intuitive behavior.

The following illustrates that it is possible to open several files at once
in a single run:

import leo.core.leoBridge as leoBridge
bridge = leoBridge.controller(gui='nullGui',silent=True,verbose=False)
assert bridge.isOpen()
g = bridge.globals()
path = g.os_path_abspath(g.os_path_join(
    g.app.loadDir,'..','test','unitTest.leo'))
assert g.os_path_exists(path), repr(path)
c = bridge.openLeoFile(path)
assert c
print('c:', c.shortFileName())
c2 = c.new()
print('c2:', c2)
c.close()
print('after c close')
c2.close()
print('after c2 close')

The output, as expected is:

c:\Test>python3 bridge_closing_test.py
c: unitTest.leo
c2: Commander 127939248: ''
after c close
after c2 close

Edward

**Comment by SegundoBob** [comment]
# Both Problems Continue to occur after test modified to comply with "Last commander close also closes LeoBridge"

[new test script](https://gist.github.com/SegundoBob/32fb5d176637c24503aab083671c2531)

I also changed the LeoBridge argument "silent" to false and added some prints to make clear when the various errors occur.

There are two separate bugs here.  The files created by the first run are fine.  The error message 

> Internal Leo error in check_gnx

is probably erroneous.

# Console Contents after Two Runs
```
$ 
2018-01-27 11:17:12 /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3
$ ./opOnClosedSqlite3.py
setting leoID from os.getenv('USER'): 'bob'

Leo 5.6, build 20180125132834, Thu Jan 25 13:28:34 CST 2018
Git repo info: branch = master, commit = 269041ff1398
Python 2.7.12, LeoGui: dummy version
linux2
** isPython3: False
** caching enabled

Opening bugdemo00.leo
file not found: /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo00.leo. creating new window
wrote recent file: /home/bob/.leo/.leoRecentFiles.txt
Opening bugdemo01.leo
file not found: /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo01.leo. creating new window
Opening bugdemo02.leo
file not found: /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo02.leo. creating new window
closing commander Commander 139989898505872: u'/pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo00.leo'
closing commander Commander 139989788879248: u'/pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo01.leo'
Traceback (most recent call last):
  File "./opOnClosedSqlite3.py", line 27, in <module>
    main()
  File "./opOnClosedSqlite3.py", line 24, in main
    cmdrX.close()
  File "/pri/git/leo-editor/leo/commands/commanderFileCommands.py", line 51, in close
    g.app.closeLeoWindow(self.frame, new_c=new_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1277, in closeLeoWindow
    g.app.forgetOpenFile(fn=c.fileName(), force=True)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1398, in forgetOpenFile
    aList = d.get(tag) or []
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 934, in get
    if not self.has_key(key):return default
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 945, in has_key
    for row in self.conn.execute(sql, (key,)):
sqlite3.ProgrammingError: Cannot operate on a closed database.
2018-01-27 11:17:34 /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3
$ ./opOnClosedSqlite3.py
setting leoID from os.getenv('USER'): 'bob'

Leo 5.6, build 20180125132834, Thu Jan 25 13:28:34 CST 2018
Git repo info: branch = master, commit = 269041ff1398
Python 2.7.12, LeoGui: dummy version
linux2
** isPython3: False
** caching enabled

Opening bugdemo00.leo
reading settings in /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo00.leo

Internal Leo error in check_gnx
getNewIndex: gnx clash bob.20180127111740.2: v: <VNode 7f4cf0e5df90 newHeadline> v2: <VNode 7f4cf0e5d410 NewHeadline>
Called from <module>, main, insertAfter, __init__, new_vnode_helper, getNewIndex
Please report this error to Leo's developers
wrote recent file: /home/bob/.leo/.leoRecentFiles.txt
Opening bugdemo01.leo
reading settings in /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo01.leo
Opening bugdemo02.leo
reading settings in /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo02.leo
closing commander Commander 139968435689680: u'/pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo00.leo'
closing commander Commander 139968431101072: u'/pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3/bugdemo01.leo'
Traceback (most recent call last):
  File "./opOnClosedSqlite3.py", line 27, in <module>
    main()
  File "./opOnClosedSqlite3.py", line 24, in main
    cmdrX.close()
  File "/pri/git/leo-editor/leo/commands/commanderFileCommands.py", line 51, in close
    g.app.closeLeoWindow(self.frame, new_c=new_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1277, in closeLeoWindow
    g.app.forgetOpenFile(fn=c.fileName(), force=True)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 1398, in forgetOpenFile
    aList = d.get(tag) or []
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 934, in get
    if not self.has_key(key):return default
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 945, in has_key
    for row in self.conn.execute(sql, (key,)):
sqlite3.ProgrammingError: Cannot operate on a closed database.
2018-01-27 11:17:41 /pri/git/leo_bug_demos/2018-01-25-leoBridge-Closed-sqlite3
$ 
```

**Comment by edreamleo** [comment]
On Sat, Jan 27, 2018 at 1:25 PM, SegundoBob <notifications@github.com>
wrote:

> Both Problems Continue to occur
> ​...
>
​In future, please don't use markdown # labels in responses.  In my email
reader it looks like you are shouting :-)

Rev 2465623 appears to fix the duplicate gnx problem.  opOnCloseSqlight3.py
no longer reports duplicate gnx's, though the sqlite3 problem persists.

The fix was to ni.compute_last_index.  It no longer sets ​self.last_index
back to zero.  I think this is sound and all unit tests pass.  However, the
code is subtle. It would be good, Bob, if you ran as many tests as you can
on your end.

Edward

**Comment by vitalije** [comment]
After calling `cmdrX.close` method. global cacher backend instance (`g.app.db`) is closed also. Trying to use bridge after that leads to this error.

I am not sure what commander.close() method should do. If you are concerned with the file being left open, I believe it is not a problem. File is opened, read, and closed before bridge.openLeoFile returns. 

While experimenting with this script, I was very surprised that it cleared my 'recent files' list. I believe that bridge should not touch neither recent files, nor to count files as already open. All this happens when we call commander.close method. 

For now, my advice is just to skip call to cmdrX.close(). I don't expect anything bad to happen if you just skip it.

**Comment by SegundoBob** [comment]
On 01/28/2018 02:37 AM, Edward K. Ream wrote:
> Rev 2465623 appears to fix the duplicate gnx problem. opOnCloseSqlight3.py
> no longer reports duplicate gnx's,

Using

Leo 5.7b1, build 20180128113157, Sun Jan 28 11:31:57 CST 2018
Git repo info: branch = master, commit = cad1766aa32f

I confirmed that opOnCloseSqlight3.py no longer reports duplicate gnx's.


-- 
Segundo Bob
SegundoBob@gmail.com

**Comment by SegundoBob** [comment]
On 01/28/2018 02:37 AM, Edward K. Ream wrote:
> It would be good, Bob, if you ran as many tests as you can
> on your end.

I ran opOnCloseSqlight3.py.  I ran my script that demonstrated issue
#35.  I ran your script that demonstrated issue #35. I don't have any
other tests or relevant ideas.  The gnx problem shown by
opOnCloseSqlight3.py showed up unexpectedly, not based on any ideas
about gnx's.

If I have any ideas about gnx testing, I'll try them, but this is
unlikely.  I have too many other things to think about.
-- 
Segundo Bob
SegundoBob@gmail.com

**Comment by SegundoBob** [comment]
On 01/28/2018 03:57 AM, Виталије Милошевић wrote:
> For now, my advice is just to skip call to cmdrX.close().

"For now"?  Does this mean that you expect cmdr.close() to eventually be
fixed?

"For now" we have the strange restriction: When using, LeoBridge, never
call cmdr.close() for the last open commander.

I confirm that taking out all the cmdr.close() calls from
opOnClosedSqlite3.py allows it to run without reported error after
Edward's fix to the gnx problem.

I would not be surprised if during process termination, the errors are
occurring, but are not reported.

-- 
Segundo Bob
SegundoBob@gmail.com

**Comment by vitalije** [comment]
By "for now" I meant to say that this issue could be very easily fixed by inserting a few checks in closing process to see if Leo is in bridge and if so, then change behavior to avoid this issue. This check can be placed in several places and question is what would be the best?

However, I don't think it would be wise to fix this issue before we have a good insight in what is really necessary for normal usage. I doubt that calling close method is necessary at all. It may look like a proper thing to do, but I really can't imagine any problem in skipping this call. I expect that commander created using bridge.openLeoFile method are ordinary Python objects, AFAIK they do not hold any reference to some system resource that need to be freed and therefore they would be garbage collected by Python when they get out of scope. A sqlite3.Connection objects are automatically closed  too when they get garbage collected. So, unless otherwise proved as a bad practice I would strongly advice every user not to call close method at all.

> When using, LeoBridge, nevercall cmdr.close() for the last open commander.
No, this is not true. The restriction would be not to call `cmdr.close()` before you have finished using bridge, and when you have finished with bridge then call close method just once on any cmdr.

**Comment by edreamleo** [comment]
I am going to close this issue, for the following reasons:

- SegundoBob confirms that Leo no longer generates duplicate gnx's.
- The LeoBridge.initLeo method is a slight variation on Leo's startup code. It would not be wise for the leoBridge module to change Leo's behavior in any great way.  Doing so might break existing leoBridge scripts.
- There are easy workarounds to avoid prematurely closing the BridgeController instance.

**Comment by edreamleo** [comment]
On Sun, Jan 28, 2018 at 5:01 PM, SegundoBob <notifications@github.com>
wrote:

> On 01/28/2018 02:37 AM, Edward K. Ream wrote:
> > Rev 2465623 appears to fix the duplicate gnx problem.
> opOnCloseSqlight3.py
> > no longer reports duplicate gnx's,
>
> Using
>
> Leo 5.7b1, build 20180128113157, Sun Jan 28 11:31:57 CST 2018
> Git repo info: branch = master, commit = cad1766aa32f
>
> I confirmed that opOnCloseSqlight3.py no longer reports duplicate gnx's.
>

​Thanks for the confirmation.

I have just closed #658
<https://github.com/leo-editor/leo-editor/issues/658>, for the reasons
given in the last comment.

Edward

**Comment by edreamleo** [comment]
On Sun, Jan 28, 2018 at 5:16 PM, SegundoBob <notifications@github.com>
wrote:

I confirm that taking out all the cmdr.close() calls from
> opOnClosedSqlite3.py allows it to run without reported error after
> Edward's fix to the gnx problem.
>

​Thanks for this confirmation.​


​Edward

**Comment by SegundoBob** [comment]
### Origin of Test Program

I was trying to write a simple  program to reproduce the "Phantom NewHeadline" possible bug, when I re-encountered this bug which seriously handicaps my investigations of the "Phantom NewHeadline" problem.

Using one LeoBridge instance, I wanted a loop containing:

1. Open a Leo-Editor file, creating it.
2. Close the Leo-Editor file.
3. Open the Leo-Editor file.
4. Check the Leo-Editor file.
5. Close the Leo-Editor file.
6. Delete the Leo-Editor file.

But at step 3 this encountered issue #658 every time.

Edward suggested that #658 might be avoidable by for each LeoBridge instance, always keeping at least one open commander.  So I tried that, and it doesn't help.

Test Description [issue658_open_commander.py](https://gist.github.com/SegundoBob/d631fb1fd7fba31d12050b1c3eb22370)

This test uses one LeoBridge instance to open test1.leo and it never closes test1.leo.  It then opens tst2.leo, closes, test2.leo, and tries to open test2.leo, at which point it encounters #658.

The bug occurs every time closed_database.py is run.

The bug always occurs on the second "cmdrT = bridge.openLeoFile(str(leoPfn))".  It doesn't matter if the test file test.leo exists or doesn't exist before closed_database.py is run.

Sample Test Run Output:
```
2019-09-21 13:45:34 /pri/git/leo_bug_demos/2019-09-21-closed-database
$ ./issue658_open_commander.py
Leo 6.1-devel, devel branch, build c4c440a639
2019-09-21 02:12:34 -0500

Traceback (most recent call last):
  File "./issue658_open_commander.py", line 48, in <module>
    main()
  File "./issue658_open_commander.py", line 44, in main
    cmdr2 = bridge.openLeoFile(str(leoPfn2))
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 261, in openLeoFile
    c = self.createFrame(fileName)
  File "/pri/git/leo-editor/leo/core/leoBridge.py", line 291, in createFrame
    c = g.openWithFileName(fileName)
  File "/pri/git/leo-editor/leo/core/leoGlobals.py", line 3874, in openWithFileName
    return g.app.loadManager.loadLocalFile(fileName, gui, old_c)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 3259, in loadLocalFile
    previousSettings = lm.getPreviousSettings(fn)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 2233, in getPreviousSettings
    c = lm.openSettingsFile(fn)
  File "/pri/git/leo-editor/leo/core/leoApp.py", line 2399, in openSettingsFile
    readAtFileNodesFlag=False, silent=True)
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 701, in openLeoFile
    silent=silent,
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 564, in getLeoFile
    v = FastRead(c, self.gnxDict).readFile(fileName)
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 61, in readFile
    v, g_element = self.readWithElementTree(path, s)
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 112, in readWithElementTree
    self.handleBits()
  File "/pri/git/leo-editor/leo/core/leoFileCommands.py", line 118, in handleBits
    expanded = c.db.get('expanded')
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 114, in get
    value = self.db.get(f"{self.key}:::{key}")
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 604, in get
    if not self.has_key(key):
  File "/pri/git/leo-editor/leo/core/leoCache.py", line 614, in has_key
    for row in self.conn.execute(sql, (key,)):
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

Test System:
```
Leo 6.1-devel, devel branch, build c4c440a639
2019-09-21 02:12:34 -0500
```

**Comment by vitalije** [comment]
Here is what you can do to avoid triggering #658
insert an import statement:`import leo.core.leoCache as leoCache`
```
# after closing cmdr1
cmdr1.close()
bridge.g.app.global_cacher = leoCache.GlobalCacher()
bridge.g.app.db = bridge.g.app.global_cacher.db
cmdr2 = bridge.openLeoFile(...)
```
This will reopen global db object which was closed during `cmdr1.close()` operation.

HTH Vitalije

**Comment by SegundoBob** [comment]
Vitalije,

Thanks. I'll certainly try your suggestion in my own programs when necessary, but I hope not to use it in issue report programs.  A symptom that occurs after working around a bug is too easy to dismiss.

SegundoBob

**Comment by vitalije** [comment]
65ca5ec should solve this issue. leoBridge is changed so that before opening new Leo document it checks if the global and commander cachers are still open and if not reopens them.

HTH
