### ISSUE TITLE
setup.py broken git_version() when tag isn't a number

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#691]
```
(leo-git) C:\Users\mattw\code\leo-editor
>pip install -e .
Obtaining file:///C:/Users/mattw/code/leo-editor
    Complete output from command python setup.py egg_info:
    Removing build and dist directories
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mattw\code\leo-editor\setup.py", line 101, in <module>
        version=git_version(),
      File "C:\Users\mattw\code\leo-editor\setup.py", line 35, in git_version
        minor = int(minor) + 1
    ValueError: invalid literal for int() with base 10: '7b1'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\mattw\code\leo-editor\
```

**Comment by edreamleo** [comment]
@maphew Again, I'll fix this immediately.  If fixing the crash is all that is wanted I'll change the milestone to 5.7.

**Comment by maphew** [comment]
@edreamleo I'm most of the way there, see latest commit, but have run out of time for today. Mostly just clean up of old approach now.

**Comment by maphew** [comment]
Believe to be fixed. Please re-open if any problems found
