### ISSUE TITLE
Leo fails to load when pyenchant is not installed

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#707]
From Lewis Neal: I changed to default leoSettings.leo to eliminate any personal settings, but Leo still did not load unless pyenchant was installed.

```N:\git\leo-editor>launchleo.py

reading settings in N:\git\leo-editor\leo\config\leoSettings.leo
reading settings in C:\Users\lewis\.leo\myLeoSettings.leo
Empty setting name in False
set parent @settings

Leo 5.7b1, build 20180205170654, Mon Feb  5 17:06:54 CST 2018
Git repo info: branch = master, commit = c8e13c3bccdc
Python 3.6.4, PyQt version 5.10.0
Windows 10 AMD64 (build 10.0.16299) SP0
** isPython3: True
** caching enabled

reading settings in C:\Users\lewis\.leo\workbook.leo
Traceback (most recent call last):
  File "N:\git\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "N:\git\leo-editor\leo\core\runLeo.py", line 74, in run
    g.app.loadManager.load(fileName, pymacs)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2204, in load
    ok = lm.doPostPluginsInit()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2836, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2897, in openEmptyWorkBook
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3062, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3086, in openFileByName
    previousSettings=previousSettings)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 1543, in newCommander
    return leoCommands.Commands(fileName, relativeFileName, gui, previousSettings)
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 82, in __init__
    c.finishCreate()
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 415, in finishCreate
    c.frame.log.finishCreate()
  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 3146, in finishCreate
    c.spellCommands.openSpellTab()
  File "N:\git\leo-editor\leo\commands\spellCommands.py", line 173, in openSpellTab
    self.handler = SpellTabHandler(c, tabName)
  File "N:\git\leo-editor\leo\commands\spellCommands.py", line 414, in __init__
    self.spellController = EnchantClass(c)
  File "N:\git\leo-editor\leo\commands\spellCommands.py", line 32, in __init__
    if language and not enchant.dict_exists(language):
AttributeError: module 'enchant' has no attribute 'dict_exists'
```

**Comment by LewisNeal** [comment]
Just to clarify: I posted the console errors when myLeoSettings.leo was active.
I later changed to default leoSettings.leo but Leo still did not load.

**Comment by edreamleo** [comment]
@LewisNeal The new code adds a guard to prevent the crash.  However, this is a very strange bug. It may be an installation issue on your end.

**Comment by LewisNeal** [comment]
Strange. I have pyenchant 1.6.6 installed waiting to confirm this fix. 
Now the latest commit ddb87d916eb3 is not loading Leo for me. It's not a complete crash; I have a Leo splash screen but nothing after that.
First, I will uninstall pyenchant and report.

**Comment by edreamleo** [comment]
fc5567a may fix this.  Please reopen if it doesn't.

There are many possible paths through the code.  Reports such as this are important.

**Comment by LewisNeal** [comment]
Fixed.
Leo loads if pyenchant is not installed.

**Comment by edreamleo** [comment]
On Fri, Feb 9, 2018 at 5:37 PM, LewisNeal <notifications@github.com> wrote:

> Fixed.
> Leo loads if pyenchant is not installed.
>

​Thanks for the confirmation.

Edward
