### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#712]
Leo 5.7b1, build 20180209145139, Fri Feb  9 14:51:39 CST 2018
Git repo info: branch = master, commit = ddb87d916eb3
Python 2.7.12, PyQt version 4.8.7
linux2
** isPython3: False
** caching enabled

reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from u"{|{x='__NEXT_PLACEHOLDER'}|}" to u'__NEXT_PLACEHOLDER'
redefining abbreviation ,, 
from u"{|{x='__NEXT_PLACEHOLDER'}|}" to u'__NEXT_PLACEHOLDER'
Traceback (most recent call last):
  File "launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/home/swot/leo-editor/leo/core/runLeo.py", line 74, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/home/swot/leo-editor/leo/core/leoApp.py", line 2206, in load
    ok = lm.doPostPluginsInit()
  File "/home/swot/leo-editor/leo/core/leoApp.py", line 2838, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()
  File "/home/swot/leo-editor/leo/core/leoApp.py", line 2899, in openEmptyWorkBook
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)
  File "/home/swot/leo-editor/leo/core/leoApp.py", line 3064, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "/home/swot/leo-editor/leo/core/leoApp.py", line 3088, in openFileByName
    previousSettings=previousSettings)
  File "/home/swot/leo-editor/leo/core/leoApp.py", line 1545, in newCommander
    return leoCommands.Commands(fileName, relativeFileName, gui, previousSettings)
  File "/home/swot/leo-editor/leo/core/leoCommands.py", line 82, in __init__
    c.finishCreate()
  File "/home/swot/leo-editor/leo/core/leoCommands.py", line 415, in finishCreate
    c.frame.log.finishCreate()
  File "/home/swot/leo-editor/leo/plugins/qt_frame.py", line 3146, in finishCreate
    c.spellCommands.openSpellTab()
  File "/home/swot/leo-editor/leo/commands/spellCommands.py", line 463, in openSpellTab
    self.handler = SpellTabHandler(c, tabName)
  File "/home/swot/leo-editor/leo/commands/spellCommands.py", line 707, in __init__
    self.spellController = DefaultWrapper(c)
  File "/home/swot/leo-editor/leo/commands/spellCommands.py", line 238, in __init__
    words = self.read_words(kind, fn)
  File "/home/swot/leo-editor/leo/commands/spellCommands.py", line 251, in read_words
    with open(fn, 'rb') as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by edreamleo** [comment]
Probably fixed at fc5567a.

**Comment by wangzhaohe** [comment]
Thanks, It has been Fixed!
