### ISSUE TITLE
@command-x = binding crashes Leo on startup

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#718]
Apparently you can't put a @ in a command for a key-binding.

See [this post](https://groups.google.com/forum/#!topic/leo-editor/Xsn1eU_ZNdY) from Chris George.

```
Traceback (most recent call last):
File "/home/chris/leo-editor/leo/core/leoConfig.py", line 2004, in visitNode
return f(p, kind, name, val)
File "/home/chris/leo-editor/leo/core/leoConfig.py", line 696, in doShortcuts
assert g.isShortcutInfo(si), si
AssertionError: None
```

**Comment by edreamleo** [comment]
Rev 4db0907 fixes this.  The checkin log mistaken referenced #717.
