### ISSUE TITLE
type importer;; in a node return error

### ISSUE THREAD

**Issue by wangzhaohe** [leo-editor/leo-editor#725]
Leo Log Window
Leo 5.7b2, build 20180214051836, Wed Feb 14 05:18:36 CST 2018
Git repo info: branch = master, commit = c773e36017a1
Python 2.7.12, PyQt version 4.8.7
linux2
isPython3: False
caching enabled
setting leoID from os.getenv('USER'): 'swot'
load dir: /home/swot/leo-editor/leo/core
global config dir: /home/swot/leo-editor/leo/config
home dir: /home/swot
reading settings in /home/swot/leo-editor/leo/config/leoSettings.leo
reading settings in /home/swot/.leo/myLeoSettings.leo
conflicting key bindings in myLeoSettings.leo
  text BackSpace backward-delete-char
   all BackSpace do-nothing
conflicting key bindings in myLeoSettings.leo
  text Delete delete-char
   all Delete do-nothing
http serving enabled at 127.0.0.1:8130
reading settings in /home/swot/.leo/workbook.leo
redefining abbreviation ,, 
from u"{|{x='__NEXT_PLACEHOLDER'}|}" to u'__NEXT_PLACEHOLDER'
reading: /home/swot/.leo/workbook.leo
read 6 files in 0.38 seconds
read outline in 0.59 seconds

Traceback (most recent call last):

  File "/home/swot/leo-editor/leo/plugins/qt_events.py", line 131, in eventFilter
    k.masterKeyHandler(event)

  File "/home/swot/leo-editor/leo/core/leoKeys.py", line 3332, in masterKeyHandler
    k.handleUnboundKeys(event, char, stroke)

  File "/home/swot/leo-editor/leo/core/leoKeys.py", line 3670, in handleUnboundKeys
    k.masterCommand(event=event, stroke=stroke)

  File "/home/swot/leo-editor/leo/core/leoKeys.py", line 3761, in masterCommand
    expanded = c.abbrevCommands.expandAbbrev(event, stroke)

  File "/home/swot/leo-editor/leo/commands/abbrevCommands.py", line 285, in expandAbbrev
    self.expand_text(w, i, j, val, word, expand_search)

  File "/home/swot/leo-editor/leo/commands/abbrevCommands.py", line 313, in expand_text
    val, do_placeholder = self.make_script_substitutions(i, j, val)

  File "/home/swot/leo-editor/leo/commands/abbrevCommands.py", line 452, in make_script_substitutions
    exec(content, c.abbrev_subst_env, c.abbrev_subst_env)

  File "<string>", line 1, in <module>

  File "<string>", line 205, in long_word

IndexError: string index out of range

**Comment by wangzhaohe** [comment]
Sorry!
I found that I have overrided the default @outline-data tree-abbreviations. It works well now!

**Comment by edreamleo** [comment]
Rev 2798f66 recovers more gracefully from this kind of error.
