### ISSUE TITLE
How to install and run LeoVue

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#735]
LeoVue is Joe Orr's prototype of Leo using vue.js. First announced [here](https://groups.google.com/d/msg/leo-editor/50SZd4136iM/owhCnBqcDAAJ). Joe's [leo-examples page](https://github.com/kaleguy/leo-examples) discusses how to run leovue on a local machine. The git repo is [here](https://github.com/kaleguy/leovue).

I can now successfully build leovue on both Ubuntu and Windows 10. **Note**: Before doing so I simulated a clean install by *uninstalling* java, node.js and a previous copy of leovue.  Uninstalling node.js involved deleting ~AppData/npm and ~AppData/npm-cache.

Here is how to install and run the demo. Note: *installing Java is no longer necessary*.  

**1. install node.js**

On Linux, do the following.  Note the **second** sudo in the curl line!!!

    anywhere>sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
    anywhere>sudo apt-get install nodejs

On Windows, install nodejs from an executable installer.  I used from node-v8.9.4-x64.msi

**2. Install global npm packages**

     anywhere>sudo npm install -g node-gyp@3.6.2

LeoVue requires a web server to run. Either install it on your server or run it locally with http-server:

    anywhere>sudo npm install -g http-server

**3. Download LeoVue itself**

Do the following where you have permissions. say in ~/repo. It will create a leovue folder.

    ~/repo>git clone https://github.com/kaleguy/leovue.git

**4. Install packages within LeoVue**

    leovue>npm install --silent
        # --silent inhibits the spammy dependency tree.

**6. Run leovue**
        
    # serve with hot reload at localhost:8080
    leovue>npm run dev

**Important**: Be sure to allow all in noscript or other ad blocker.

**Note**: `npm run dev` is quite slow. Maybe 20 seconds on a fast machine. Eventually the console should show: `> Listening at http://localhost:8080`

**7. Building the production version**

The following also works (it's quite slow):
        
    # build for production with minification
    leovue>npm run build

    # build for production and view the bundle analyser report
    leovue>npm run build --report

At the end of the build, this message appears:

    Tip: built files are meant to be served over an HTTP server.
    Opening index.html over file:// won't work.

**From tscv11**: The script 'leo4sqlite' is now online using leovue. The syntax highlighting works well.
I'm looking forward to trying some of leovue's more advanced capabilities. The leovue/leo4sqlite demo lives [here](https://tscv11.github.io/leo4sqlite/#/t/23/)

**Comment by edreamleo** [comment]
npm install FAILS. Here is the console log:
```
[a64] c:\leo.repo\leovue>npm install

npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated.
See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> uws@9.14.0 install c:\leo.repo\leovue\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

> java@0.9.0 install c:\leo.repo\leovue\node_modules\java
> node-gyp rebuild

[a64] c:\leo.repo\leovue\node_modules\java>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\edreamleo\.windows-build-tools\python27\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

gyp ERR! cwd c:\leo.repo\leovue\node_modules\java
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

npm WARN leo-vue@1.6.4 No repository field.
npm WARN leo-vue@1.6.4 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\edreamleo\AppData\Roaming\npm-cache\_logs\2018-02-19T05_44_26_172Z-debug.log
```

**Comment by edreamleo** [comment]
I installed Python27 in C:\Users\edreamleo\.windows-build-tools.

Googling "[node-java] Error: not found: javac.exe" yields https://github.com/joeferner/node-java/issues/355

The log:
```
[a64] c:\leo.repo\leovue>npm install

> java@0.9.0 install c:\leo.repo\leovue\node_modules\java
> node-gyp rebuild


[a64] c:\leo.repo\leovue\node_modules\java>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
[node-java] Error: not found: javac.exe
gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\leo.repo\leovue\node_modules\java
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN leo-vue@1.6.4 No repository field.
npm WARN leo-vue@1.6.4 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\edreamleo\AppData\Roaming\npm-cache\_logs\2018-02-19T06_50_06_802Z-debug.log
```

**Comment by edreamleo** [comment]
Here is the latest attempt:
```
[a64] c:\leo.repo\leovue>npm install node-java --save
npm WARN leo-vue@1.6.4 No repository field.
npm WARN leo-vue@1.6.4 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ node-java@1.0.1
updated 1 package in 10.516s

[a64] c:\leo.repo\leovue>npm install

> java@0.9.0 install c:\leo.repo\leovue\node_modules\java
> node-gyp rebuild


[a64] c:\leo.repo\leovue\node_modules\java>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
c:\leo.repo\leovue\node_modules\java\src\javaScope.h(5): fatal error C1083: Cannot open include file: 'jni.h': No such
file or directory (compiling source file ..\src\javaScope.cpp) [c:\leo.repo\leovue\node_modules\java\build\nodejavabrid
ge_bindings.vcxproj]
  nodeJavaBridge.cpp
c:\leo.repo\leovue\node_modules\java\src\utils.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file
 or directory (compiling source file ..\src\methodCallBaton.cpp) [c:\leo.repo\leovue\node_modules\java\build\nodejavabr
idge_bindings.vcxproj]
  utils.cpp
c:\leo.repo\leovue\node_modules\java\src\java.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file
or directory (compiling source file ..\src\java.cpp) [c:\leo.repo\leovue\node_modules\java\build\nodejavabridge_binding
s.vcxproj]
c:\leo.repo\leovue\node_modules\java\src\javaObject.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such
 file or directory (compiling source file ..\src\javaObject.cpp) [c:\leo.repo\leovue\node_modules\java\build\nodejavabr
idge_bindings.vcxproj]
  win_delay_load_hook.cc
c:\leo.repo\leovue\node_modules\java\src\java.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file
or directory (compiling source file ..\src\nodeJavaBridge.cpp) [c:\leo.repo\leovue\node_modules\java\build\nodejavabrid
ge_bindings.vcxproj]
c:\leo.repo\leovue\node_modules\java\src\utils.h(7): fatal error C1083: Cannot open include file: 'jni.h': No such file
 or directory (compiling source file ..\src\utils.cpp) [c:\leo.repo\leovue\node_modules\java\build\nodejavabridge_bindi
ngs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\leo.repo\leovue\node_modules\java
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN rollback Rolling back ajv@4.11.8 failed (this is probably harmless): EPERM: operation not permitted, lstat 'c:\leo.repo\leovue\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back tar-pack@3.4.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'c:\leo.repo\leovue\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back readable-stream@2.2.9 failed (this is probably harmless): EPERM: operation not permitted, lstat 'c:\leo.repo\leovue\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back node-pre-gyp@0.6.39 failed (this is probably harmless): EPERM: operation not permitted, lstat 'c:\leo.repo\leovue\node_modules\fsevents\node_modules'
npm WARN leo-vue@1.6.4 No repository field.
npm WARN leo-vue@1.6.4 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\edreamleo\AppData\Roaming\npm-cache\_logs\2018-02-19T07_22_15_426Z-debug.log
```

**Comment by tscv11** [comment]
I, too have run into a problem with leovue. See below for the command and the error it elicited.
(Everything appears to be installed,  including the java jdk).

tsc-Lenovo$ leovue # npm install --silent
[node-java]$ Error: not found: javac
gyp: Call to 'node findJavaHome.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

I hope that helps.

**Comment by edreamleo** [comment]
@tscv11 Note the following comment above:

Googling "[node-java] Error: not found: javac.exe" yields joeferner/node-java#355

**Comment by tscv11** [comment]
> Googling "[node-java] Error: not found: javac.exe" yields
> joeferner/node-java#355

Unfortunately I forgot to mention that I'm using linux, not windows.
Also, I did google it but only the "not found: javac.exe" part -
apparently that wasn't specific enough - sorry.

-- 

Thanks,

tscv11

**Comment by edreamleo** [comment]
@tscv11 Please see the first comment of this item for a summary of how to install on Linux.  It works for me.

Please note: LeoVue also requires java.  I uses apt-get to install a jdk, don't remember the details. `javac --version` gives  1.8.0_151

HTH.

**Comment by edreamleo** [comment]
On Wed, Feb 28, 2018 at 6:11 AM, tscv11 <notifications@github.com> wrote:

> > Googling "[node-java] Error: not found: javac.exe" yields
> > joeferner/node-java#355
>

​I have just updated #735 to emphasize that java must be installed.  HTH.

Edward

**Comment by tscv11** [comment]
On Wed, 28 Feb 2018 12:18:20 +0000 (UTC)
"Edward K. Ream" <notifications@github.com> wrote:

> @tscv11 Please see the first comment of this item for a summary of
> how to install on Linux.  It works for me.

> Please note: LeoVue also requires java.  I uses apt-get to install a
> jdk, don't remember the details. `javac --version` gives  1.8.0_151

Noted and done. Leovue appears to be working now.

-- 

Thank-you for your assistance,

tscv11

**Comment by edreamleo** [comment]
On Wed, Feb 28, 2018 at 7:03 AM, tscv11 <notifications@github.com> wrote:

> Please note: LeoVue also requires java. I uses apt-get to install a
> > jdk, don't remember the details. `javac --version` gives 1.8.0_151
>
> Noted and done. Leovue appears to be working now.
>

​Excellent.

Edward

**Comment by tscv11** [comment]
My Leovue/leo4sqlite demo site is temporarily down for unknown reasons. If possible I will work with Joe Orr to get it back up as soon as possible, or find an answer some other way. My apologies - I am very new to most web technologies other than HTML and CSS, and I've never had a real web page before.

tscv11
