### ISSUE TITLE
`pip install leo` fails to pre-install semantic_version

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#745]
### Recipe
```
conda create -n leo-git
activate leo-git
conda install pip pyqt5
pushd D:\github\leo-editor
git checkout master
git pull
```
```
(leo-git) D:\github\leo-editor
> pip install -e .
Obtaining file:///D:/github/leo-editor
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\github\leo-editor\setup.py", line 10, in <module>
        import semantic_version
    ModuleNotFoundError: No module named 'semantic_version'
```
### Expected
...that pip would install semantic_version before attempting to install leo.

This is a minor issue and shouldn't block release. It's easy work around the issue by inserting `pip install semantic_version` before `pip install -e .\leo-editor` but it would be better to not have to work around.

**Comment by maphew** [comment]
Closed with commit 8622289 in #847. Semantic_version still isn't installed early. If import fails we fall back to internal version. Semantic_version _is_ installed at end though so will be available in future pip install/upgrade calls. See comments in #847 re: the upstream problem.
