### ISSUE TITLE
`contract-all-other-nodes` gives traceback

### ISSUE THREAD

**Issue by tbnorth** [leo-editor/leo-editor#749]
```
Leo 5.7 final, build 20180227010945, Tue Feb 27 01:09:45 CST 2018
Git repo info: branch = master, commit = c9764e545f62
Python 2.7.12, PyQt version 5.5.1
linux2

Traceback (most recent call last):

  File "/home/tbrown/local/leo-editor/leo/core/leoCommands.py", line 2011, in executeAnyCommand
    return command(event)

  File "/home/tbrown/local/leo-editor/leo/core/leoGlobals.py", line 2334, in commander_command_wrapper
    method(event=event)

  File "/home/tbrown/local/leo-editor/leo/commands/commanderOutlineCommands.py", line 163, in contractAllOtherNodes
    c.contractIfNotCurrent(c, p, leaveOpen)

AttributeError: 'Commands' object has no attribute 'contractIfNotCurrent'
```

**Comment by edreamleo** [comment]
On Tue, Feb 27, 2018 at 8:57 AM, Terry Brown <notifications@github.com>
wrote:

> Leo 5.7 final, build 20180227010945, Tue Feb 27 01:09:45 CST 2018
> Git repo info: branch = master, commit = c9764e545f62
>
>
​Wow.  Perfect timing. 5 minutes later would have been too late. I was just
about to regenerate 5.7 final.

Fixed in 5.7 final and master at 049e540.

Edward

**Comment by tbnorth** [comment]
Still getting traceback here:
```
Traceback (most recent call last):

  File "/home/tbrown/local/leo-editor/leo/core/leoCommands.py", line 2011, in executeAnyCommand
    return command(event)

  File "/home/tbrown/local/leo-editor/leo/core/leoGlobals.py", line 2334, in commander_command_wrapper
    method(event=event)

  File "/home/tbrown/local/leo-editor/leo/commands/commanderOutlineCommands.py", line 163, in contractAllOtherNodes
    contractIfNotCurrent(c, p, leaveOpen)

  File "/home/tbrown/local/leo-editor/leo/commands/commanderOutlineCommands.py", line 171, in contractIfNotCurrent
    c.contractIfNotCurrent(child, leaveOpen)

AttributeError: 'Commands' object has no attribute 'contractIfNotCurrent'
```

```
Leo 5.7 final, build 20180227091711, Tue Feb 27 09:17:11 CST 2018
Git repo info: branch = master, commit = 049e54082e80
Python 2.7.12, PyQt version 5.5.1
```

**Comment by edreamleo** [comment]
On Tue, Feb 27, 2018 at 10:06 AM, Terry Brown <notifications@github.com>
wrote:

> Still getting traceback here:
>
​Too bad. 5.7 is out the door.  I'm mightily unimpressed with pylint.

Edward

**Comment by edreamleo** [comment]
Rev be4522b should fix this.  Please reopen if it doesn't.

**Comment by edreamleo** [comment]
Rev 2c288fb fixes yet another crasher in the code, this one caught by pylint.
