### ISSUE TITLE
g.glob_glob may have broken bookmarks/urls/unls on Windows

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#812]
Rev 8ab89ca6f5a1 replaces glob.glob by g.glob_glob throughout Leo's core.  It may have broken the bookmarks plugin and ruined existing bookmarks.

Rev 1228671 removes the call to g.glob_glob from the PickleShareDB.keys method.  Imo, it is clearly *never* correct to change backslashes to slashes in this class.

The bookmarks plugin uses c.db, which is/can be a PickleShareDB object.  Thus, the call to g.glob_glob in PickleShareDB.keys was likely the culprit.

There are no calls to glob.glob or g.glob_glob in bookmarks.py, but BookMarkDisplayProvider.ns_provide does call g.recursiveUNLFind.

Revs ed74121 and 96ba543 attempt to make g.recursiveUNLFind more robust.  Clearly, however, this method was not ultimately to blame.

**Summary**

As noted above, the bookmarks plugin uses c.db. Thus, the call to g.glob_glob in PickleShareDB.keys was likely the culprit.

A cff on g.glob_glob reveals no other obviously dubious calls in Leo's core. Afaik, there are no calls to g.glob_glob relating to url's or unl's.

**Original Crash Report**

Lewis Neal reports this:
QQQ
After a recent commit 8ab89ca6f5a1, my bookmarks failed to display.
I right-clicked over a pane divider and selected Load Layout > bookmarks_name

Leo then crashed with a dialog box [python has stopped working]

Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\nested_splitter.py", line 350, in cb
    splitter.context_cb(id_, index)
  File "N:\git\leo-editor\leo\plugins\nested_splitter.py", line 650, in context_cb
    provided = provider.ns_do_context(id_, self, index)
  File "N:\git\leo-editor\leo\plugins\free_layout.py", line 311, in ns_do_context
    self.get_top_splitter().load_layout(layout)
  File "N:\git\leo-editor\leo\plugins\nested_splitter.py", line 1071, in load_layout
    new.load_layout(i, level + 1)
  File "N:\git\leo-editor\leo\plugins\nested_splitter.py", line 1073, in load_layout
    provided = self.get_provided(i)
  File "N:\git\leo-editor\leo\plugins\nested_splitter.py", line 1125, in get_provided
    provided = provider.ns_provide(id_)
  File "N:\git\leo-editor\leo\plugins\bookmarks.py", line 1212, in ns_provide
    ok, depth, other_p = g.recursiveUNLFind(UNL.split('-->'), other_c)
  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 3813, in recursiveUNLFind
    target = unlList[depth]
IndexError: list index out of range
[end]

Leo Log Window
Leo 5.8 devel, build 20180307231313, Wed Mar 7 23:13:13 PST 2018
Git repo info: branch = devel, commit = a7ad18cbb012
Python 3.6.4, PyQt version 5.10.1
Windows 10 AMD64 (build 10.0.16299) SP0
isPython3: True
QQQ

**Comment by edreamleo** [comment]
I am going to close this item.  Please reopen if problems remain.
