### ISSUE TITLE
started  cd7d8c0 Leo is stalled with a splashscreen.

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#831]
Just started  cd7d8c0
Leo is stalled with a splashscreen.

Traceback (most recent call last):
  File "N:\git\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "N:\git\leo-editor\leo\core\runLeo.py", line 74, in run
    g.app.loadManager.load(fileName, pymacs)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2274, in load
    ok = lm.doPostPluginsInit()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2329, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()
  File "N:\git\leo-editor\leo\core\leoApp.py", line 2390, in openEmptyWorkBook
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3134, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 3158, in openFileByName
    previousSettings=previousSettings)
  File "N:\git\leo-editor\leo\core\leoApp.py", line 1565, in newCommander
    return leoCommands.Commands(fileName, relativeFileName, gui, previousSettings)
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 82, in __init__
    c.finishCreate()
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 405, in finishCreate
    c.frame.finishCreate()
  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 2085, in finishCreate
    f.top = g.app.gui.frameFactory.createFrame(f)
  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 4682, in createFrame
    dw.construct(master=tabw)
  File "N:\git\leo-editor\leo\plugins\qt_frame.py", line 116, in construct
    c.styleSheetManager.set_style_sheets(top=self, all=True)
  File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1703, in set_style_sheets
    sheet = self.expand_css_constants(sheet)
  File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1731, in expand_css_constants
    sheet = self.replace_indicator_constants(sheet)
  File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1918, in replace_indicator_constants
    close_path = self.find_icon_path('tree-image-closed')
  File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1516, in find_icon_path
    for directory in self.compute_icon_directories():
  File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1489, in compute_icon_directories
    for directory in self.compute_theme_directories():
  File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1503, in compute_theme_directories
    directory = g.os_path_normslashes(g.app.theme_directory)
  File "N:\git\leo-editor\leo\core\leoGlobals.py", line 6590, in os_path_normslashes
    path = path.replace('\\','/')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by edreamleo** [comment]
Sorry about that.  Please try d08c779.

**Comment by LewisNeal** [comment]
Thanks for the fix.

**Comment by edreamleo** [comment]
On Tue, Mar 20, 2018 at 6:24 PM, LewisNeal <notifications@github.com> wrote:

> Thanks for the fix.
>
​You're welcome.

Edward
