### ISSUE TITLE
Leo crashes on non English system

### ISSUE THREAD

**Issue by manipuladordedados** [leo-editor/leo-editor#832]
I've installed Leo 5.7 via pip and aur on Arch Linux but when i try to run this error occurs:

```Invalid language code for Enchant 'en_US'
Using "en_US" instead
Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/leo/commands/spellCommands.py", line 374, in open_dict_file
    d = enchant.DictWithPWL(language, fn)

  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 811, in __init__
    Dict.__init__(self,tag,broker)

  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 562, in __init__
    _EnchantObject.__init__(self)

  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 168, in __init__
    self._init_this()

  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 569, in _init_this
    this = self._broker._request_dict_data(self.tag)

  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 310, in _request_dict_data
    self._raise_error(eStr % (tag,),DictNotFoundError)

  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 258, in _raise_error
    raise eclass(default)

enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/leo/commands/spellCommands.py", line 374, in open_dict_file
    d = enchant.DictWithPWL(language, fn)
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 811, in __init__
    Dict.__init__(self,tag,broker)
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 562, in __init__
    _EnchantObject.__init__(self)
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 168, in __init__
    self._init_this()
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 569, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 310, in _request_dict_data
    self._raise_error(eStr % (tag,),DictNotFoundError)
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 258, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/leo", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/python3.6/site-packages/leo/core/runLeo.py", line 74, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/usr/lib/python3.6/site-packages/leo/core/leoApp.py", line 2209, in load
    ok = lm.doPostPluginsInit()
  File "/usr/lib/python3.6/site-packages/leo/core/leoApp.py", line 2841, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()
  File "/usr/lib/python3.6/site-packages/leo/core/leoApp.py", line 2902, in openEmptyWorkBook
    c = lm.loadLocalFile(fn, gui=g.app.gui, old_c=None)
  File "/usr/lib/python3.6/site-packages/leo/core/leoApp.py", line 3067, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)
  File "/usr/lib/python3.6/site-packages/leo/core/leoApp.py", line 3091, in openFileByName
    previousSettings=previousSettings)
  File "/usr/lib/python3.6/site-packages/leo/core/leoApp.py", line 1548, in newCommander
    return leoCommands.Commands(fileName, relativeFileName, gui, previousSettings)
  File "/usr/lib/python3.6/site-packages/leo/core/leoCommands.py", line 82, in __init__
    c.finishCreate()
  File "/usr/lib/python3.6/site-packages/leo/core/leoCommands.py", line 417, in finishCreate
    c.frame.log.finishCreate()
  File "/usr/lib/python3.6/site-packages/leo/plugins/qt_frame.py", line 3147, in finishCreate
    c.spellCommands.openSpellTab()
  File "/usr/lib/python3.6/site-packages/leo/commands/spellCommands.py", line 477, in openSpellTab
    self.handler = SpellTabHandler(c, tabName)
  File "/usr/lib/python3.6/site-packages/leo/commands/spellCommands.py", line 717, in __init__
    self.spellController = EnchantWrapper(c)
  File "/usr/lib/python3.6/site-packages/leo/commands/spellCommands.py", line 332, in __init__
    g.app.spellDict = self.d = self.open_dict_file(fn)
  File "/usr/lib/python3.6/site-packages/leo/commands/spellCommands.py", line 379, in open_dict_file
    d = enchant.Dict(language)
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 562, in __init__
    _EnchantObject.__init__(self)
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 168, in __init__
    self._init_this()
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 569, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 310, in _request_dict_data
    self._raise_error(eStr % (tag,),DictNotFoundError)
  File "/usr/lib/python3.6/site-packages/enchant/__init__.py", line 258, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found
```

I don't use en_US as the default language on my system.

**Comment by edreamleo** [comment]
On Thu, Mar 22, 2018 at 8:33 AM, Valter Nazianzeno <notifications@github.com
> wrote:

> I've installed Leo 5.7 via pip and aur on Arch Linux but when i try to run
> this error occurs:
>
> Using "en_US" instead
> Traceback (most recent call last):
>
> ​Thanks for this report. Rev d45a6ca suppresses the traceback and gives a
more informative message.

In particular, it says: Use @string enchant_language to specify your
language.

Edward

**Comment by veksha** [comment]
Hello. Got similar crash.
and what do you mean by "Use @string enchant_language to specify your language" ?
What should I do with this?

```Console
F:\MySSDPrograms\leo-editor>python launchLeo.py


** (python3.10.exe:14804): WARNING **: 00:46:35.380: Error loading plugin: 'C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\data\mingw64/lib/enchant-2\enchant_hunspell.dll': Не найден указанный модуль.

Leo 6.6.3-devel, devel branch, build 4eaacdf7e5
2022-06-29 04:10:01 -0500
Python 3.10.5, PyQt version 6.3.0
Windows 10 AMD64 (build 10.0.22000) SP0
Invalid language code for Enchant 'en-US'
Using "en_US" instead
Use @string enchant_language to specify your language
Can not create empty workbook
Traceback (most recent call last):

  File "F:\MySSDPrograms\leo-editor\leo\commands\spellCommands.py", line 355, in open_dict_file
    d = enchant.DictWithPWL(language, fn)

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 781, in __init__
    super().__init__(tag, broker)

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 542, in __init__
    super().__init__()

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 144, in __init__
    self._init_this()

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 549, in _init_this
    this = self._broker._request_dict_data(self.tag)

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 287, in _request_dict_data
    self._raise_error(e_str % (tag,), DictNotFoundError)

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 233, in _raise_error
    raise eclass(default)

enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found
Please check https://pyenchant.github.io/pyenchant/ for details


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "F:\MySSDPrograms\leo-editor\leo\core\leoApp.py", line 2267, in doPostPluginsInit
    c1 = lm.openEmptyWorkBook()  # Calls LM.loadLocalFile.

  File "F:\MySSDPrograms\leo-editor\leo\core\leoApp.py", line 2311, in openEmptyWorkBook
    c = self.loadLocalFile(fn2, gui=g.app.gui, old_c=None)

  File "F:\MySSDPrograms\leo-editor\leo\core\leoApp.py", line 2935, in loadLocalFile
    c = lm.openFileByName(fn, gui, old_c, previousSettings)

  File "F:\MySSDPrograms\leo-editor\leo\core\leoApp.py", line 2991, in openFileByName
    c = g.app.newCommander(

  File "F:\MySSDPrograms\leo-editor\leo\core\leoApp.py", line 1476, in newCommander
    c = leoCommands.Commands(fileName,

  File "F:\MySSDPrograms\leo-editor\leo\core\leoCommands.py", line 80, in __init__
    c.finishCreate()  # Slightly slow.

  File "F:\MySSDPrograms\leo-editor\leo\core\leoCommands.py", line 393, in finishCreate
    c.frame.log.finishCreate()

  File "F:\MySSDPrograms\leo-editor\leo\plugins\qt_frame.py", line 3139, in finishCreate
    c.spellCommands.openSpellTab()

  File "F:\MySSDPrograms\leo-editor\leo\commands\spellCommands.py", line 443, in openSpellTab
    self.handler = SpellTabHandler(c, tabName)

  File "F:\MySSDPrograms\leo-editor\leo\commands\spellCommands.py", line 678, in __init__
    self.spellController = EnchantWrapper(c)

  File "F:\MySSDPrograms\leo-editor\leo\commands\spellCommands.py", line 314, in __init__
    g.app.spellDict = self.d = self.open_dict_file(fn)

  File "F:\MySSDPrograms\leo-editor\leo\commands\spellCommands.py", line 360, in open_dict_file
    d = enchant.Dict(language)

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 542, in __init__
    super().__init__()

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 144, in __init__
    self._init_this()

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 549, in _init_this
    this = self._broker._request_dict_data(self.tag)

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 287, in _request_dict_data
    self._raise_error(e_str % (tag,), DictNotFoundError)

  File "C:\Users\yura\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\enchant\__init__.py", line 233, in _raise_error
    raise eclass(default)

enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found
Please check https://pyenchant.github.io/pyenchant/ for details
```

**Comment by veksha** [comment]
tried to install enchant from pypi.org, but no luck.
finally these commands helped.

```
pip uninstall pyenchant
pip install --no-binary pyenchant pyenchant
```

**Comment by edreamleo** [comment]
@veksha Thanks for your report. As the traceback shows, this is a bug in pyenchant, not Leo.
