### ISSUE TITLE
Cannot Open Any Non Leo File From Command Line

### ISSUE THREAD

**Issue by technatica** [leo-editor/leo-editor#843]
Tested with *.csv, *.txt, *.log.

`leo somefile.txt` where the file exists in the CWD of the terminal.

Traceback (most recent call last):
  File "./launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/home/chris/leo-editor/leo/core/runLeo.py", line 74, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2275, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2453, in doPrePluginsInit
    lm.readGlobalSettingsFiles()
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2213, in readGlobalSettingsFiles
    theme_path = lm.computeThemeFilePath()
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 1829, in computeThemeFilePath
    theme_c = lm.openSettingsFile(path)
  File "/home/chris/leo-editor/leo/core/leoApp.py", line 2181, in openSettingsFile
    readAtFileNodesFlag=False, silent=True)
  File "/home/chris/leo-editor/leo/core/leoFileCommands.py", line 874, in openLeoFile
    silent=silent,
  File "/home/chris/leo-editor/leo/core/leoFileCommands.py", line 732, in getLeoFile
    theFile.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by edreamleo** [comment]
Fixed at 5a782dc.
