### ISSUE TITLE
Stickynotes AttributeError: 'Commands' object has no attribute 'cacher'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#935]
Stickynotes plugin command 'tabula-show' causes Leo to hard crash.

Traceback (most recent call last):
  File "N:\git\leo-editor\leo\plugins\stickynotes.py", line 589, in delayed_load
    self.load_states()
  File "N:\git\leo-editor\leo\plugins\stickynotes.py", line 678, in load_states
    if not self.c.cacher.db:
AttributeError: 'Commands' object has no attribute 'cacher'
[end]

Leo Log Window
Leo 5.7.4 devel, build 20180607085129, Thu Jun 7 08:51:29 CDT 2018
Git repo info: branch = fast-read, commit = 1ff1e575f2ce
Python 3.6.5, PyQt version 5.11.1
Windows 10 AMD64 (build 10.0.17134) SP0
isPython3: True

**Comment by LewisNeal** [comment]
I also get this traceback with command Stickynotes>About and Valuespace>About
Leo remains running.

Traceback (most recent call last):

   File "N:\git\leo-editor\leo\core\leoCommands.py", line 2071, in executeAnyCommand
return command(event)

   File "N:\git\leo-editor\leo\plugins\plugins_menu.py", line 276, in about
c.putHelpFor(msg, short_title=self.name)

   File "N:\git\leo-editor\leo\core\leoCommands.py", line 2432, in putHelpFor
g.app.gui.put_help(c, s, short_title)

   File "N:\git\leo-editor\leo\plugins\qt_gui.py", line 1099, in put_help
vr.show_scrolled_message(tag='Apropos', kw=kw)

   File "N:\git\leo-editor\leo\plugins\viewrendered.py", line 325, in show_scrolled_message
vr = viewrendered(event=kw)

   File "N:\git\leo-editor\leo\plugins\viewrendered.py", line 367, in viewrendered
layouts[h] = c.cacher.db.get('viewrendered_default_layouts', (None, None))

AttributeError: 'Commands' object has no attribute 'cacher'

**Comment by edreamleo** [comment]
On Wed, Jun 27, 2018 at 6:33 PM, LewisNeal <notifications@github.com> wrote:

> Stickynotes plugin command 'tabula-show' causes Leo to hard crash.
>
​Fixed at b336001aa by changing c.cacher.db to c.db.  This problem also
affected the viewrendered.py plugin, but not vr2.

Edward
