### ISSUE TITLE
badUnlink **can not happen:

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#937]
I just suffered this traceback (in the pdb branch) while moving an `@file` node upward.  The pdb branch is based on devel, not fast-read, so it's not entirely clear whether fast-read is implicated at all. 

In any case, this is an extremely serious bug. Note that the check-outline command passed after this traceback.
```
Traceback (most recent call last):
  File "c:\leo.repo\leo-editor\leo\core\leoCommands.py", line 2073, in executeAnyCommand
    return command(event)
  File "c:\leo.repo\leo-editor\leo\core\leoGlobals.py", line 281, in commander_command_wrapper
    method(event=event)
  File "c:\leo.repo\leo-editor\leo\commands\commanderOutlineCommands.py", line 1346, in moveOutlineUp
    p.moveAfter(back2)
  File "c:\leo.repo\leo-editor\leo\core\leoNodes.py", line 1482, in moveAfter
    p._unlink()
  File "c:\leo.repo\leo-editor\leo\core\leoNodes.py", line 1069, in _unlink
    child._cutLink(n, parent_v)
  File "c:\leo.repo\leo-editor\leo\core\leoNodes.py", line 2557, in _cutLink
    child._cutParentLinks(parent=v)
  File "c:\leo.repo\leo-editor\leo\core\leoNodes.py", line 2565, in _cutParentLinks
    child._cutParentLinks(parent=v)
  File "c:\leo.repo\leo-editor\leo\core\leoNodes.py", line 2562, in _cutParentLinks
    v.parents.remove(parent)
ValueError: list.remove(x): x not in list
badUnlink **can not happen: children[6] != p.v
badUnlink parent_v.children...
 [
    <VNode ekr.20111002001133.2144 Startup>,
    <VNode ekr.20170227092417.1 Recent settings>,
    <VNode ekr.20150115062912.1 Recursive import script>,
    <VNode ekr.20180621091242.1 Files>,
    <VNode ekr.20180126174239.1 Do not delete>,
    <VNode ekr.20171027091130.1 Recent>,
    <VNode ekr.20180627111650.1 c.db test>,
    <VNode ekr.20180628060752.1 @button xpdb>,
    <VNode ekr.20180628063040.1 pdb>,
    <VNode ekr.20180628123216.2 @path C:/leo.repo/blinker>,
    <VNode ekr.20180628131301.1 script: signal manager.py>,
    <VNode ekr.20180628155633.1 script: separate threads>,
    <VNode ekr.20180629103728.1 script: debugger thread1>,
    <VNode ekr.20180629090928.1 script: debugger thread2>
]
badUnlink parent_v <VNode hidden-root-vnode-gnx <hidden root vnode>>
badUnlink parent_v.children[n] <VNode ekr.20180627111650.1 c.db test>
badUnlink child <VNode ekr.20180602113546.1 @file fast_read_test.txt>
badUnlink ** callers: commander_command_wrapper,moveOutlineUp,moveAfter,_unlink
```

**Comment by edreamleo** [comment]
I'm going to close this.  I'll reopen if it happens again.
