### ISSUE TITLE
Request: Better error reporting on startup for missing Qt

### ISSUE THREAD

**Issue by iskunk** [leo-editor/leo-editor#953]
Currently, if I run the Leo devel branch on an Ubuntu Linux system without PyQt installed, I see this:
```
$ ./launchLeo.py 

import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'skunk'
reading settings in /home/skunk/leo-editor/leo/config/leoSettings.leo
Traceback (most recent call last):
  File "./launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "/home/skunk/leo-editor/leo/core/runLeo.py", line 72, in run
    g.app.loadManager.load(fileName, pymacs)
  File "/home/skunk/leo-editor/leo/core/leoApp.py", line 2211, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "/home/skunk/leo-editor/leo/core/leoApp.py", line 2397, in doPrePluginsInit
    lm.createGui(pymacs)
  File "/home/skunk/leo-editor/leo/core/leoApp.py", line 2551, in createGui
    lm.createSpecialGui(gui_option, pymacs, script, windowFlag)
  File "/home/skunk/leo-editor/leo/core/leoApp.py", line 2565, in createSpecialGui
    g.app.createDefaultGui()
  File "/home/skunk/leo-editor/leo/core/leoApp.py", line 1021, in createDefaultGui
    app.createQtGui(fileName, verbose=verbose)
  File "/home/skunk/leo-editor/leo/core/leoApp.py", line 1043, in createQtGui
    import leo.plugins.qt_gui as qt_gui
  File "/home/skunk/leo-editor/leo/plugins/qt_gui.py", line 12, in <module>
    import leo.plugins.qt_events as qt_events
  File "/home/skunk/leo-editor/leo/plugins/qt_events.py", line 46, in <module>
    class LeoQtEventFilter(QtCore.QObject):
AttributeError: 'NoneType' object has no attribute 'QObject'
```

This kind of error message is confusing to users, not least because it makes no mention of the immediate problem in need of addressing: the lack of PyQt. What I'd like to see is something along these lines:
```
$ ./launchLeo.py 
leoQt.py: can not import either PyQt4 or PyQt5.
leoQt.py: Please install a suitable version of PyQt.
```
I.e. a straightforward message, and no stack trace. (Obviously, stack traces and other programmer-friendly output should be available if the appropriate debug/trace mode is enabled.)

I've tried to put together some modifications to implement this behavior, but have run into difficulties with Leo's console mode, which also tries to import Qt even though it seems like that should not be necessary. I take it console mode uses the non-GUI portions of Qt (QtCore)?

**Comment by edreamleo** [comment]
Fixed at 5d3f2e6 in devel.
