### ISSUE TITLE
Syntax errors with python 3.7.0

### ISSUE THREAD

**Issue by btheado** [leo-editor/leo-editor#956]
Running unit tests in leo using python 3.7.0 give me these syntax errors:
```
created directory: /home/leouser/.leo
reading settings in /leo/leo/config/leoSettings.leo
reading settings in /leo/leo/test/unitTest.leo
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-leouser'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-leouser'

Leo 5.7.4 devel, build 20180815095610, Wed, Aug 15, 2018  9:56:10 AM
Git repo info: branch = devel, commit = 9db824eb3746
Python 3.7.0, PyQt version 5.11.1
linux
** isPython3: True

reading settings in /leo/leo/test/unitTest.leo
created: /home/leouser/.leo/spellpyx.txt
found  2 doctests for leo.core.leoGlobals
found  1 doctests for leo.core.leoTest
...s...
..s..............syntax error in: make_stub_files.py
Traceback (most recent call last):
  File "/leo/leo/core/leoTest.py", line 1247, in checkFileSyntax
    compile(s + '\n', fileName, 'exec')
  File "make_stub_files.py", line 233
    def do_FunctionDef(self, node, async=False):
                                       ^
SyntaxError: invalid syntax

syntax error in: py2cs.py
Traceback (most recent call last):
  File "/leo/leo/core/leoTest.py", line 1247, in checkFileSyntax
    compile(s + '\n', fileName, 'exec')
  File "py2cs.py", line 855
    def do_For(self, node, async=False):
                               ^
SyntaxError: invalid syntax

```

Using similar setup, except with python 3.6, all unit tests pass for me:
```
Leo 5.7.4 devel, build 20180815095610, Wed, Aug 15, 2018  9:56:10 AM
Git repo info: branch = devel, commit = 9db824eb3746
Python 3.6.6, PyQt version 5.11.1
linux
```

**Comment by beetleb** [comment]
Seems `async` is now a reserved keyword:

https://docs.python.org/3/whatsnew/3.7.html

**Comment by edreamleo** [comment]
Rev 0e015aa in devel changes the async kwarg to async_flag.  It also fixes/suppresses some pylint complaints.  Please reopen if necessary.

**Comment by btheado** [comment]
make_stub_files.py and py2cs.py both have the issue and I only see the fix in make_stub_files.py

```
syntax error in: py2cs.py
Traceback (most recent call last):
  File "/leo/leo/core/leoTest.py", line 1247, in checkFileSyntax
    compile(s + '\n', fileName, 'exec')
  File "py2cs.py", line 855
    def do_For(self, node, async=False):
                               ^
SyntaxError: invalid syntax
```

**Comment by btheado** [comment]
Thanks. All test pass for me now in python 3.7.0

**Comment by edreamleo** [comment]
On Sat, Aug 18, 2018 at 10:30 AM, btheado <notifications@github.com> wrote:

> Thanks. All test pass for me now in python 3.7.0
>

Thanks for the confirmation.

Edward
