### ISSUE TITLE
Unable to run leo, python import error

### ISSUE THREAD

**Issue by shanavas786** [leo-editor/leo-editor#957]
I have installed leo in a virtualenv with python3. Installation succeeded. But when opened, it throws the following  error.
 
```
leoQt.py: can not fully import PyQt5.
Traceback (most recent call last):
  File "/home/<user>/opt/leo/bin/leo", line 7, in <module>
    from leo.core.runLeo import run
  File "/home/<user>/opt/leo/lib/python3.5/site-packages/leo/core/runLeo.py", line 27, in <module>
    leoGlobals.app = leoApp.LeoApp()
  File "/home/<user>/opt/leo/lib/python3.5/site-packages/leo/core/leoApp.py", line 324, in __init__
    import leo.core.leoFrame as leoFrame
  File "/home/<user>/opt/leo/lib/python3.5/site-packages/leo/core/leoFrame.py", line 13, in <module>
    import leo.core.leoColorizer as leoColorizer
  File "/home/<user>/opt/leo/lib/python3.5/site-packages/leo/core/leoColorizer.py", line 9, in <module>
    from leo.core.leoQt import Qsci, QtGui, QtWidgets # isQt5, QtCore
  File "/home/<user>/opt/leo/lib/python3.5/site-packages/leo/core/leoQt.py", line 76, in <module>
    qt_version = QtCore.QT_VERSION_STR
NameError: name 'QtCore' is not defined
```
os: ubuntu 16.04

**Comment by brownterryn** [comment]
Hi @shanavas786,
The following just worked for me in Ubuntu 18.04
```shell
virtualenv -p python3 venv
source venv/bin/activate
pip install leo
leo
```

I'll attempt to try it in a 16.04 image to see what happens.

**Comment by terminalcommand** [comment]
Known issue, current workaround is to explicitly install PyQt 5.10.0.

Following commands worked for me:
`$ python3 -m venv leo-editor-venv
$ cd leo-editor-venv
$ bin/pip install leo
$ bin/pip install PyQt5==5.10.0
$ bin/leo
`
[https://github.com/leo-editor/leo-editor/issues/944](Previous issue)

**Comment by edreamleo** [comment]
I am going to close this issue now.  Please reopen if desired.
