### ISSUE TITLE
Run all unit tests for TravisCI

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#989]
Rev 3a233a52a completes most of the work.  There are some nits concerning Leo's bridge, so some of the unit tests are disabled if g.in_bridge is True, but that's a nit.

To run the tests, do `python run_travis_unit_tests.py` from the leo-editor folder.  This script runs all the unit tests using Leo's bridge and does sys.exit(0) if all went well and sys.exit(1) otherwise.

**Comment by maphew** [comment]
```
> python run_travis_unit_tests.py
Traceback (most recent call last):
  File "run_travis_unit_tests.py", line 14, in <module>
    silent=False, verbose=False)
  File "D:\code-maphew\leo-editor\leo\core\leoBridge.py", line 71, in controller
    verbose)
  File "D:\code-maphew\leo-editor\leo\core\leoBridge.py", line 89, in __init__
    self.initLeo()
  File "D:\code-maphew\leo-editor\leo\core\leoBridge.py", line 146, in initLeo
    raise ValueError("unable to set LeoID.")
ValueError: unable to set LeoID.
```

**Comment by maphew** [comment]
Oh, I didn't actually have a LeoID! Something unset my HOME and I didn't notice. All good now:
```
{...}
Ran 930 tests in 62.558s
OK (skipped=47)
Travis unit tests all passed.
```

**Comment by maphew** [comment]
Moved into .travis.yml and pushed commit 4a35c008bb40ecff4716477a4c31442649f86851. Let's see what travis thinks of it

**Comment by maphew** [comment]
Unlike my Windows machine in Travis it picked up a LeoID from the env. However a missing dependency seems to have failed it:
```
$ python run_travis_unit_tests.py
setting leoID from os.getenv('USER'): 'travis'
Traceback (most recent call last):
  File "run_travis_unit_tests.py", line 14, in <module>
    silent=False, verbose=False)
  File "/home/travis/build/leo-editor/leo-editor/leo/core/leoBridge.py", line 71, in controller
    verbose)
  File "/home/travis/build/leo-editor/leo-editor/leo/core/leoBridge.py", line 89, in __init__
    self.initLeo()
  File "/home/travis/build/leo-editor/leo-editor/leo/core/leoBridge.py", line 152, in initLeo
    lm.readGlobalSettingsFiles()
  File "/home/travis/build/leo-editor/leo-editor/leo/core/leoApp.py", line 2168, in readGlobalSettingsFiles
    commanders = [lm.openSettingsFile(path) for path in paths]
  File "/home/travis/build/leo-editor/leo-editor/leo/core/leoApp.py", line 2144, in openSettingsFile
    c = g.app.newCommander(fn)
  File "/home/travis/build/leo-editor/leo-editor/leo/core/leoApp.py", line 1567, in newCommander
    return leoCommands.Commands(fileName, relativeFileName, gui, previousSettings)
  File "/home/travis/build/leo-editor/leo-editor/leo/core/leoCommands.py", line 73, in __init__
    c.initObjects(self.gui)
  File "/home/travis/build/leo-editor/leo-editor/leo/core/leoCommands.py", line 285, in initObjects
    import leo.core.leoDebugger as leoDebugger
  File "/home/travis/build/leo-editor/leo-editor/leo/core/leoDebugger.py", line 76, in <module>
    import queue
ImportError: No module named queue
The command "python run_travis_unit_tests.py" exited with 1.
```

**Comment by edreamleo** [comment]
On Tue, Oct 9, 2018 at 11:41 PM matt wilkie <notifications@github.com>
wrote:

> Looks like a python2/3 problem -
> https://stackoverflow.com/questions/25175531/importerror-no-module-named-queue
>
A milestone!  Continuous integration finds its first bug.  Fixed in devel
at cc8a3ae6b.

Edward

**Comment by edreamleo** [comment]
I am going to close this because there is now a green check mark next to devel.
